### ISSUE TITLE
[DISCUSSION] Add SkyWalking go SDK as a plugin

### ISSUE THREAD

**Issue by wu-sheng** [mosn/mosn#1027]
### The New Feature

Does the MOSN have a plugin or filter mechanism to add a tracing/APM agent? 
SkyWalking has its LUA agent for Nginx, Kong and OpenResty, https://github.com/apache/skywalking-nginx-lua
As it has the go agent https://github.com/SkyAPM/go2sky, so if you have the mechanism, we could try to invite our committer, @arugal to work with your team.

WDYT?

**Comment by rootsongjc** [comment]
@wangfakang @taoyuanyuan @ peacocktrain

**Comment by wu-sheng** [comment]
FYI @kezhenxu94, if you have interests, welcome to watch and join.

**Comment by taoyuanyuan** [comment]
welcome to join in！
We are also planning to support opentracing，we could work together.
MOSN supports plugin and filter 
example：https://github.com/mosn/mosn/blob/master/pkg/filter/stream/mixer/mixer.go

**Comment by wu-sheng** [comment]
OpenTracing already makes things more complex than they should be. It is just APIs of jaeger only.

I will keep the thing for SkyWalking native only.

**Comment by taoyuanyuan** [comment]
yeah，Support skywalking also one of our plans, We are very welcome to add skywalking.
I see that Huawei cloud supports mixer APM adatper， does the skywalking support it too？

btw,mosn can easily support various implementations of tracing by [framework](https://github.com/mosn/mosn/blob/master/pkg/trace/driver.go) 
PR welcome   ^_^
![image](https://user-images.githubusercontent.com/2707372/76156034-74411180-612f-11ea-932f-8967b8564e25.png)

**Comment by peacocktrain** [comment]
hi～@wu-sheng 
I'm a developer.
I see that skywalking's go client is well encapsulated, but I have a few questions about whether I should choose skywalking as APM to add to our own mosn.
Which are skywalking's dependencies? 
Can skywalking be easily deployed on k8s preferably with a operator management?
Can skywalking automatically collect exportor on k8s ?

**Comment by wu-sheng** [comment]
> Which are skywalking's dependencies?

Is this question for go agent or backend?  

> Can skywalking be easily deployed on k8s preferably with a operator management?
Can skywalking automatically collect exportor on k8s ?

We have k8s helm3 already, https://github.com/apache/skywalking-kubernetes. So these wouldn't be an issue.

**Comment by peacocktrain** [comment]
> Is this question for go agent or backend?
backend
> We have k8s helm3 already, https://github.com/apache/skywalking-kubernetes. So these wouldn't be an issue.
ok, skywalking easy to install in k8s , if exporter push data to skywalking，that's it.

**Comment by wu-sheng** [comment]
>backend

That is complex and a long list. Ff you have interests, read our official LICENSE, https://github.com/apache/skywalking/blob/master/dist-material/release-docs/LICENSE#L204-L408

**Comment by arugal** [comment]
Hi community.

I read the mosn document and source code, now have a general understanding of mosn.

### Implementation plan
1. Register a `Driver` named `SkyWanling`

```go
trace.RegisterDriver("SkyWalking", trace.NewDefaultDriverImpl())
```
2. Implement `SkyWalkingTracer` and support the http1 protocol

##### tracer configuration:
```json
 "tracing": {
    "enable": true,
    "tracer": "SkyWalking",
    "driver": "SkyWalking",
    "config": {
        "backend_service": "skywalking-oap-server:11800",
        "service_name": "app1"
    }
```

##### span data:
```json
[
  {
    "Refs": null,
    "StartTime": "2020-03-12T21:34:09.035262+08:00",
    "EndTime": "2020-03-12T21:34:09.037031+08:00",
    "OperationName": "/GET/v1",
    "Peer": "",
    "Layer": 3,
    "ComponentID": 49,
    "Tags": [
      {
        "key": "http.method",
        "value": "GET"
      },
      {
        "key": "url",
        "value": "127.0.0.1:2046/v1"
      },
      {
        "key": "status_code",
        "value": "200"
      },
      {
        "key": "bytesReceived",
        "value": "0"
      },
      {
        "key": "bytesSent",
        "value": "400"
      },
      {
        "key": "upstreamHost",
        "value": "127.0.0.1:8080"
      },
      {
        "key": "downstreamLocalAddress",
        "value": "127.0.0.1:2046"
      },
      {
        "key": "mosnProcessTime",
        "value": "577.014µs"
      }
    ],
    "Logs": null,
    "IsError": false,
    "SpanType": 0,
    "TraceID": [
      1584020049035272000,
      0,
      1435709800533376607
    ],
    "SegmentID": [
      1,
      1584020049035283000,
      6763203574148249155
    ],
    "SpanID": 0,
    "ParentSpanID": -1,
    "ParentSegmentID": null
  }
] 
```

**Comment by wu-sheng** [comment]
@arugal Why we need to implement HTTP1? Is gRPC communication not supported?

**Comment by arugal** [comment]
> @arugal Why we need to implement HTTP1? Is gRPC communication not supported?

This refers to intercepting http1 passing through mosn.

**Comment by wu-sheng** [comment]
> This refers to intercepting http1 passing through mosn.

Thanks for clarification. Please continue. I still prefer to write a native SkyWalking filter rather than just tracer implementation.
