### ISSUE TITLE
Can not set proxy correctly with a parameter in a HTTP path.

### ISSUE THREAD

**Issue by yangyongzhi7** [mosn/mosn#1030]
### Your question

In order to know how does filter work in MOSN, I run the mosn instance with configuration :
```examples/codes/filter/commonrule/config.json```
https://github.com/mosn/mosn/blob/master/examples/codes/filter/commonrule/config.json

It returns with 200 code from server by visiting the "http;//127.0.0.1:8080" ,
Then we visit "http;//127.0.0.1:2045" immediately, it still returns OK with code 200.

It seems everything is OK, alright?

For now, we visited the server directly with a command like this:
 ```crul http;//127.0.0.1:8080?aa=a1``` 
 the server return with 200 too.

Then, we need to validate if the filter function can be work, we visit the mosn listener like this:
 ```crul http;//127.0.0.1:2045?aa=a1``` 

it returns with code 400, the response showed as follows:
```
yangyongzhi@yangyongzhis-MacBook-Pro mosn % curl "http://127.0.0.1:2045/serverdetai?aa=a1" -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 2045 (#0)
> GET /serverdetai?aa=a1 HTTP/1.1
> Host: 127.0.0.1:2045
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Mon, 09 Mar 2020 09:24:45 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 15
< Connection: close
<
* Closing connection 0
```

In my opinion, It seem that a HTTP request with a parameter can not be supported by MOSN?

### Environment

- MOSN Version
 **Master** branch.

### Logs

- Paste the logs you see.
The following logs has been found in MOSN console.
```[ERROR] parse query parameters error,parameters = %!(EXTRA string=aa=a1)```

**Comment by wangfakang** [comment]
@yangyongzhi7  Test of the master (Latest commit 2ea7c63) code i'm not reproduce the problem as you said. However, from the log you provided, it may contain illegal input characters.
```
$curl "http://127.0.0.1:2045/serverdetai?aa=a1" -v
* About to connect() to 127.0.0.1 port 2045 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2045 (#0)
> GET /serverdetai?aa=a1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2045
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 20 Mar 2020 11:13:47 GMT
< Content-Type: text/plain
< Content-Length: 429
< 
Method: GET
Protocol: HTTP/1.1
Host: 127.0.0.1:2045
RemoteAddr: 127.0.0.1:27913
RequestURI: "/serverdetai?aa=a1"
URL: &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/serverdetai", RawPath:"", ForceQuery:false, RawQuery:"aa=a1", Fragment:""}
Body.ContentLength: 0 (-1 means unknown)
Close: false (relevant for HTTP/1 only)
TLS: (*tls.ConnectionState)(nil)

Headers:
Accept: */*
User-Agent: curl/7.29.0
* Connection #0 to host 127.0.0.1 left intact

```

**Comment by wangfakang** [comment]
@yangyongzhi7 have any question?

**Comment by wangfakang** [comment]
It  has been fixed, thank you.
