### ISSUE TITLE
Is heartbeater interface unreasonable?

### ISSUE THREAD

**Issue by yiyanghua** [mosn/mosn#1052]
### Your question

Heartbeater Reply 入参数，是不是应该改成xprotocol.XFrame
对于有些RPC来说，HB返回的数据可能需要根据请求里面的clone出来的，不仅是一个id

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by neverhook** [comment]
有没有具体场景可以描述一下呢？因为在一般场景下，可以认为心跳包是不含业务语义的。

**Comment by yiyanghua** [comment]
最简单的例子，我心跳发出去的数据包序列化方式，返回的数据包是不是应该发出去的一致？

**Comment by neverhook** [comment]
以 SOFABolt 协议为例，其协议头中包含 Codec 字段，对应你提到的"序列化方式"。但是在目前 xprotocol 处理心跳包的场景下，Codec 的值并无实际意义，因为并没有需要序列化/反序列化的 payload，此处就算 heartbeat request/response 的 codec 值不一样，也对实际处理没有影响。

当然，从目前的协议设计上来说，心跳包也可以携带 payload，但支持此类场景的话会给框架引入额外的复杂度：除了 Reply，Trigger 的入参签名是否也需要调整？同时，我们在设计上也不鼓励这么做，你可以将 xprotocol 的 heartbeat 支持粒度理解为 HTTP/2 PING frame，这应当是不含业务语义的。

这个问题有一定可参考性，但是目前来看的话还需要有更多适合的场景来支撑。cc @taoyuanyuan

**Comment by neverhook** [comment]
建议可以提供一个具体的场景，并说明其协议心跳报文/回包携带 payload 的必要性

**Comment by yiyanghua** [comment]
1.就像你说的心跳包里面的Codec值，因为没有payload值所以返回什么值都没有太大意义，但从逻辑角度出发是不是应该返回一样值更合理？
2.在一些高级负载策略下，我们是不是可以利用心跳机制来反馈服务提供方的压力？

**Comment by neverhook** [comment]
> 1.就像你说的心跳包里面的Codec值，因为没有payload值所以返回什么值都没有太大意义，但从逻辑角度出发是不是应该返回一样值更合理？

是的，从逻辑上说这样会更合理。

> 2.在一些高级负载策略下，我们是不是可以利用心跳机制来反馈服务提供方的压力？

这个场景我理解更接近于业务策略，而非协议本身的行为定义，即：这种"高级负载策略"是否是包含在协议自身的标准内，如果在框架内集成了该能力，该能力对该协议的所有用户是否都适用？

**Comment by neverhook** [comment]
依据目前的输入情况，输入参数修改是一个合理的建议。但是具体到实现上，Heartbeater 定位还是一个用于心跳保活的能力接口，更高级、更偏向业务的策略定制建议通过 stream filter 等其他扩展机制来进行实现。

**Comment by neverhook** [comment]
Fixed in #1090
