### ISSUE TITLE
Make MOSN support pilot-agent /healthz/ready health check

### ISSUE THREAD

**Issue by trainyao** [mosn/mosn#1057]
### The New Feature

Inorder to make MOSN a sidecar for isito, MOSN need to handle the http request from pilot-agent in it's `/healthz/ready` http endpoint handle logic, this endpoint will be called by k8s readnessprobe probe health check

### Your scenes

mosn istio WG roadmap

### Your advice

1. create a admin endpoint `/stats?usedonly` to reply the data pilot-agent wanted, especially [this keys](https://github.com/istio/istio/blob/1.4.6/pilot/cmd/pilot-agent/status/util/stats.go#L27), to pass [this check](https://github.com/istio/istio/blob/1.4.6/pilot/cmd/pilot-agent/status/ready/probe.go#L83) in pilot-agent, format like:
```text
...
cluster_manager.cluster_added: 70                                                       
cluster_manager.cluster_modified: 0                                            
cluster_manager.cluster_removed: 0                                                    
...
```
2. create a admin endpint `/server_info` to reply [envoy control plane proto](https://github.com/envoyproxy/go-control-plane/blob/v0.9.1/envoy/admin/v2alpha/server_info.pb.go#L108), to pass [this check](https://github.com/istio/istio/blob/1.4.6/pilot/cmd/pilot-agent/status/ready/probe.go#L51), this proto info is needed [here](https://github.com/istio/istio/blob/1.4.6/pilot/cmd/pilot-agent/status/util/server_info.go#L32)

### Environment

- MOSN v0.10.0

**Comment by trainyao** [comment]
thus [this comment](https://github.com/mosn/istio/blob/feature-mosn_adapter/install/kubernetes/helm/istio/files/injection-template.yaml#L316) can be removed

**Comment by wangfakang** [comment]
It  has been supported, thank you.
