### ISSUE TITLE
error updating listener, listener have filter chains count is not 1

### ISSUE THREAD

**Issue by yiyanghua** [mosn/mosn#1058]
### Describe the bug

virtual listener通过ConvertListenerConfig后没有了FilterChains，导致AddOrUpdateListener报上面的错

### Environment

- MOSN master

**Comment by wangfakang** [comment]
@yiyanghua 关于Istio适配修改的改动先参考这个分支上的修改 https://github.com/mosn/mosn/tree/feature-istio_adapter ，后面会merge进master的。你反馈的这个问题在这个分支上是已经修复过的。

**Comment by yiyanghua** [comment]
@wangfakang 多谢

**Comment by yiyanghua** [comment]
@wangfakang 还是这个相关问题，virtualOutbound xds不会下发filter，但是mosn没有看到处理original_dst filter的问题

**Comment by yiyanghua** [comment]
@wangfakang 看的是 https://github.com/mosn/mosn/tree/feature-istio_adapter  这个分支

**Comment by wangfakang** [comment]
fixed PR https://github.com/mosn/mosn/pull/1064 .
