### ISSUE TITLE
Make MOSN support pilot-agent startup params

### ISSUE THREAD

**Issue by trainyao** [mosn/mosn#1071]
### The New Feature

Make MOSN support pilot-agent startup params, so pilot-agent is able to use MOSN as binary path to start

### Your scenes

MOSN Istio WG roadmap

#### advice 1 
MOSN use `urfave/cli` lib to manage cli command, it seems to support only subcommand format, but params from pilot-agent to startup envoy looks like:
```text
 /usr/local/bin/binaryPath -c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster productpage.default --service-node sidecar~10.244.0.86~productpage-v1-7685fd594b-xql9q.default~default.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --log-format [Envoy (Epoch 0)] [%Y-%m-%d %T.%e][%t][%l][%n] %v -l warning --component-log-level misc:error --concurrency 2
```
so to meet the need, maybe MOSN should change another cli manage lib, so start command be like
```text
mosn -c xxx ...
```
and maybe the `stop` `restart` subcommand in urfave/cli can change to be a flag, like:
```text
mosn --stop ...
mosn --restart ...
```
#### advice 2
I'm also thinking that the change can be pilot-agent side, like [this PR](https://github.com/mosn/istio/pull/5), pilot-agent can add a `proxtImplement` flag to choose which sidecar user can use, and mosn style startup params can be differ from envoy, in the pilot-agent
### Environment

- MOSN v0.10.0

**Comment by wangfakang** [comment]
fixed.
