### ISSUE TITLE
support consistent hash routing

### ISSUE THREAD

**Issue by trainyao** [mosn/mosn#1117]
### The New Feature

- support maglev consistent hash algorithm to do route
- convert consistent hash config both from config file and Istio

### Your scenes

MOSN Istio WG roadmap

### Your advice

- use protocol variable to get variables of protocol(such as TCP, HTTP1 HTTP2 or x-protocol), refer to [this PR](https://github.com/mosn/mosn/pull/1107), to let the protocol implements to decide how to get variables of own protocol
- when choosing host,  the routing stage of request, read maglev config info(header/http cookie/ip) in downstream to generate hash for maglev algorithm
- convert config file to maglev config info, both from config file and Istio xds server

### Environment

- MOSN v0.10.0

**Comment by wangfakang** [comment]
It has been support, refer https://github.com/mosn/mosn/pull/1118 https://github.com/mosn/mosn/pull/1218
