### ISSUE TITLE
Improve user configure experience

### ISSUE THREAD

**Issue by cch123** [mosn/mosn#1154]
### The New Feature

Describe the new feature you want to support clearly.

### Your scenes

当前 mosn 的配置文件是巨长的 json，当实例既当 server 又是 client 时，用户配置容易出错。例如出现过 app -> local-mosn-> local-mosn -> remote-mosn -> remote-app 这种情况。

### Your advice

理想的情况下，应该提供交互式 or  界面来生成配置文件，尽量避免手动配置出错

### Environment

- MOSN Version

**Comment by taoyuanyuan** [comment]
#1158

**Comment by cch123** [comment]
https://github.com/mosn/configure

第一个版本已可以生成跑得起 mosn 的配置，待体验后决定是否继续迭代
