### ISSUE TITLE
Optimize the current examples configuration

### ISSUE THREAD

**Issue by wenxuwan** [mosn/mosn#1158]
### The New Feature

Describe the new feature you want to support clearly.

### Your scenes

现有的mosn的example的让人太混淆了，个人理解example是想模拟一个dubbo监听2045端口接受client请求，一个dubbo监听2046端口接收mosn的请求，但现在的example把2045和2046都放到一个里面，让配置文件看起来太难懂了，搞了个闭环一样的！！！

https://github.com/mosn/mosn/blob/master/examples/codes/http-sample/config.json

### Your advice

如果是要模拟我说的场景，那就起两个mosn，不然堆到一个configure里面，对于用户太难理解了。

### Environment

- MOSN Version

**Comment by nejisama** [comment]
你的理解是正确的，就是为了模拟client->mosn->mosn->server的场景
如果拆分成两个配置，那么运行一个example需要两个机器才能跑起来。
因为mosn做了平滑升级，一个机器如果同时存在两个mosn就认为处于平滑升级的状态，最终只会留下一个mosn

**Comment by taoyuanyuan** [comment]
可以看通过配置项默认把平滑升级的能力关闭了，让可以本地运行2个mosn，让exmple更好理解，分为client.json和server.json 两个文件。

**Comment by cch123** [comment]
master 分支已将大部分配置均分离为 client_config.json 和 server_config.json
