### ISSUE TITLE
Support for go1.14 debugging unit tests

### ISSUE THREAD

**Issue by zonghaishang** [mosn/mosn#1168]
### Describe the bug

` go. Mod ` rely on low repository ` github.com/TarsCloud/TarsGo v0.0.0-20181112071624-2 d42457f2025 ` leads to high version go cannot debug the program.  Should be upgraded to a ` github.com/TarsCloud/TarsGo v0.0.0-20190521041003-0022231 bc5b2 `

--- 中文

`go.mod` 依赖低版本库`github.com/TarsCloud/TarsGo v0.0.0-20181112071624-2d42457f2025`导致高版本go无法调式测试程序.
应该升级到`github.com/TarsCloud/TarsGo v0.0.0-20190521041003-0022231bc5b2`

refer: https://github.com/mosn/mosn/pull/1132/commits/0a7c0b4ec2b80ab637724a9da33f7e2e2c2ac45e

### Environment

- MOSN Version

**Comment by wangfakang** [comment]
You can refer to this https://github.com/mosn/mosn/pull/1132, and it fixed in this PR https://github.com/mosn/mosn/pull/1167.

**Comment by zonghaishang** [comment]
> You can refer to this #1132, and it fixed in this PR #1167.
这段需要把性能优化能力迁移到开源，需要在master分支投入开发调试，目前master分支存在这个缺陷 ，你修复的pr在`feature-istio_adapter`分支，预期什么时候合并进master?

**Comment by zonghaishang** [comment]
merged, closed it now.
