### ISSUE TITLE
[Feature] Support regex rewrite for route

### ISSUE THREAD

**Issue by liangyuanpeng** [mosn/mosn#1191]
### The New Feature

Describe the new feature you want to support clearly.

### Your scenes

Describe your use scenes (why need this feature).

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by liangyuanpeng** [comment]
I'm working in this issue.

**Comment by liangyuanpeng** [comment]
In Envoy , if both ``prefix_rewrite`` and `regex_rewrite` are configured, the envoy will exit and return ``Cannot specify both prefix_rewrite and regex_rewrite``.  

So i do the some thing in Mosn, 

``routes_impl.go``#NewRouters
```
for _, route := range vhConfig.Routers {
			if len(route.Route.RegexRewrite.Pattern) > 1 && len(route.Route.PrefixRewrite) > 1 {
				return nil, errors.New("Cannot specify both prefix_rewrite and regex_rewrite")
			}
		}
```  

The reason It's not working  is that mosn ignored this error 


`routes_manager.go`#AddOrUpdateRouters
```
// adds new router
		// if a routerConfig with no routes, it is a valid config
		// we ignore the error when we addsd a new router
		// becasue we may stored a nil routers, which is used in istio "RDS" mode
		routers, _ := NewRouters(routerConfig)
		rm.routersWrapperMap.Store(routerConfig.RouterConfigName, &RoutersWrapper{
			routers:       routers,
			routersConfig: routerConfig,
		})
```  


So, just ignore this error and use ``prefix_rewrite`` or `regex_rewrite` config?

**Comment by wangfakang** [comment]
@liangyuanpeng If both are configured, we can use `prefix_rewrite` by default first. 
In addition [host_rewrite](https://docs.google.com/spreadsheets/d/1fALompY9nKZNImOuxQw23xtMD-5rCBrXWziJZkj76bo/edit?usp=sharing) is not supported and you can also contribute if you are interested.

**Comment by liangyuanpeng** [comment]
@wangfakang 
Cool, I am interested in trying it out
