### ISSUE TITLE
istio-1.5.2 with mosn run examples-bookinfo CrashLoopBackOff

### ISSUE THREAD

**Issue by lehongwen** [mosn/mosn#1268]
### Describe the bug
istio-1.5.2 with mosn run examples-bookinfo CrashLoopBackOff

pod/reviews-v2、pod/reviews-v3、pod/reviews-v1，三个示例；
如果有两个部署在同一个主机节点上就会出现CrashLoopBackOff，不断的异常重启；另外一个是正常。

### Environment

使用https://katacoda.com/mosn/courses/istio/mosn-with-istio示例部署
[root@k8s252 ServiceMesh]# kubectl get node,svc,pod -n kube-system
NAME          STATUS   ROLES    AGE   VERSION
node/k8s100   Ready    <none>   47h   v1.18.1
node/k8s252   Ready    master   47h   v1.18.1

NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
service/kube-dns        ClusterIP   10.254.0.10     <none>        53/UDP,53/TCP,9153/TCP   47h
service/tiller-deploy   ClusterIP   10.254.173.11   <none>        44134/TCP                26h

NAME                                           READY   STATUS    RESTARTS   AGE
pod/calico-kube-controllers-555fc8cc5c-v2kzh   1/1     Running   0          47h
pod/calico-node-b5b5k                          1/1     Running   0          47h
pod/calico-node-m4b27                          1/1     Running   0          47h
pod/coredns-7ff77c879f-d949z                   1/1     Running   0          47h
pod/coredns-7ff77c879f-gzqvk                   1/1     Running   0          47h
pod/etcd-k8s252                                1/1     Running   0          47h
pod/kube-apiserver-k8s252                      1/1     Running   0          47h
pod/kube-controller-manager-k8s252             1/1     Running   0          47h
pod/kube-proxy-7rb6x                           1/1     Running   0          47h
pod/kube-proxy-ftv8k                           1/1     Running   0          47h
pod/kube-scheduler-k8s252                      1/1     Running   0          47h
pod/tiller-deploy-58cb4bf676-wj9sb             1/1     Running   0          26h
[root@k8s252 ServiceMesh]# 

使用如下命令来下载 istio：
export ISTIO_VERSION=1.5.2 && curl -L https://raw.githubusercontent.com/istio/istio/release-1.5/release/downloadIstioCandidate.sh | sh -

通过 istioctl 命令的参数指定 MOSN 作为 istio 中的数据面：
istioctl manifest apply --set .values.global.proxy.image="mosnio/proxyv2:1.5.2-mosn" --set meshConfig.defaultConfig.binaryPath="/usr/local/bin/mosn"

通过 kube-inject 的方式实现Sidecar注入： istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml > bookinfo.yaml && sed -i "s/\/usr\/local\/bin\/envoy/\/usr\/local\/bin\/mosn/g" ./bookinfo.yaml
部署注入 Sidecar 后的 Bookinfo 应用： kubectl apply -f bookinfo.yaml

[root@k8s252 ServiceMesh]# kubectl get svc,pod -o wide 
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                        AGE   SELECTOR
service/details                  ClusterIP   10.254.7.176     <none>        9080/TCP                       16m   app=details
service/kubernetes               ClusterIP   10.254.0.1       <none>        443/TCP                        47h   <none>
service/productpage              ClusterIP   10.254.141.197   <none>        9080/TCP                       16m   app=productpage
service/ratings                  ClusterIP   10.254.118.188   <none>        9080/TCP                       16m   app=ratings
service/reviews                  ClusterIP   10.254.198.79    <none>        9080/TCP                       16m   app=reviews
service/swift-swift              ClusterIP   10.254.64.64     <none>        9855/TCP,50055/TCP,56790/TCP   26h   app=swift,release=swift
service/unm-k8s-metrics-server   ClusterIP   10.254.182.125   <none>        443/TCP                        26h   app=metrics-server,release=unm-k8s

NAME                                         READY   STATUS             RESTARTS   AGE   IP             NODE     NOMINATED NODE   READINESS GATES
pod/details-v1-58876d78b8-hj4qb              2/2     Running            0          16m   172.20.29.24   k8s100   <none>           <none>
pod/productpage-v1-64474b44b5-jfkhd          2/2     Running            0          16m   172.20.42.53   k8s252   <none>           <none>
pod/ratings-v1-7bfc79c8d4-vbhqj              2/2     Running            0          16m   172.20.42.62   k8s252   <none>           <none>
pod/reviews-v1-6d8f6bbdfc-bjnss              2/2     Running            0          16m   172.20.29.25   k8s100   <none>           <none>
pod/reviews-v2-6cd4f98cd7-22jtg              1/2     CrashLoopBackOff   7          16m   172.20.42.59   k8s252   <none>           <none>
pod/reviews-v3-85b59666b5-d6b5z              1/2     CrashLoopBackOff   7          16m   172.20.42.61   k8s252   <none>           <none>
pod/swift-swift-567f9cb58f-6z7dl             1/1     Running            0          26h   172.20.42.18   k8s252   <none>           <none>
pod/unm-k8s-metrics-server-5f4556879-lvslr   1/1     Running            1          26h   172.20.29.8    k8s100   <none>           <none>
[root@k8s252 ServiceMesh]# 

- MOSN Version

**Comment by lehongwen** [comment]
[root@k8s252 ServiceMesh]# kubectl logs pod/reviews-v3-85b59666b5-d6b5z -c reviews

Unhandled exception
Type=Bus error vmState=0xffffffff
J9Generic_Signal_Number=00000028 Signal_Number=00000007 Error_Value=00000000 Signal_Code=00000002
Handler1=00007FB59A0E7810 Handler2=00007FB5999CC670 InaccessibleAddress=00000000FFF00000
RDI=00007FB5940B7950 RSI=0000000000000001 RAX=0000000000000001 RBX=0000000000000000
RCX=00000000FFF00000 RDX=0000000000100000 R8=0000000100000000 R9=0000000000000000
R10=00007FB59333AAD8 R11=00007FB5930717C0 R12=00000000FFF00000 R13=0000000100000000
R14=0000000000000000 R15=00007FB5940BCC20
RIP=00007FB59305E5B2 GS=0000 FS=0000 RSP=00007FB59B041C60
EFlags=0000000000010246 CS=0033 RBP=00007FB5940B7950 ERR=0000000000000006
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFF00000
xmm0 726f6d654d5f4d4d (f: 1298091392.000000, d: 1.676463e+243)
xmm1 6170536275537972 (f: 1968404864.000000, d: 2.295250e+161)
xmm2 3ff3333340000000 (f: 1073741824.000000, d: 1.200000e+00)
xmm3 7fefffffffffffff (f: 4294967296.000000, d: 1.797693e+308)
xmm4 405b800000000000 (f: 0.000000, d: 1.100000e+02)
xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm6 405b800000000000 (f: 0.000000, d: 1.100000e+02)
xmm7 41be908b3ead9fec (f: 1051566080.000000, d: 5.127893e+08)
xmm8 41a0000002000000 (f: 33554432.000000, d: 1.342177e+08)
xmm9 405b800000000000 (f: 0.000000, d: 1.100000e+02)
xmm10 3fe0000000000000 (f: 0.000000, d: 5.000000e-01)
xmm11 be65472eb0670fdb (f: 2959544320.000000, d: -3.963347e-08)
xmm12 3c4cd58858eb8000 (f: 1491828736.000000, d: 3.126201e-18)
xmm13 3d3fae0000000000 (f: 0.000000, d: 1.125489e-13)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9gc29.so
Module_base_address=00007FB592E6D000
Target=2_90_20191106_432135 (Linux 3.10.0-1062.el7.x86_64)
CPU=amd64 (8 logical CPUs) (0x3cb22c000 RAM)
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/07/15 05:27:05 - please wait.
JVMDUMP032I JVM requested System dump using '/opt/ibm/wlp/output/defaultServer/core.20200715.052705.1.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.40.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 40 was not found. Expected to find core file with name "/opt/ibm/wlp/output/defaultServer/core.40"
JVMDUMP032I JVM requested Java dump using '/opt/ibm/wlp/output/defaultServer/javacore.20200715.052705.1.0002.txt' in response to an event
JVMDUMP012E Error in Java dump: /opt/ibm/wlp/output/defaultServer/javacore.20200715.052705.1.0002.txt
JVMDUMP032I JVM requested Snap dump using '/opt/ibm/wlp/output/defaultServer/Snap.20200715.052705.1.0003.trc' in response to an event
JVMDUMP009I Snap dump not available
JVMDUMP013I Processed dump event "gpf", detail "".
[root@k8s252 ServiceMesh]#

**Comment by wangfakang** [comment]
> [root@k8s252 ServiceMesh]# kubectl logs pod/reviews-v3-85b59666b5-d6b5z -c reviews
> 
> Unhandled exception
> Type=Bus error vmState=0xffffffff
> J9Generic_Signal_Number=00000028 Signal_Number=00000007 Error_Value=00000000 Signal_Code=00000002
> Handler1=00007FB59A0E7810 Handler2=00007FB5999CC670 InaccessibleAddress=00000000FFF00000
> RDI=00007FB5940B7950 RSI=0000000000000001 RAX=0000000000000001 RBX=0000000000000000
> RCX=00000000FFF00000 RDX=0000000000100000 R8=0000000100000000 R9=0000000000000000
> R10=00007FB59333AAD8 R11=00007FB5930717C0 R12=00000000FFF00000 R13=0000000100000000
> R14=0000000000000000 R15=00007FB5940BCC20
> RIP=00007FB59305E5B2 GS=0000 FS=0000 RSP=00007FB59B041C60
> EFlags=0000000000010246 CS=0033 RBP=00007FB5940B7950 ERR=0000000000000006
> TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFF00000
> xmm0 726f6d654d5f4d4d (f: 1298091392.000000, d: 1.676463e+243)
> xmm1 6170536275537972 (f: 1968404864.000000, d: 2.295250e+161)
> xmm2 3ff3333340000000 (f: 1073741824.000000, d: 1.200000e+00)
> xmm3 7fefffffffffffff (f: 4294967296.000000, d: 1.797693e+308)
> xmm4 405b800000000000 (f: 0.000000, d: 1.100000e+02)
> xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
> xmm6 405b800000000000 (f: 0.000000, d: 1.100000e+02)
> xmm7 41be908b3ead9fec (f: 1051566080.000000, d: 5.127893e+08)
> xmm8 41a0000002000000 (f: 33554432.000000, d: 1.342177e+08)
> xmm9 405b800000000000 (f: 0.000000, d: 1.100000e+02)
> xmm10 3fe0000000000000 (f: 0.000000, d: 5.000000e-01)
> xmm11 be65472eb0670fdb (f: 2959544320.000000, d: -3.963347e-08)
> xmm12 3c4cd58858eb8000 (f: 1491828736.000000, d: 3.126201e-18)
> xmm13 3d3fae0000000000 (f: 0.000000, d: 1.125489e-13)
> xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
> xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
> Module=/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9gc29.so
> Module_base_address=00007FB592E6D000
> Target=2_90_20191106_432135 (Linux 3.10.0-1062.el7.x86_64)
> CPU=amd64 (8 logical CPUs) (0x3cb22c000 RAM)
> JVMDUMP039I Processing dump event "gpf", detail "" at 2020/07/15 05:27:05 - please wait.
> JVMDUMP032I JVM requested System dump using '/opt/ibm/wlp/output/defaultServer/core.20200715.052705.1.0001.dmp' in response to an event
> JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" specifies that the core dump is to be piped to an external program. Attempting to rename either core or core.40.
> 
> JVMDUMP012E Error in System dump: The core file created by child process with pid = 40 was not found. Expected to find core file with name "/opt/ibm/wlp/output/defaultServer/core.40"
> JVMDUMP032I JVM requested Java dump using '/opt/ibm/wlp/output/defaultServer/javacore.20200715.052705.1.0002.txt' in response to an event
> JVMDUMP012E Error in Java dump: /opt/ibm/wlp/output/defaultServer/javacore.20200715.052705.1.0002.txt
> JVMDUMP032I JVM requested Snap dump using '/opt/ibm/wlp/output/defaultServer/Snap.20200715.052705.1.0003.trc' in response to an event
> JVMDUMP009I Snap dump not available
> JVMDUMP013I Processed dump event "gpf", detail "".
> [root@k8s252 ServiceMesh]#

It seems that the [Reviews](https://github.com/istio/istio/tree/1.5.2/samples/bookinfo/src/reviews) Java service throws exceptions, but the root reasons for exceptions cannot be cleared from the logs.
