### ISSUE TITLE
package `mosn.io/mosn/pkg/shm`  `TestAtomic` uint test 

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#1342]
### Describe the bug

https://github.com/mosn/mosn/blob/master/pkg/shm/shm_test.go#L54

in my macbookpro `runtime.NumCPU()` is 12, so the variable of expected  cann't be divided by `runtime.NumCPU()`.

### Minimal yet complete reproducer code (or GitHub URL to code)

```golang
for i := 0; i < cpu; i++ {
		go func() {
			for j := 0; j < expected/cpu; j++ { // bug in expected/cpu
				atomic.AddUint32(counter, 1)
			}
			wg.Done()
		}()
	}
```

### Environment

macbookpro 16寸

- MOSN Version

latest version of master branch

if menbers accept this bug, i will fix it later.

**Comment by wangfakang** [comment]
@alpha-baby Thank you for your report, welcome to contribute PR.
