### ISSUE TITLE
Support variable for Route Match

### ISSUE THREAD

**Issue by taoyuanyuan** [mosn/mosn#1377]
### The New Feature

Describe the new feature you want to support clearly.

### Your scenes

Describe your use scenes (why need this feature).

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by taoyuanyuan** [comment]
@CodingSinger

**Comment by taoyuanyuan** [comment]
目前MOSN有一堆自己的内部变量，用于路由匹配，目前是在请求处理前塞到用户的header，在请求发送前在删掉，如injectInternalHeaders函数和 removeInternalHeaders
函数，主要是为了让路由使用，这儿就存在几个问题：
1. 我们修改了用户的header，作为我们的数据中转，这个是不合理的。
2. 影响性能，每次请求都要插入然后删除，然后为了重试逻辑，也需要每次拷贝一个header

目前mosn已经支持了变量机制，可以把这些值保存到ctx里面，跟着整个stream的请求周期，然后修改route的获取源，之前是从header，修改为从ctx的变量机制

**Comment by taoyuanyuan** [comment]
#1418

**Comment by CodingSinger** [comment]
### 背景描述：

目前为了在MOSN内部传递一些请求或者响应的变量,例如mosn-header-status，都是通过操作用户的headers,把一些请求相关的信息存储到headers这个key-value结构中，并且在header发出去之前把这些信息删除。

这种做法存在很多问题，代码上不优雅，操作用户的headers容易出现问题。并且频繁的拷贝和Del也会有性能影响。



### 改进目标：

1. 尽量不修改通过请求解析出来的headers，除非feature本身允许用户按自己的意愿修改headers。例如`header_parser.go`中的方法。
2. 原先存储在headers中的MOSN内置变量，都存储在context中。主要是`pkg/types/constant.go`和`pkg/protocol/types.go`的以"x-mosn"开头的变量。



### 改进方案：

通过变量机制，把之前存储在header中的数据存储到每个请求的ctx中。什么是变量机制，可以看官方文档的介绍。https://mosn.io/blog/code/mosn-variable/

`ServerStreamConnection`在接受请求时，会解析请求数据和请求headers，并且将原先通过`headers.Set`的地方都修改为`variable.SetVariableValue`。例如“x-mosn-host"、"x-mosn-path"等，MOSN在接受到请求时从Header中提取请求的Path、Service等信息并注入到为该请求分配的独占context对象中。并且在之后的请求处理流程中都通过ctx做到随用随取。例如路由、path rewrite等流程。



除此之外，在有了变量机制之后，我们也可以根据context的内置变量来做路由。新增`VariableRouteRuleImpl`类，该路由支持多种变量匹配项的组合。基本配置结构如下：

```
type VariableMatchItem struct {
	name         string // 变量名
	value        *string // 变量精确匹配值
	regexPattern *regexp.Regexp // 正则匹配表达式
	model        Model // 连接下一个匹配项的模式，目前有and和or两种
}
```

组合形式以下面代码配置为例：

```
RouterConfig: v2.RouterConfig{
			Match: v2.RouterMatch{
				Variables: []v2.VariableMatcher{
					{
						Name:  "header",
						Value: "test",
						Model: "or",
					},
					{
						Name:  "method",
						Value: "test",
						Model: "and",
					},
					{
						Name:  "uri",
						Regex: "/[0-9]+",
						Model: "or",
					},
					{
						Name:  "uri",
						Value: "/1234",
					},
				},
			},
			Route: v2.RouteAction{
				RouterActionConfig: v2.RouterActionConfig{
					ClusterName: "test",
				},
			},
		},
```

每个匹配项的Model用来连接之后的匹配项，最后一个匹配项的mode可以不配。从上到下连接，其表示满足只要请求的内置变量满足`header == test || (method == test && regex(/[0-9]+).MatchString(uri)) || uri == /1234`则走该路由。

**Comment by taoyuanyuan** [comment]
thx
