### ISSUE TITLE
Does mson support istio 1.6.x? 

### ISSUE THREAD

**Issue by tanjunchen** [mosn/mosn#1398]
### Your question

Describe your question clearly.

Does mson support istio 1.6.x? 

Is there a corresponding relationship diagram between mosn version and istio?

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by tanjunchen** [comment]
I see it from https://mosn.io/docs/community/, from 
![image](https://user-images.githubusercontent.com/19339970/95541195-55885d80-0a25-11eb-9e74-742a0d77c97c.png), it seems that we can support 1.7.x  now , really?

**Comment by wangfakang** [comment]
@tanjunchen Currently we are adapting 1.6.x on the branch of `feature-istio_adapter`  https://github.com/mosn/mosn/pull/1183, we may skip 1.7.x, because istio 1.8.x will only accepts xDS v3 API https://github.com/istio/istio/issues/19885#issuecomment-614109648.

**Comment by tanjunchen** [comment]
@wangfakang  Thanks for your reply. I get it .
