### ISSUE TITLE
filterManager InitializeReadFilters()

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#1470]
### Describe the bug

在这里会初始化一下filtermanager：https://github.com/mosn/mosn/blob/master/pkg/server/handler.go#L482

感觉这个初始化函数里面也没干什么重要的东西，`func (fm *filterManager) onContinueReading(filter *activeReadFilter)`这个函数中会去获取 rawconnection 中的buffer ，但是 rawconnection 在这里才开启读取数据：https://github.com/mosn/mosn/blob/master/pkg/server/handler.go#L508，所以感觉https://github.com/mosn/mosn/blob/master/pkg/server/handler.go#L482这个有点多余一样，但是我不确定是不是我有什么隐藏的东西我没有理解到

### Environment

- MOSN Version

latest

**Comment by cch123** [comment]
onContinueReading 主要干两件事

- 把没初始化的 filter 初始化，并调用 OnNewConnection

- 如果连接收到了数据，那么依次执行 readfilter

OnNewConnection 中，如果本地向 mosn 建了连接，那 mosn 会在 proxy 的：

```
func (p *proxy) OnNewConnection() api.FilterStatus {
	if log.DefaultLogger.GetLogLevel() >= log.DEBUG {
		log.DefaultLogger.Debugf("[%s proxy] [new conn] accept new connection", p.network)
	}
	return p.initializeUpstreamConnection()
}
```

和远端进行预建连。

理论上你把上面那个删掉也行，只不过这样会变成收到数据才去建连

这里写的确实不好懂，有什么好想法可以改得更好懂欢迎 PR
