### ISSUE TITLE
pkg/stream/http Dispatch error

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#1473]
### Describe the bug

https://github.com/mosn/mosn/blob/master/pkg/stream/http/stream.go#L142

This function of `Dispatch` is called in a short time. Data will be lost.

I don't know if I'm right in my analysis, I hope you can recheck.

### Environment

- MOSN Version

lastest version in master branch

**Comment by cch123** [comment]
这里写的比较 trick, 
channel 是一个阻塞 channel，
如果发送成功了，那说明一定是被其它协程读走了

更好的写法应该把通知和数据发送分开，你有想法欢迎 pr 呀

**Comment by alpha-baby** [comment]
@cch123

**Comment by alpha-baby** [comment]
@cch123 
我的意思是 如果函数整阻塞在这里：https://github.com/mosn/mosn/blob/master/pkg/stream/http/stream.go#L143

但是后面的函数还没有执行完这里：https://github.com/mosn/mosn/blob/master/pkg/stream/http/stream.go#L184

然后又瞬间`Dispatch`函数又被调用，然后新请求过来的buf，就会被上面第一处阻塞的地方把buf读走了，然后数据就丢失了

**Comment by taoyuanyuan** [comment]
@alpha-baby  Dispatch 不是已经阻塞在 https://github.com/mosn/mosn/blob/master/pkg/stream/http/stream.go#L143 吗，怎么还会有瞬间的 Dispatch 调用？

**Comment by alpha-baby** [comment]
> @alpha-baby Dispatch 不是已经阻塞在 https://github.com/mosn/mosn/blob/master/pkg/stream/http/stream.go#L143 吗，怎么还会有瞬间的 Dispatch 调用？

确实是你说的这样的，我可能当时没理解，感谢

**Comment by champly** [comment]
这本身就是一个阻塞的channel，上面 `Dispatch` 负责放 `buffer`，下面的 `Read` 负责读取，拷贝，然后再等待下一次 `Read` 调用，就算是多个 `Dispatch`, 也是会阻塞在那里的

**Comment by alpha-baby** [comment]
@champly 如果是多个 `Dispatch`那么，`Dispatch`中的for循环会自旋起来，如果自旋起来了会造成数据顺序乱掉
可以看PR https://github.com/mosn/mosn/pull/1475

**Comment by champly** [comment]
> @champly 如果是多个 `Dispatch`那么，`Dispatch`中的for循环会自旋起来，如果自旋起来了会造成数据顺序乱掉
> 可以看PR #1475

是的，如果是多个会出现自己消费了自己的情况
