### ISSUE TITLE
not exists if a key with an empty value in api.HeaderMap

### ISSUE THREAD

**Issue by GLYASAI** [mosn/mosn#1518]
### Describe the bug

A key with an empty value set to api.HeaderMap. But header.Get(key) thinks that the key does not exist. 

```
header := http.RequestHeader{
	RequestHeader: &fasthttp.RequestHeader{},
}
header.Set("foobar", "")
_, exists := header.Get("foobar")
```
 Expected exists to be true, but got false.

**Comment by ianwoolf** [comment]
the method of `mosn/pkg/protocol/http`.`RequestHeader` has no pointer reciever, and its method `Set` has a problem.  i'm working on it

**Comment by nejisama** [comment]
fixed

**Comment by wangfakang** [comment]
TODO 
upgrade fasthttp:
https://github.com/valyala/fasthttp/commit/4e63057c0fd0ebcc9040c161ad69c7e56d57cf82
