### ISSUE TITLE
如何按请求中的header字段实现自定义的寻址

### ISSUE THREAD

**Issue by morefreeze** [mosn/mosn#1548]
### Your question
假如header字段service记录了要服务发现的名字，我会用service的值去向一个发现服务（一个http请求）请求endpoint，对于这种动态host的怎么实现比较好呢？

我的想法是每个service是一个cluster，我实现一种clusterType是前面讲的找endpoint的方式，然后clusterManager.GetClusterSnapshot时判断下，不存在则新建这个Cluster完成寻址，这样吗？

举个例子，发一个请求curl example.com/foo/bar -H'service: svr1'，然后会请求服务发现curl 127.0.0.1:2280/lookup?name=svr1 得到一些endpoint，比如有1.2.3.4:5678，将请求替换成1.2.3.4:5678/foo/bar -H'domain:example.com'发出，但这个svr1 不是预先知道的，可以是任意值
### Environment

- MOSN Version
0.4.0
### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
你可以写一个streamfilter，然后插header来指定目标ip
https://github.com/mosn/mosn/pull/1005

**Comment by morefreeze** [comment]
> 你可以写一个streamfilter，然后插header来指定目标ip
> #1005

是不是有点误解，传进来 的header是指定过的，然后要根据这个header来选ip

**Comment by morefreeze** [comment]
我看streamfilter是可以读到header的，但它的onRecevice是返回是否继续的

**Comment by taoyuanyuan** [comment]
嗯 你看我发的链接的第二个例子，可以设置一个header，通过header的value作为目标ip转发，这个header你自己设置

**Comment by taoyuanyuan** [comment]
],
  "cluster_manager":{     
     "clusters":[
        {
          "Name":"PassthroughCluster",
          "type": "SIMPLE",
          "lb_type": "LB_ORIGINAL_DST",
          "max_request_per_conn": 1024,
          "conn_buffer_limit_bytes":32768,
          "original_dst_lb_config": {
             "use_http_header": true,
             "header_name": "host"
          } 
        }
     ]
  }
}
-——————————————

use_http_header

**Comment by morefreeze** [comment]
> ],
>   "cluster_manager":{     
>      "clusters":[
>         {
>           "Name":"PassthroughCluster",
>           "type": "SIMPLE",
>           "lb_type": "LB_ORIGINAL_DST",
>           "max_request_per_conn": 1024,
>           "conn_buffer_limit_bytes":32768,
>           "original_dst_lb_config": {
>              "use_http_header": true,
>              "header_name": "host"
>           } 
>         }
>      ]
>   }
> }
> -——————————————
> 
> use_http_header
> header_name 随意设置，你在streamfilter里把ip插这个header头

多谢！ 是想要的 明天我试下然后再resolve

**Comment by greedying** [comment]
你好。original_dst_lb_config.header_name 解决了转发到自定义 ip 的问题。
如果我需要转发到不同的路径，有办法解决么？
比如 我需要把 `/a/b` 转发到 `1.2.3.4/c/d` 去。
其中 `/a/b` 和 `1.2.3.4/c/d` 的对应关系是动态的，比如对应关系是存储在数据库中的。

@taoyuanyuan
