### ISSUE TITLE
About x-mosn-path header

### ISSUE THREAD

**Issue by ab91963931372** [mosn/mosn#1555]
### Your question

为什么这个header在http流量的场景下用的是fasthttp的uri.Path()而不是uri.PathOriginal()
pkg/stream/http/stream.go#injectInternalHeaders()
![image](https://user-images.githubusercontent.com/21658981/105569083-9492b280-5d79-11eb-9fe1-a496a117e740.png)
之所以这么问是因为从定义上来说：
Path():
![image](https://user-images.githubusercontent.com/21658981/105569056-64e3aa80-5d79-11eb-9c6f-d4522236b4fb.png)
PathOriginal():
![image](https://user-images.githubusercontent.com/21658981/105569065-74fb8a00-5d79-11eb-9535-459a44ec1277.png)
如果想要的是http原本的requestURI的话，应该是下面的，因为上面那种的话会导致向upstream发请求的时候uri编码丢失：
![image](https://user-images.githubusercontent.com/21658981/105569095-b0965400-5d79-11eb-9312-0aa545c90d15.png)
这样会导致400 Bad request

### Environment

- v20

### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
确实有问题

**Comment by antJack** [comment]
fix: https://github.com/mosn/mosn/pull/1558
解决方案：向 upstream 发请求时对 path 进行编码转义，确保发出去的 uri 是合法的(例如空格会被转换成%20)；injectInternalHeaders() 处保留 uri.Path() 调用，以避免对上层用户造成影响。
