### ISSUE TITLE
How to build custom mosnio/proxyv2 image?

### ISSUE THREAD

**Issue by xieziqiang** [mosn/mosn#1583]
### Your question

How to build mosnio/proxyv2 image?

fllow https://github.com/istio/istio/pull/25146，I use the following command to build：
`
ISTIO_ENVOY_VERSION=v0.13.0 ISTIO_ENVOY_RELEASE_URL=https://github.com/GLYASAI/mosn/releases/download/0.13.0/mosn.tgz ISTIO_ENVOY_MACOS_RELEASE_URL=https://github.com/GLYASAI/mosn/releases/download/0.13.0/mosn-macos.tar.gz ISTIO_ENVOY_MACOS_RELEASE_NAME=mosn-0.13.0 SIDECAR=mosn make docker.proxyv2
`
But it can't be build successfully，the error logs is:
`
Downloading WebAssembly file: https://storage.googleapis.com/istio-build/proxy/stats-v0.13.0.wasm to /work/out/linux_amd64/release/stats-v0.13.0.wasm
curl: (22) The requested URL returned error: 404 

real    0m0.313s
user    0m0.020s
sys     0m0.008s
Makefile.core.mk:224: recipe for target '/work/out/linux_amd64/istio_is_init' failed
make[1]: *** [/work/out/linux_amd64/istio_is_init] Error 1
Makefile:46: recipe for target 'docker.proxyv2' failed
make: *** [docker.proxyv2] Error 2
`
It looks like still to download WebAssembly when sidecar is mosn.

Can anyone tell me how to build mosnio/proxyv2 image?  tks

### Environment

- MOSN Version 

### Logs

- Paste the logs you see.

**Comment by wangfakang** [comment]
@xieziqiang I have added a [document](https://github.com/mosn/mosn.io/pull/131/files) about build proxyv2 image,you can try it. thx.

**Comment by xieziqiang** [comment]
okay, thank you. I have build it successfully. I download wasm first, and then it was built successfully. I'll try your document next time.
