### ISSUE TITLE
[Proposal] Mosn to evolve to an application runtime

### ISSUE THREAD

**Issue by nobodyiam** [mosn/mosn#1591]
## Background

Mosn is a great service proxy and is used in production by many companies, which works well to solve many companys' service connectivity challenges.

Yet, in real world cases, a typical company may face much more challenges in areas like cache, database, message queue, configuration management, etc. Which means we still need to maintain a set of heavy weight SDKs along with the application code.

## Proposal

While the open source version of MOSN remains as a pure **_service_** proxy, the actual usage in Ant Group has evolved a lot and has proxied more capabilities such as message queue, redis, etc. The reason why these capabilities were not ported back to open source community is because there was no clear abstraction layer and these capability implementations were tightly coupled with the actual backend services(port, protocol, etc), which is not suitable for open source users.

**Current architecture:**
![20210219201433](https://user-images.githubusercontent.com/837658/108503355-3234bf80-72ef-11eb-9546-a3642b489bd1.jpg)

However, with the release of [dapr 1.0.0](https://github.com/dapr/dapr/releases/tag/v1.0.0), we see another possiblity: we can define an abstraction layer and the sidecar becomes an application runtime which implements the abstraction layer, so that the application code could safely program against one set of standard api and forget about the actual backend services.

**Proposed new architecture:**
![20210219202141](https://user-images.githubusercontent.com/837658/108503939-23024180-72f0-11eb-9d18-4387d38be5a0.jpg)

## Benefits

With this new architecture, there are several advantages:
1. Multi-language friendly
    * Since the api is standardized, it's very easy to implement the thin sdk in multi-languages
    * If we choose the protocol right (e.g. http/http2), there may be no need to implement the sdk at all since the application could access MOSN with the protocol directly
2. No vendor lock-in
    * Since the api is standardized, users have no concern in choosing MOSN, as it could be safely replaced by any sidecar/process which implements the same api
3. Write once, Run anywhere
    * Since MOSN abstracts away the backend service details, we could safely deploy one codebase to different environments(e.g. hybrid cloud/multiple cloud), no matter what the actual backend services are

![20210219203824](https://user-images.githubusercontent.com/837658/108505504-77a6bc00-72f2-11eb-8c65-c325bc49e1e7.jpg)

----------------

## 背景

MOSN 是一个非常不错的服务代理，已经用于不少公司的生产环境中，解决了许多公司在微服务服务方面遇到的挑战。

然而，在现实场景中，一个典型的公司不止会面临微服务方面的挑战，往往还会在缓存、数据库、消息队列、配置管理等领域面临更多难题，这就意味着我们事实上仍然需要维护一套重量级的 SDK 并且嵌在应用代码中。

## 提议

尽管 MOSN 的开源版本仍然定位为比较纯粹的 **_服务_** 代理，但是蚂蚁集团的实际用法已经向前演进了许多，比如除了代理服务流量外，还代理了消息队列，redis 等。没有把这些功能贡献回开源社区的主要原因是中间缺少了一个清晰的抽象层，导致这些功能的实现与实际的后端服务（端口，协议等）耦合过紧，并不适合开源用户。

**当前架构：**
![20210219201433](https://user-images.githubusercontent.com/837658/108503355-3234bf80-72ef-11eb-9546-a3642b489bd1.jpg)

不过，随着[dapr 1.0.0](https://github.com/dapr/dapr/releases/tag/v1.0.0)的发布，我们看到了另一种可能性：我们其实可以定义一个 api 抽象层，并且由 MOSN 来实现这套 api，从而在我们的应用程序中可以只针对这套标准的 api 编程，而无需考虑实际运行时的后端服务形态。

**提议的新架构：**
![20210219202141](https://user-images.githubusercontent.com/837658/108503939-23024180-72f0-11eb-9d18-4387d38be5a0.jpg)

## 收益

使用这种新架构，有以下几个优点：
1. 多语言友好
     * 由于 api 是标准化的，所以很容易在各种语言中实现一套 thin SDK 来适配
     * 如果我们选择了一套通用协议（例如http/http2），那么在很多情况下可能根本不需要去提供 thin sdk，因为应用程序可以直接通过标准协议来访问 MOSN
2. 没有厂商绑定
     * 由于 api 是标准化的，所以用户在选择 MOSN 时不会有任何顾虑，因为可以非常方便地替换为其它实现了相同 api 的任何sidecar 或外部进程
3. 真正实现 Write once, Run anywhere
     * 由于 MOSN 把后端服务的实现都抽象掉了，所以我们可以实现一套代码在不同的环境中运行（例如，混合云/多云）而无需为每套环境做适配

![20210219203824](https://user-images.githubusercontent.com/837658/108505504-77a6bc00-72f2-11eb-8c65-c325bc49e1e7.jpg)

**Comment by 1725636955** [comment]
666

**Comment by fdingiit** [comment]
> 不过，随着dapr 1.0.0的发布，我们看到了另一种可能性：我们其实可以定义一个 api 抽象层，并且由 MOSN 来实现这套 api，从而在我们的应用程序中可以只针对这套标准的 api 编程，而无需考虑实际运行时的后端服务形态。

请教下齐老板：

简单的看了一下dapr demo和源码，主要关注了存储这一块。对于有状态存储来说，dapr定义了一套接口，这个接口只开放了set/get/delete三个方法。
```go
type Store interface {
	BulkStore
	Init(metadata Metadata) error
	Delete(req *DeleteRequest) error
	Get(req *GetRequest) (*GetResponse, error)
	Set(req *SetRequest) error
}
```
而市面上存在redis/mongo/zk/es等各种各样存储产品的原因之一，是需要在不同业务场景使用不同的高级功能，比如自动过期淘汰、链表、有序集合、全文搜索、临时数据等，`Store`接口基本上不会满足业务需求。

所以dapr的提供了一个扩展不同存储后端的框架，但这个框架内的功能极度有限（毕竟需要保证所有对接的后端存储产品都需要能够实现接口里定义的方法）；如果只用api提供的功能，几乎什么都做不了；如果基于他二次开发，就相当于需要把目标后端存储产品的客户端sdk，迁移到dapr上并提供一套http/gRPC接口，其所引入的工作量的价值是不是得具体分析了？

**Comment by nobodyiam** [comment]
@fdingiit 

我是这么理解这个问题的：
1. 有些特性是后端服务自己带来的，比如 zk 的强一致，这些不需要体现在 api 上，用户可以通过替换后端服务来获得所需要的能力
2. 有些特性是需要在 api 上体现的，比如存储的数据是否是 ephemeral 的，这些可以作为 api 的接口字段或者是扩展的 attributes 字段来体现。不过对接不同的后端服务，确实会有不同的实现方式，那作为 api 设计方，我们就需要考虑 ephemeral 是否对于状态存储是一个通用的 feature，如果是的话，那就需要针对不同的后端服务提供不同的实现，如果不是的话，那就要么 api 上不体现这个能力，要么就作为一个 hint，表示由实际的后端服务尽力而为。
3. 一旦涉及抽象，肯定会对个性化带来一定的影响，这个和咱们在程序中设计 API 其实是一个道理。如果 API 太过抽象，那么这个 API 势必不好用，但如果太过具象，那这个 API 势必会不稳定，所以其中还是需要有个平衡在的。

**Comment by CodingSinger** [comment]
所以我理解这套API的定义是必须谨慎重要的，后续是和dapr一起推进，维护一份规范，还是MOSN完全自己搞？

**Comment by nobodyiam** [comment]
@CodingSinger 我们倾向于业界一起共建出一套标准的 API Specification，目前还在和 dapr、envoy 等社区沟通

**Comment by alpha-baby** [comment]
> @CodingSinger 我们倾向于业界一起共建出一套标准的 API Specification，目前还在和 dapr、envoy 等社区沟通

个人认为这种App Runtime的发展潜力还是不错的我也觉得，共建API非常重要

**Comment by alpha-baby** [comment]
> @CodingSinger 我们倾向于业界一起共建出一套标准的 API Specification，目前还在和 dapr、envoy 等社区沟通

个人认为这种App Runtime的发展潜力还是很不错的
我也觉得，共建API非常重要，如果公用一个APi那么用户就可以随意更换sidecar了。

**Comment by nobodyiam** [comment]
[Layotto](https://github.com/mosn/layotto) is the answer to this issue! 🚀
