### ISSUE TITLE
实现一个记录request header 并打印到resp header的功能

### ISSUE THREAD

**Issue by morefreeze** [mosn/mosn#1598]
### Your question
hi，我又来提问啦，有一个需求，当header里有x-debug:1时，我们想把一路上的request header都保留，在resp时增加打印出来。

原本做法是实现一个stream filter，在OnReceive时保存headers到成员，在Append时把保留的headers和传入的headers做下merge，但有个问题是，前面的filter也会加自己的header，这个filter需要放在最后确保拿到的header是全的，中间有filter直接判断提前退出，用了StreamFilterStop就不会到这个filter，现在想让这个filter总是被调用到且最后调用到

### Environment

不重要

### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
在append的时候直接调用 GetRequestHeaders()  呢？

**Comment by morefreeze** [comment]
多谢！居然这么简单
