### ISSUE TITLE
mosn云边互联能力支持

### ISSUE THREAD

**Issue by CodingSinger** [mosn/mosn#1600]
## mosn云边互联

在边缘计算场景中，边缘节点常位于本地专有网络中，这虽然保证了边缘节点的安全，但云端的节点无法主动访问边缘节点，常用解法是在云端和边缘节点之间建立方向通道。

![image-20210425205630629](https://raw.githubusercontent.com/CodingSinger/res/master/uPic/image-20210425205630629.png)

云端节点部署MOSN作为Server进行转发请求到边缘节点（后文统称为server），边缘端部署MOSN Client作为agent，后文统称为agent。

### 基本流程

1. agent在启动时主动连接远端的server。
2. server listener接受到连接时，将该连接加入到对应cluster。
3. 云侧请求统一经过server出口，根据对应cluster拿到反向连接，进行转发数据。

### 细节

agent启动时扫描静态配置文件中所有cluster文件，如果有标志需要反向通道的cluster，则立即主动建立连接而非懒加载模式。增加`ConnectAtStartup`字段表示加载cluster时即创建对应的连接。

```
type Cluster struct {
  ...
	ConnectAtStartup bool 
}
```

server侧通过配置不同的listener来接受agent连接和云端fontend的连接，

接受到agent连接时，通过`ReadFilter`的`OnNewConnection`方法将连接加入到对应的cluster中的连接池map中。

需要`ClusterManager`开个接口支持该特性。

```
AddConnectionForCluster(clusterName string, conn StreamSender)
```

除此之外，agent可能属于不同upstream cluster，如何将agent连接绑定到对应的cluster的连接池，需要从4层的连接信息获取对应的clusterName。

类似于streamproxy：通过filter配置中的clustername字段或者StreamRouter即可以根据connection的address信息匹配拿到cluster。

### 其他

1. 当upstream agent侧的连接未主动连接时，server接受的请求返回`NoRouteFound`错误。
2. 当server有多个时，agent需要与所有server建立连接。

**Comment by taoyuanyuan** [comment]
agent启动时扫描静态配置文件中所有cluster文件，如果有标志需要反向通道的cluster
-------------------
这个不对哟  agent的cluster是他访问backend

**Comment by CodingSinger** [comment]
改进版本：

ExtendConfig中定义TunnelAgentConfig，该配置会在agent侧mosn建立连接时

```
type TunnelAgentConfig struct {
  // 建立连接数
	ConnectionNum int64  `json:"connection_num"`
	// 对应cluster的name
	Cluster       string `json:"cluster"`
	// 处理listener name
	HostingListener string `json:"hosting_listener"`
	// Server侧的直连列表
	ServerList   []string `json:"server_list"`
	...
}
```





1. agent侧通过ExtendConfig配置来进行启动和server侧的交互协程。主动连接公有云侧的server，并通过简单交互协议告诉server本连接的信息，协议格式如下：![image-20210406165911515](https://raw.githubusercontent.com/CodingSinger/res/master/uPic/image-20210406165911515.png)

   

   主要包括：

   * 协议魔数：2字节，0x20 0x88

   * 协议版本：1字节

   * 交互类型：1字节，目前主要是初始化连接

   * 数据长度：两字节 Json数据 包括clusterName、weight等host信息。

2. 公云侧的MOSN Server接受到连接时，通过解析连接内容，将该host以及对应的tcp连接直接加入到server侧的clusterManager。

3. server接收到downstream的连接时，走正常的路由逻辑，并将请求经由直接转发到agent侧，agent侧接受到请求之后转到对应的listener做处理。

**Comment by alpha-baby** [comment]
PR 里面是不是提供一个example，以上里就看代码都看不太懂
