### ISSUE TITLE
case sensitive in jwtauthn match prefix

### ISSUE THREAD

**Issue by Ruil1n** [mosn/mosn#1633]
### Describe the bug

When using [JWT authorization](https://github.com/mosn/mosn/tree/master/examples/en_readme/filter/jwtauthn), it is case-sensitive to the prefix that the URL matches, which can lead to authentication bypassing in some scenarios.

It is recommended to apply URL normalization and employ case-insensitive comparison in order to eliminate the risk of potential access control list bypasses.

### Expected behavior

Be intercepted by jwtauthn

### Actual behavior

Bypass the intercept

### Steps to reproduce 

config.js

```
......
"rules": [
             {
                     "match": {
                     "prefix": "/index"
             },
......
```

NodeJS with Express

```
curl http://127.0.0.1:2046/index -s -o /dev/null  -H "Authorization: Bearer token" -w "%{http_code}\n" 
401
```

```
curl http://127.0.0.1:2046/indeX -s -o /dev/null  -H "Authorization: Bearer token" -w "%{http_code}\n"
200
```

### Environment

- MOSN Version

**Comment by antJack** [comment]
According to [RFC3986](https://tools.ietf.org/html/rfc3986#section-6.2.2.1), only the host, sheme, and hexadecimal digits should be case-insensitive. The other generic syntax  components are assumed to be case-sensitive.

So, by default, the prefix "/index" should not match with "/indeX"

**Comment by Ruil1n** [comment]
Yes, that's true for RFC3986, but the conventions generally use all lowercase paths.

As MOSN is a general network proxy, I think its function of authenticating the matching path needs to support the differences of most applications to the greatest extent. 

Personally, I suggest that case-insensitive matching be enabled by default, and users can configure it by themselves.

If the default is case-sensitive, it is best to remind users of possible risks.

**Comment by antJack** [comment]
Is there any documentation about your mentioned _conventions_?

I referred to the Envoy JWT Authentication module, but found that its [match](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-msg-route-routematch) is also case-sensitive. Or am I wrong with some places?

**Comment by antJack** [comment]
And we do need to provide the ability to configure whether case-sensitive or not by users.

That's what @GLYASAI is doing right now in https://github.com/mosn/mosn/pull/1637

**Comment by Ruil1n** [comment]
There may not be an explicit rule on this, I see in dapr 

https://github.com/dapr/dapr/pull/2768 https://github.com/yaron2/dapr/blob/c8d6d14e9430afc13a499111c40cdc363f78d5bf/pkg/config/configuration.go#L547 

They appear to be case insensitive after a security audit.

But I think it's better to be consistent with the RFC and Envoy as you do.

**Comment by Ruil1n** [comment]
There may not be an explicit rule on this,
But I think it's better to be consistent with the RFC and Envoy as you do.
