### ISSUE TITLE
[Feature] Add version api for adminApi

### ISSUE THREAD

**Issue by taoyuanyuan** [mosn/mosn#1647]
### The New Feature

Describe the new feature you want to support clearly.

### Your scenes

Describe your use scenes (why need this feature).

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by doujiang24** [comment]
add `/api/v1/version` in the admin API to show the version of the current running mosn.

here maybe a good choice.
![image](https://user-images.githubusercontent.com/570391/162551886-c94aef27-8ead-4ddd-bd5f-1084d28e2145.png)

**Comment by doujiang24** [comment]
already implemented in #2002
