### ISSUE TITLE
protocol-auto模式下 dubbo stream filter适配

### ISSUE THREAD

**Issue by Thiswang** [mosn/mosn#1667]
### The New Feature

protocol-auto模式下，如果存在dubbo协议流量需要配置dubbo stream filter做serviceEntry路由。
这时其他流量会出现may be the protocol is not dubbo异常

### Your scenes

protocol-auto模式下存在dubbo协议流量

### Your advice

修改dubbo stream filter报错逻辑为跳过

### Environment

- v0.23.0

**Comment by taoyuanyuan** [comment]
welcome pr

**Comment by champly** [comment]
You have already used `dubbo_stream` filter, means you wish this `listener` deal with `dubbo` request. Unless you use another `listener` deal with `dubbo` request.
