### ISSUE TITLE
[Feature] MOSN support holmes

### ISSUE THREAD

**Issue by taoyuanyuan** [mosn/mosn#1683]
### The New Feature

support https://github.com/mosn/holmes

### Your scenes

Describe your use scenes (why need this feature).

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by taoyuanyuan** [comment]
> With our [branch](https://github.com/symcn/mosn/blob/a55c73de826060b47566660bda39afb58f99f8cd/pkg/featuregate/mosn_features.go#L40) already support this feature.
hahaha， PR welcome ！

**Comment by taoyuanyuan** [comment]
#1978

**Comment by doujiang24** [comment]
https://github.com/mosn/mosn/pull/1978 is merged, closing.
