### ISSUE TITLE
[Feature] cluster name support variable for `RouterActionConfig`

### ISSUE THREAD

**Issue by wangfakang** [mosn/mosn#1687]
Add a `cluster_variable` for  [RouterActionConfig](https://github.com/mosn/mosn/blob/master/pkg/config/v2/route.go#L53) and determine the cluster to route to by reading the value of the variable named by `cluster_variable`. If the variable is not found or the referenced cluster does not exist, we could return a 404 response.

**Comment by nejisama** [comment]
这个方案似乎可以解决 #1685 下的问题2

**Comment by nejisama** [comment]
> 这个方案似乎可以解决 #1685 下的问题2

不同的需求

**Comment by taoyuanyuan** [comment]
#1705
