### ISSUE TITLE
[upstream WRRLB] if all hosts weight equal reuse rrLB

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#1721]
### Your question

https://github.com/mosn/mosn/blob/master/pkg/upstream/cluster/loadbalancer.go#L224

我觉得这里直接复用rrLB是一个比较好的处理方式，你们觉得呢？
i think reusing rrLB is a good choice，do you think so?

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
👍
