### ISSUE TITLE
about mosnio/proxyv2:layotto

### ISSUE THREAD

**Issue by rtttech** [mosn/mosn#1742]
There is a mosnio/proxyv2:layotto docker image  released a month ago on dockerhub, what features does this image have?

**Comment by nejisama** [comment]
@zhenjunMa @seeflood

**Comment by seeflood** [comment]
> There is a mosnio/proxyv2:layotto docker image released a month ago on dockerhub, what features does this image have?

This is used as a quickstart demo to show how layotto integrates with Istio,see https://mosn.io/layotto/#/en/start/istio/start
