### ISSUE TITLE
setting or clearing health flag may be insecure in concurrent calls

### ISSUE THREAD

**Issue by XIEZHENGYAO** [mosn/mosn#1748]
in file pkg/upstream/cluster/health.go L44-L46.
f loaded from p may be modified and stored by other routines, so storing new value to p may cause problems.

- MOSN Version v0.24.0

**Comment by nejisama** [comment]
Are there specific test cases or usage scenarios to reproduce the problem?

**Comment by XIEZHENGYAO** [comment]
The problem is not discovered at runtime,  I just noticed that codes might occur unexpected problems when concurrent calling.
