### ISSUE TITLE
[BUG] Request hangs if the upstream connection closes at the first time and then it does retry.

### ISSUE THREAD

**Issue by XIEZHENGYAO** [mosn/mosn#1751]
### Describe the bug

本地启动了两个端口，分别监听http2和http1端口，配置cluster的两个实例分别对应到这两个端口。mosn转发的端口配置HTTP2协议，开启http2_use_stream配置，期望请求在转发到http1实例失败后成功重试并得到http2端口的响应。

但实际测试时，请求hang住了。我加上日志打点后，发现第一次http2的请求到http1端口后，upstream关闭了连接，然后触发了异步协程写data时的报错，然后 `HandleError` `pkg/module/http2/mhttp2.go L1296` 这个函数会关闭downstream的SendData，再次重试时，SendData在 `pkg/module/http2/mhttp2.go L1140` 读取时失败，goroutine退出，因为第一次的http2 server没有关闭connection，导致waitNotify的请求协程一直等待，直到超时退出。

总结，一共两个问题：

1. 请求失败后直接关闭SendData是否应该？
2. 异步协程退出后是否需要有相应机制保证请求的协程能收到事件？

**Comment by taoyuanyuan** [comment]
麻烦发一下配置文件

**Comment by taoyuanyuan** [comment]
把h2_use_stream关了在试试看，一般来说用流式就不能支持重试了

**Comment by XIEZHENGYAO** [comment]
http2_use_stream在遇到连接关闭后就自动重试了。mosn的http2_use_stream其实我在本地配置文件加上没有生效，我是手动改了代码才生效的。
![image](https://user-images.githubusercontent.com/24311963/130385597-fe0f94ba-dfee-4a2f-8664-94a617b73f6d.png)
改完后重新编译，使用以下配置文件启动mosn：

``` json
{
	"close_graceful" : false,
	"servers":[
		{
			"default_log_path": "stdout",
			"default_log_level": "DEBUG",
			"graceful_timeout": "5s",
			"routers":[
				{
					"router_config_name":"grpc_router",
					"virtual_hosts":[{
						"name":"grpcHost",
						"domains": ["*"],
						"routers": [
							{
								"match":{"prefix":"/"},
								"route":{"cluster_name":"grpcCluster|GRPC"}
							}
						]
					}]
				}
			],
			"listeners":[
				{
					"name":"grpcListener",
					"address": "127.0.0.1:2045",
					"bind_port": true,
					"filter_chains": [{
						"filters": [
							{
								"type": "proxy",
								"config": {
									"downstream_protocol": "Http2",
									"upstream_protocol": "Http2",
									"router_config_name":"grpc_router",
									"extend_config": {
										"http2_use_stream": true
									}
								}
							}
						]
					}]
				}
			]
		}
	],
	"cluster_manager":{
		"clusters":[
			{
				"name": "grpcCluster|GRPC",
				"type": "SIMPLE",
				"lb_type": "LB_RANDOM",
				"max_request_per_conn": 1024,
				"conn_buffer_limit_bytes":32768,
				"hosts":[
					{"address":"127.0.0.1:21280"},
					{"address":"127.0.0.1:21278"}
				]
			}
		]
	},
	"admin": {
		"address": {
			"socket_address": {
				"address": "0.0.0.0",
				"port_value": 34901
			}
		}
	}
}
```

在本地启动mock server：
``` golang
package main

import (
	"context"
	"log"
	"net"
	"net/http"

	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/helloworld/helloworld"
	"google.golang.org/grpc/reflection"
)

type server struct {
	pb.UnimplementedGreeterServer
}

func (s *server) SayHello(context.Context, *pb.HelloRequest) (*pb.HelloReply, error) {
	return &pb.HelloReply{
		Message: "hello world",
	}, nil
}

func main() {
	go http.ListenAndServe(":21278", http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		writer.WriteHeader(http.StatusOK)
	}))
	// 监听端口
	lis, err := net.Listen("tcp", ":21280")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```
之后使用命令：grpcurl -plaintext 127.0.0.1:2045 helloworld.Greeter.SayHello
会发现请求有一半几率hang住不动。

**Comment by taoyuanyuan** [comment]
@XIEZHENGYAO 好的哈，我看看，不过stream的也不应该支持重试，需要关掉。
你用非流式的有问题吗？

**Comment by XIEZHENGYAO** [comment]
非流式没有这个问题，因为非流式的我看在同一个routine下写的upstream data，连接关闭后去写数据会直接返回err，然后再重试的话就返回502了。

**Comment by taoyuanyuan** [comment]
@XIEZHENGYAO 流式的话本来就支持不了重试，比如已经传输的部分body是不会保存的，没办法重试给下一个peer。
这儿需要改两个地方：
1. 在只发送header，还没有发送body的情况下，支持重试。（目测不太好改）
2. 发送了部分body的情况下，不支持重试。 
或者就是流式的场景下，都不支持重试。
小哥有啥想法？

**Comment by XIEZHENGYAO** [comment]
一般会做重试的请求我们这是只针对建立连接失败的情况，如果连接是通的就不会重试了，所以我比较支持粗暴点不做重试，因为写header成功代表连接本身没问题。
现在要解决的是不是连接关闭后不再重试？因为我看代码，连接关闭会得到一个`StreamConnectionFailed`的事件，实际上应该是`StreamConnectionTermination`。

**Comment by taoyuanyuan** [comment]
除了连接层面的重试，也有针对40x，50x的应用层面的重试，这个其实也是配置可配的，所有有些场景下连接关闭了也是需要重试的。。
这儿我也认为可以粗暴点不重试了，但只是在流式的场景下，就算配置了重试也不能重试。

**Comment by XIEZHENGYAO** [comment]
赞成。流式的场景就不重试了吧，但是我们的业务场景流式是需要打开的，在遇到连接connection refused或connection timeout的场景下是需要重试的。
但是现在不管用不用流式，在连接关闭的情况下也给了`StreamConnectionFailed`事件，导致没法和建立连接失败的场景区分开。如果统一都重试就会导致上面的问题。

**Comment by taoyuanyuan** [comment]
看了下代码，h2这儿特殊处理了，因为在goaway的场景下，server发了goaway，client可能还在发stream，就会导致失败，这个失败是需要重试的，所以把应该是StreamConnectionTermination的改成StreamConnectionFailed，为了支持兜底重试。

https://github.com/mosn/mosn/blob/f3fc4c31ddee9db296e3620cab7b8eee16255135/pkg/stream/http2/stream.go#L1038
看可以修改这个函数不，是stream的，并且不是goaway的，就改成StreamConnectionTermination

**Comment by XIEZHENGYAO** [comment]
我看这个函数已经对go away做了处理了，连接关闭的事件处理在go away的逻辑之后，直接去掉这段代码是不是OK？

**Comment by XIEZHENGYAO** [comment]
另外，https://github.com/mosn/mosn/blob/f3fc4c31ddee9db296e3620cab7b8eee16255135/pkg/stream/http2/connpool.go#L208

**Comment by XIEZHENGYAO** [comment]
另外，我看这段代码和HTTP1的实现不太一样，先建立连接再做的AddListener，导致连接建立成功的时间没有给到client，就算连接断开也认为是ConnectionFailed。
https://github.com/mosn/mosn/blob/f3fc4c31ddee9db296e3620cab7b8eee16255135/pkg/stream/http2/connpool.go#L208

**Comment by taoyuanyuan** [comment]
> 另外，我看这段代码和HTTP1的实现不太一样，先建立连接再做的AddListener，导致连接建立成功的时间没有给到client，就算连接断开也认为是ConnectionFailed。
> https://github.com/mosn/mosn/blob/f3fc4c31ddee9db296e3620cab7b8eee16255135/pkg/stream/http2/connpool.go#L208

确实如此，看了下原因是在createStreamClient里面会做连接的初始化工作，比如发settting帧这些，所以需要在connect成功之后，需要简单改下，把setting这些初始化延后，在真正write的时候做了。

**Comment by XIEZHENGYAO** [comment]
我又发现一个问题，HTTP2流式即使在遇到goaway异常时重试，也会因为SendData被读了而无法重试。。目前看来能重试成功的也只有建连失败或NewStream的时候就已经goaway了。

**Comment by XIEZHENGYAO** [comment]
我又发现一个问题，HTTP2开启流式后即使在遇到goaway异常时重试，也会因为SendData被读了而无法重试。。目前看来能重试成功的也只有建连失败或NewStream的时候就已经goaway了的场景。
在我们的业务场景下，mosn代理支持流式是基本需求，但是引入流式又会导致server重启时因为goaway损失部分请求。我们大部分业务都是用gRPC的unary，少部分会使用bidi stream。为此，我想了以下的解决办法：
serverStreamConnection在handleFrame的函数中，判断第一个data帧是否是endStream，如果是，即使配置了流式也不用，如果不是，再走流式。这样可以避免大部分unary请求的损失，因为大部分unary请求data不超过一帧（16kb）.
不知道老哥怎么看？

**Comment by XIEZHENGYAO** [comment]
而且考虑到流式多起一个routine的性能问题，body size非常小的unary request走流式也是个性能损失。

**Comment by alpha-baby** [comment]
> 我又发现一个问题，HTTP2开启流式后即使在遇到goaway异常时重试，也会因为SendData被读了而无法重试。。目前看来能重试成功的也只有建连失败或NewStream的时候就已经goaway了的场景。
> 在我们的业务场景下，mosn代理支持流式是基本需求，但是引入流式又会导致server重启时因为goaway损失部分请求。我们大部分业务都是用gRPC的unary，少部分会使用bidi stream。为此，我想了以下的解决办法：
> serverStreamConnection在handleFrame的函数中，判断第一个data帧是否是endStream，如果是，即使配置了流式也不用，如果不是，再走流式。这样可以避免大部分unary请求的损失，因为大部分unary请求data不超过一帧（16kb）.
> 不知道老哥怎么看？

server重启时因为goaway损失部分请求，grpc本身是用的两次go away来解决了goaway帧竞争的问题，你说的这个损失部分请求是什么意思呢？你是说这个请求在mosn里面损失的？

**Comment by alpha-baby** [comment]
> 流式多起一个routine

流式多起一个routine，这个routine是多在哪块代码的呀？

**Comment by XIEZHENGYAO** [comment]
> server重启时因为goaway损失部分请求，grpc本身是用的两次go away来解决了goaway帧竞争的问题，你说的这个损失部分请求是什么意思呢？你是说这个请求在mosn里面损失的？

这个是mosn的流式实现导致的，goaway帧无法阻止已经在RoundTrip函数的写请求写data，而useStream会导致data被读完之后就无法再读。
https://github.com/mosn/mosn/blob/f3fc4c31ddee9db296e3620cab7b8eee16255135/pkg/module/http2/mhttp2.go#L1090
routetine也是这个函数内启动的。

**Comment by taoyuanyuan** [comment]
> 我又发现一个问题，HTTP2开启流式后即使在遇到goaway异常时重试，也会因为SendData被读了而无法重试。。目前看来能重试成功的也只有建连失败或NewStream的时候就已经goaway了的场景。
> 在我们的业务场景下，mosn代理支持流式是基本需求，但是引入流式又会导致server重启时因为goaway损失部分请求。我们大部分业务都是用gRPC的unary，少部分会使用bidi stream。为此，我想了以下的解决办法：
> serverStreamConnection在handleFrame的函数中，判断第一个data帧是否是endStream，如果是，即使配置了流式也不用，如果不是，再走流式。这样可以避免大部分unary请求的损失，因为大部分unary请求data不超过一帧（16kb）.
> 不知道老哥怎么看？

你的方案挺好的，欢迎pr，👍

**Comment by taoyuanyuan** [comment]
> > 我又发现一个问题，HTTP2开启流式后即使在遇到goaway异常时重试，也会因为SendData被读了而无法重试。。目前看来能重试成功的也只有建连失败或NewStream的时候就已经goaway了的场景。
> > 在我们的业务场景下，mosn代理支持流式是基本需求，但是引入流式又会导致server重启时因为goaway损失部分请求。我们大部分业务都是用gRPC的unary，少部分会使用bidi stream。为此，我想了以下的解决办法：
> > serverStreamConnection在handleFrame的函数中，判断第一个data帧是否是endStream，如果是，即使配置了流式也不用，如果不是，再走流式。这样可以避免大部分unary请求的损失，因为大部分unary请求data不超过一帧（16kb）.
> > 不知道老哥怎么看？
> 
> server重启时因为goaway损失部分请求，grpc本身是用的两次go away来解决了goaway帧竞争的问题，你说的这个损失部分请求是什么意思呢？你是说这个请求在mosn里面损失的？

这只是grpc这样处理，http2并不是
