### ISSUE TITLE
[Question]为什么这里TLS1.3没有TransferSetTLSInfo(hs)

### ISSUE THREAD

**Issue by titanxxh** [mosn/mosn#1801]
https://github.com/mosn/mosn/blob/35636c406ee4b80e4898f0da6d026e0dd854d218/pkg/mtls/crypto/tls/handshake_server.go#L52

下面那个return前会设置`TransferSetTLSInfo(hs)`

**Comment by taoyuanyuan** [comment]
开发这个功能的时候， go tls还没正式支持tls1.3，有兴趣可以pr
