### ISSUE TITLE
mem leak

### ISSUE THREAD

**Issue by Dennis8274** [mosn/mosn#1818]
https://github.com/mosn/mosn/blob/102c1aa0e2df8bed96cd34d760b5bb13f07edced/pkg/stream/xprotocol/connpool_binding.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L84

**Comment by taoyuanyuan** [comment]
thank you!
