### ISSUE TITLE
prefix_rewrite can't rewrite  `/app/app1` to `/app1`

### ISSUE THREAD

**Issue by Bryce-huang** [mosn/mosn#1824]
### Describe the bug

prefix_rewrite can't rewrite  `/app/app1` to `/app1`

### Expected behavior

success request  
`/app/app1` to `/app1`
### Actual behavior

`/app/app1` to `/app/app1`

### Minimal yet complete reproducer code (or GitHub URL to code)

```json
  "routers": [
                {
                  "match": {
                    "prefix": "/app"
                  },
                  "route": {
                    "cluster_name": "app",
                    "regex_rewrite": {
                      "pattern": "/"
                    }
                  }
                }
              ]
```

### Environment

- MOSN Version 0.24

**Comment by taoyuanyuan** [comment]
thank you for your feedback! PR welcome!
