### ISSUE TITLE
codecClient is nil cause panic

### ISSUE THREAD

**Issue by cuiweixie** [mosn/mosn#1850]
### Describe the bug
panic at this line https://github.com/mosn/mosn/blob/master/pkg/stream/xprotocol/connpool_pingpong.go#L348 
because of codecClient is nil

### Expected behavior
 no panic
### Actual behavior
panic
### Steps to reproduce
1. change bolt protocol mode to pingpong
2. set the ip in https://github.com/mosn/mosn/blob/master/examples/codes/sofarpc-with-xprotocol-sample/client_config.json#L54  to a ip that will cause connection timeout
3. build mosn, then run mosn -c client_config.json at sofarpc-with-xprotocol-sample
4. go run client.go 
5. then you will see the panic log
`2021-11-19 20:02:09,511 [ERROR] [mosn.proxy.panic] [2,-] [proxy] [downstream] OnReceive panic: runtime error: invalid memory address or nil pointer dereference, downstream: &{ID:1 proxy:0xc000b4a000 route:0xc000862ed0 cluster:0xc000777180 element:0xc000b34240 bufferLimit:0 timeout:{GlobalTimeout:-1000000 TryTimeout:0} retryState:0xc000b95ae0 requestInfo:0xc000b66210 responseSender:0xc000b64078 upstreamRequest:0xc000b66188 perRetryTimer:<nil> responseTimer:<nil> downstreamReqHeaders:0xc000b3c3c0 downstreamReqDataBuf:<nil> downstreamReqTrailers:<nil> downstreamRespHeaders:<nil> downstreamRespDataBuf:<nil> downstreamRespTrailers:<nil> upstreamResponseReceived:0 downstreamResponseStarted:false downstreamRecvDone:true upstreamRequestSent:false upstreamProcessDone:{_:[] v:{_:[] v:0}} noConvert:false directResponse:false oneway:false notify:0xc000398360 downstreamReset:1 downstreamCleaned:0 upstreamReset:0 reuseBuffer:1 resetReason:{_:[] v:{Value:{v:ConnectionTermination} _:[]}} streamFilterChain:{downStream:0xc000b66000 DefaultStreamFilterChainImpl:0xc000b38120} receiverFiltersAgainPhase:0 context:0xc000b3c1e0 tracks:0xc000b62000 logDone:0 snapshot:0xc0008628a0 phase:6}, oldId: 1, newId: 1
goroutine 23 [running]:
runtime/debug.Stack(0xc0004824b8, 0x22d4880, 0x36cee50)
	/home/weixiecui/go/src/runtime/debug/stack.go:24 +0x9f
mosn.io/mosn/pkg/proxy.(*downStream).OnReceive.func1.1(0xc000b66000, 0x1)
	/home/weixiecui/test/mosn/pkg/proxy/downstream.go:395 +0x5e
panic(0x22d4880, 0x36cee50)
	/home/weixiecui/go/src/runtime/panic.go:969 +0x1b9
mosn.io/mosn/pkg/stream/xprotocol.(*activeClientPingPong).OnEvent(0xc000400240, 0x25c3133, 0xe)
	/home/weixiecui/test/mosn/pkg/stream/xprotocol/connpool_pingpong.go:348 +0x866
mosn.io/mosn/pkg/network.(*clientConnection).Connect.func1()
	/home/weixiecui/test/mosn/pkg/network/connection.go:1180 +0xfb
sync.(*Once).doSlow(0xc00044ed58, 0xc000566c60)
	/home/weixiecui/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/home/weixiecui/go/src/sync/once.go:57
mosn.io/mosn/pkg/network.(*clientConnection).Connect(0xc00044eb40, 0x27dc240, 0xc0005527d0)
	/home/weixiecui/test/mosn/pkg/network/connection.go:1169 +0x85
mosn.io/mosn/pkg/stream/xprotocol.(*poolPingPong).newActiveClient(0xc000b335c0, 0x2824400, 0xc000b3c1e0, 0x25b606d, 0x4, 0x7f385c079f01, 0x400, 0xc000b43438)
	/home/weixiecui/test/mosn/pkg/stream/xprotocol/connpool_pingpong.go:209 +0x297
mosn.io/mosn/pkg/stream/xprotocol.(*poolPingPong).GetActiveClient(0xc000b335c0, 0x2824400, 0xc000b3c1e0, 0x25b606d, 0x4, 0x0, 0x0, 0x0)
	/home/weixiecui/test/mosn/pkg/stream/xprotocol/connpool_pingpong.go:113 +0x285
mosn.io/mosn/pkg/stream/xprotocol.(*poolPingPong).NewStream(0xc000b335c0, 0x2824400, 0xc000b3c1e0, 0x27f9b80, 0xc000b66188, 0x2824400, 0xc000b3c1e0, 0x2831f80, 0xc000b3c3c0, 0x284efa0, ...)
	/home/weixiecui/test/mosn/pkg/stream/xprotocol/connpool_pingpong.go:63 +0x113
mosn.io/mosn/pkg/proxy.(*upstreamRequest).appendHeaders(0xc000b66188, 0x2824401)
	/home/weixiecui/test/mosn/pkg/proxy/upstream.go:176 +0x155
mosn.io/mosn/pkg/proxy.(*downStream).receiveHeaders(0xc000b66000, 0x1)
	/home/weixiecui/test/mosn/pkg/proxy/downstream.go:887 +0xae
mosn.io/mosn/pkg/proxy.(*downStream).receive(0xc000b66000, 0x2824400, 0xc000b3c1e0, 0x1, 0x6, 0x0)
	/home/weixiecui/test/mosn/pkg/proxy/downstream.go:536 +0xdd
mosn.io/mosn/pkg/proxy.(*downStream).OnReceive.func1()
	/home/weixiecui/test/mosn/pkg/proxy/downstream.go:407 +0xca
mosn.io/mosn/pkg/sync.(*workerPool).spawnWorker(0xc000868540, 0xc000b33580)
	/home/weixiecui/test/mosn/pkg/sync/workerpool.go:93 +0x56
created by mosn.io/mosn/pkg/sync.(*workerPool).ScheduleAuto
	/home/weixiecui/test/mosn/pkg/sync/workerpool.go:73 +0x24d
2021-11-19 20:02:09,511 [ERROR] [2,-] [proxy] [downstream] upstreamRequest.resetStream, proxyId: 1
`
set upstream

### Environment

- MOSN Version master

**Comment by taoyuanyuan** [comment]
thanks for your feedback！
