### ISSUE TITLE
[healthCheck] if net return error when establishing a connection and set host unhealthy immediately

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#1858]
### Your question

主动【健康检查】是一个较慢的过程，往往需要几秒到几分钟不等。
那么就需要一些被动检查策略来辅助达到比较好的效果。

例如：可以在[这里](https://github.com/mosn/mosn/blob/master/pkg/stream/xprotocol/connpool_multiplex.go#L265), 当建立连接失败就马上设置 host 状态为【不健康】
但是这里有个因素需要注意，如果用户没有开启主动健康检查策略，在上述中提到的地方设置为不健康后，就没有地方重新把 host 设置回 【健康】，所以在前面要判断一下

或者把这里的结果往健康检查器中提交，健康检查器会根据已经配置了的规则把 host 设置为 【不健康】

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by nejisama** [comment]
不要做这种默认行为，可以扩展健康检查的机制来做类似的功能。比如单机故障隔离的StreamFilter:https://github.com/mosn/mosn/tree/master/pkg/filter/stream/faulttolerance

在实际生产实践做，健康检查都需要控制一定的阈值，否则会造成健康的机器被压垮引发血崩，最终导致所有的服务不可用的情况

**Comment by alpha-baby** [comment]
> https://github.com/mosn/mosn/tree/master/pkg/filter/stream/faulttolerance

ok
