### ISSUE TITLE
配置迁移时,未赋值给Mosn.config

### ISSUE THREAD

**Issue by jialongli** [mosn/mosn#1880]
https://github.com/mosn/mosn/blob/7222aafcdd2d6d7f9bf285b1ef1a3b9e97c8bbeb/pkg/mosn/mosn.go#L91

这里没有赋值回去吧 应加上m.Config = c

**Comment by doujiang24** [comment]
@jialongli 你是碰到这方面的问题了么？

1. m.Config 是更新了的
2.但是 configmanager 是没有更新的，这一行的 c 是配置迁移前的，这个已经在 #1859 里修复了 
https://github.com/mosn/mosn/blob/7222aafcdd2d6d7f9bf285b1ef1a3b9e97c8bbeb/pkg/mosn/mosn.go#L59

**Comment by jialongli** [comment]
> 

是的.提完issue.发现master里修复了...
