### ISSUE TITLE
[Question]sidecar 流量劫持

### ISSUE THREAD

**Issue by sanxun0325** [mosn/mosn#1895]
### Your question
在官网[流量劫持](https://mosn.io/docs/concept/traffic-hijack/)章节，了解到sidecar 主要是代理注册server实例，调用者调用时从注册中心获取到sidecar 的ip和端口，将请求发送到sidecar实例上，sidecar再进行转发到真正的server实例上。

想了解一下 当server实例由于各种原因导致进程挂掉，sidecar依然存活的情况下，sidecar能否感知到server实例挂掉。实现机制是怎样的？

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by alpha-baby** [comment]
你可以 在 sidecar 上去探测 server 是否健康的，mosn 中有探测机制的扩展，在这个目录下 `pkg/upstream/healthcheck`
@sanxun0325

**Comment by sanxun0325** [comment]
非常感谢回答
