### ISSUE TITLE
请问 mosn 作为 TCP 代理时，是否支持 TLS 卸载

### ISSUE THREAD

**Issue by xuyang2** [mosn/mosn#1901]
请问 mosn 作为 TCP 代理时，是否支持 [TLS 卸载](https://en.wikipedia.org/wiki/TLS_termination_proxy) 呢，
即 client 到 mosn 是 TLS 通信，mosn 到 upstream 是明文通信？

目前粗略看了一下 mosn 文档，没能得出结论
- https://github.com/mosn/mosn/tree/master/examples/cn_readme/tcpproxy-sample
- https://mosn.io/blog/code/mosn-tls/

TLS termination 相关资料见：
- https://en.wikipedia.org/wiki/TLS_termination_proxy
- https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-tcp/

**Comment by taoyuanyuan** [comment]
可以的哈，tcp代理配上tls_context的配置就行了

**Comment by xuyang2** [comment]
@taoyuanyuan 感谢回复，我试试

**Comment by taoyuanyuan** [comment]
@xuyang2  https://github.com/mosn/mosn/blob/74353b469d6eb3754640fd739375520a50d6cb56/examples/codes/http-sample/tls_server_config.json#L28
你可以仿照下http的tls配置

**Comment by xuyang2** [comment]
@taoyuanyuan 
试了一下，修改 [examples/codes/tcpproxy-sample/config.json](https://github.com/mosn/mosn/blob/74353b469d6eb3754640fd739375520a50d6cb56/examples/codes/tcpproxy-sample/config.json#L13) 的 `servers[0].listeners[0].filter_chains[0].tls_context` 后，
`go run http.go` 然后 `curl https://127.0.0.1:2045/` 调用成功了。

另外修改 [examples/codes/tcpproxy-sample/rpc_client.go](https://github.com/mosn/mosn/blob/74353b469d6eb3754640fd739375520a50d6cb56/examples/codes/tcpproxy-sample/rpc_client.go) 的 `NewClient()` 方法，改成
```
	tlsCfg := v2.TLSConfig{
		Status:     true,
		CACert:     "../certs/ca.pem",
		CertChain:  "../certs/cert.pem",
		PrivateKey: "../certs/key.pem",
		ServerName: "127.0.0.1",
	}
	cltMng, err := mtls.NewTLSClientContextManager(&tlsCfg)
	if err != nil {
		panic(err)
	}

	conn := network.NewClientConnection(0, cltMng, remoteAddr, stopChan)
```
然后 `go run rpc_server.go`  和 `go run rpc_client.go` 也调用成功。

说明 mosn 作为 TCP 代理转发 HTTP 和 RPC 都是支持 TLS 卸载的。多谢指点。
