### ISSUE TITLE
unexpected handler of sigal interrupt

### ISSUE THREAD

**Issue by cuiweixie** [mosn/mosn#1906]
### Describe the bug

if catchSignalsCrossPlatform handle SIGINT with a little long time, handler in catchSignalsPosix will exit quickly without waitting catchSignalsCrossPlatform to exit.

### Environment

- MOSN Version

**Comment by nejisama** [comment]
The signal-related logic is being reconstructed, and we no longer directly provide signal-related processing
see https://github.com/mosn/mosn/pull/1859

**Comment by doujiang24** [comment]
@cuiweixie Already fixed in https://github.com/mosn/mosn/pull/1859. Thanks, closing it.
