### ISSUE TITLE
MOSN支持http的健康检查功能

### ISSUE THREAD

**Issue by rickey17** [mosn/mosn#1939]
### The New Feature

MOSN支持http的健康检查功能
MOSN支持第一次健康检查delay，类似k8s liveness

### Your scenes

我的java server是springcloud的应用，实现了actuator的http健康接口，健康状态不仅包括进程存活，端口监听，也包括应用的业务逻辑健康等。并且java程序启动的时候，可能启动时间比较长。

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by nejisama** [comment]
健康检查本身支持扩展实现，可以按照需求实现一个扩展实现，满足对应的需求。 如果扩展实现的比较通用，可以贡献到开源库里来

**Comment by nejisama** [comment]
如果是需要额外提供一个端口，提供健康检查服务？这个可以参考pkg/admin/store下实现一个service，单独实现一个满足需求http server注册进来，也是MOSN的标准扩展方式之一，可以拥有平滑升级等能力。MOSN部分额外的HTTP服务也是这样实现的

**Comment by rickey17** [comment]
不需要提供一个服务端口，只是需要http的检查检查，这个可以扩展实现，不放在里面。

**Comment by rickey17** [comment]
http健康检查，有一些额外的信息，如端口（可能不是rpc的端口），path，http超时时间。

**Comment by rickey17** [comment]
> 如果是需要额外提供一个端口，提供健康检查服务？这个可以参考pkg/admin/store下实现一个service，单独实现一个满足需求http server注册进来，也是MOSN的标准扩展方式之一，可以拥有平滑升级等能力。MOSN部分额外的HTTP服务也是这样实现的

不需要提供一个服务端口，只是需要http的检查检查，这个可以扩展实现，不放在里面。
然后还需要加一个健康检查的参数，第一次健康检查delay，类似k8s liveness。现在mosn是默认写死的常量，1S，这个目前很多用户希望能自己配置。
http健康检查，有一些额外的信息，如端口（可能不是rpc的端口），path，http超时时间。
