### ISSUE TITLE
MOSN是否支持动态设置BindPort

### ISSUE THREAD

**Issue by rickey17** [mosn/mosn#1940]
### Your question

我的mosn前面有个负载均衡器，当mosn的端口开始监听的时候，负载均衡器就会认为业务正常，但是实际情况，mosn监听端口不一定代表业务正常。

所以咨询一下mosn是否支持动态设置BindPort，比如我的listenerConfig默认设置bindToPort=false，等业务逻辑ready了（如：健康检查通过了），再主动set bindToPort = true，开始监听端口。

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by doujiang24** [comment]
这个感觉不是太好，不过感觉也有一定的合理性，有些没有考虑中间层的场景，就是用 tcp 连接来探测的

目前应该是不支持的，搞起来或许也有一定的复杂度，比如后面健康检查失败，还要把 listen 关闭？
也欢迎贡献 PR

**Comment by nejisama** [comment]
可以通过MOSN对代理业务的健康检查配置来动态添加Listener，而不是使用静态的Listener配置

**Comment by rickey17** [comment]
嗯，但是我如果设置bindToPort=false之后就不能监听了，所以一定要设置成true，那我启动的那个时候一定要打开了一会儿的，只能在后面主动关掉，感觉不太好。

**Comment by rickey17** [comment]
> 嗯，但是我如果设置bindToPort=false之后就不能监听了，所以一定要设置成true，那我启动的那个时候一定要打开了一会儿的，只能在后面主动关掉，感觉不太好。

嗯，但是我如果设置bindToPort=false之后就不能监听了，所以一定要设置成true，那我启动的那个时候一定要打开了一会儿的，只能在后面主动关掉，感觉不太好。
是否可以支持在设置bindToPort=false之后，也能开启监听器呢？

**Comment by rickey17** [comment]
> 嗯，但是我如果设置bindToPort=false之后就不能监听了，所以一定要设置成true，那我启动的那个时候一定要打开了一会儿的，只能在后面主动关掉，感觉不太好。 是否可以支持在设置bindToPort=false之后，也能开启监听器呢？

嗯，但是我如果设置bindToPort=false之后就不能监听了，所以一定要设置成true，那我启动的那个时候一定要打开了一会儿的，只能在后面主动关掉，感觉不太好。
是否可以支持在设置bindToPort=false之后，也能开启监听器呢？

**Comment by taoyuanyuan** [comment]
还有一个比较通用的方式是负载均衡使用七层健康检查

**Comment by rickey17** [comment]
> 还有一个比较通用的方式是负载均衡使用七层健康检查

怎么搞？

**Comment by taoyuanyuan** [comment]
举个例子，比如负载均衡的检查url是 GET /health, 你等你检查都ok了，touch这个空文件就行了，类似方式很多。
之前x系的lvs跟后端nginx的检查都是这样搞的

**Comment by rickey17** [comment]
> 举个例子，比如负载均衡的检查url是 GET /health, 你等你检查都ok了，touch这个空文件就行了，类似方式很多。 之前x系的lvs跟后端nginx的检查都是这样搞的

或者mosn里面可以在AddOrUpdateListener的时候也把BindToPort的配置可以更新掉吗？
或者mosn在Listener接口，里面加一个SetBindToPort的方法
这样的话，我收到健康的事件之后，就可以把端口从关闭，变成打开。

**Comment by taoyuanyuan** [comment]
> > 举个例子，比如负载均衡的检查url是 GET /health, 你等你检查都ok了，touch这个空文件就行了，类似方式很多。 之前x系的lvs跟后端nginx的检查都是这样搞的
> 
> 或者mosn里面可以在AddOrUpdateListener的时候也把BindToPort的配置可以更新掉吗？ 或者mosn在Listener接口，里面加一个SetBindToPort的方法 这样的话，我收到健康的事件之后，就可以把端口从关闭，变成打开。

那这个就跟鹏总说的没本质区别了，收到健康的事件，在去AddOrUpdateListener
BindToPort有其他的语义，是被透明劫持用的，并且也有stop和start listener的开关

**Comment by rickey17** [comment]
> 

BindToPort 这个不就是控制是不是监听端口用的吗？

**Comment by nejisama** [comment]
bindport为false的listener 是有用处的，代表虚拟listener。
你这个需求其实就是要动态配置Listener，当检查到服务健康的时候，主动Add/Start Listener； 检查到服务不健康的时候，主动Delete/Stop Listeners。
如果你觉得用Start和Stop比较难理解，可以改用Add/Delete，然后看下在Delete的时候增加Stop的实现

**Comment by taoyuanyuan** [comment]
目前BindToPort就不是一个动态的开关，就只是给透明劫持场景的listener用的。
先检查通过，再去AddOrUpdateListener有什么问题吗？
和你说的 AddOrUpdateListener(bindToPort=fasle) ； 检查通过；AddOrUpdateListener(bindToPort=true)， 不是还少一步么

**Comment by rickey17** [comment]
因为mosn start的时候，就会去调用Start()，也就是进程一起来，端口一定会监听，然后等走到后面，我再去主动关闭stop，那这段时间可能就有业务损失啦。

这个配置不是动态开关的考虑是什么？改成动态开关的问题是什么？

**Comment by taoyuanyuan** [comment]
> 因为mosn start的时候，就会去调用Start()，也就是进程一起来，端口一定会监听，然后等走到后面，我再去主动关闭stop，那这段时间可能就有业务损失啦。
> 
> 这个配置不是动态开关的考虑是什么？改成动态开关的问题是什么？

老哥，鹏总说的很清楚了啊 ， 先检查通过，在添加listener，端口不会提前监听啊
还有这个BindToPort你可以认为是一个listener的type，不是开关，是一个虚拟listener的类型标识

**Comment by rickey17** [comment]
现在我们用的FILE模式，不是xds模式。所以listerner config都写好了，在initServer()的时候就add进去了

>

**Comment by nejisama** [comment]
> 现在我们用的FILE模式，不是xds模式。所以listerner config都写好了，在initServer()的时候就add进去了
> 
> >

那你换一种模式啊，不走pilot推送，也可以动态调用AddListener这些啊，你健康检查的回调触发配置解析，调用AddListener接口不就行了。为什么一定要写到MOSN的启动配置里去

**Comment by rickey17** [comment]
BindToPort这个是一个标志，但是又控制了是否监听，是不是职责太多了。这个目前可以变成动态配置的吗？或者变成动态配置有什么缺点呢？

**Comment by nejisama** [comment]
虚拟的就是不会实际去监听这个地址，因为这个地址是别的进程（如app）监听的。
本身listener也是具备动态的能力的（Start/Stop/Close的接口都有），我不知道为什么一定要去修改原有配置的语义

**Comment by nejisama** [comment]
只有端口监听不代表服务正常的逻辑是普遍存在的，通常在引流的地方（比如负载均衡上），会配置对应的七层检查，也可以考虑往这个方向去配置，不要发现端口被监听了就引流也是一种办法。

**Comment by rickey17** [comment]
没有改语义。
那为什么UseOriginalDst和ListenerTag、PerConnBufferLimitBytes这些配置参数可以动态更新，但是BindToPort不可以呢？

**Comment by nejisama** [comment]
BindPort 涉及到系统资源的占用问题

**Comment by rickey17** [comment]
ok
