### ISSUE TITLE
Support slow start mode for WRR.

### ISSUE THREAD

**Issue by wangfakang** [mosn/mosn#1943]
### The New Feature

slow start mode is a config of cluster for setting in MOSN to progressively increase amount of traffic for newly added upstream endpoints.

### Your scenes

Describe your use scenes (why need this feature).

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by jizhuozhi** [comment]
Is it because some resources need to be warmed up? Such as Java's JIT

**Comment by jizhuozhi** [comment]
If we want to support this function, the more general should be to support the dynamic weight function, for example, the load balancer supports automatic weight reduction and automatic recovery after failure

**Comment by wangfakang** [comment]
> Is it because some resources need to be warmed up? Such as Java's JIT

yes.

**Comment by wangfakang** [comment]
> If we want to support this function, the more general should be to support the dynamic weight function, for example, the load balancer supports automatic weight reduction and automatic recovery after failure

You're right. If you're interested it, welcome to contribute PR.

**Comment by jizhuozhi** [comment]
> > If we want to support this function, the more general should be to support the dynamic weight function, for example, the load balancer supports automatic weight reduction and automatic recovery after failure
> 
> You're right. If you're interested it, welcome to contribute PR.

I'll try to understand how MOSN works and evaluate the cost, if possible, I'll implement this feature after Chinese New Year

**Comment by jizhuozhi** [comment]
Do we need to slow start according to time? @wangfakang

**Comment by wangfakang** [comment]
> Do we need to slow start according to time? @wangfakang For example, we have the slow_start_window as 10s, and the full weight is 100, then each 1s we warmup 10 weight

enh, using only the time dimension is similar to Envoy‘s [slow-start](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start). It may cause the slow-start does not work properly in individual scenarios. For example, when the request arrives, the slow start window has just been restored, as follows:

![image](https://user-images.githubusercontent.com/8215757/150940737-6b9e16ae-f1ee-4014-b7ef-2ac858f7b98d.png)

So, we should add another request dimension, and then control the weight recovery together with the time window. as follows:
![image](https://user-images.githubusercontent.com/8215757/150944610-e6df824d-8279-4291-8867-0ea5a311a686.png)

**Comment by jizhuozhi** [comment]
@wangfakang I don't understand what you mean in graphs.

It seems when the host is slow starting, it should be scheduled with the WRR, and we would recalculate the effective weight each time peeked but not using a fixed rate scheduler?

**Comment by wangfakang** [comment]
> @wangfakang I don't understand what you mean in graphs.
> 
> It seems when the host is slow starting, it should be scheduled with the WRR, and we would recalculate the effective weight each time peeked but not using a fixed rate scheduler?

If there is no traffic during slow-start time and the host weight has been restored during this time. This will cause incoming traffic after a slow-start time window to fail to warm up.

**Comment by jizhuozhi** [comment]
> > @wangfakang I don't understand what you mean in graphs.
> > It seems when the host is slow starting, it should be scheduled with the WRR, and we would recalculate the effective weight each time peeked but not using a fixed rate scheduler?
> 
> If there is no traffic during slow-start time and the host weight has been restored during this time. This will cause incoming traffic after a slow-start time window to fail to warm up.

But why not using ready or health probe by service registries?

**Comment by wangfakang** [comment]
> > > @wangfakang I don't understand what you mean in graphs.
> > > It seems when the host is slow starting, it should be scheduled with the WRR, and we would recalculate the effective weight each time peeked but not using a fixed rate scheduler?
> > 
> > 
> > If there is no traffic during slow-start time and the host weight has been restored during this time. This will cause incoming traffic after a slow-start time window to fail to warm up.
> 
> But why not using ready or health probe by service registries? It seems a delay-start rather than a slow-start, cause although slow it still has incoming traffic.

My above reply is intended to explain the picture rather than the desired effect of slow-start. BTW It is inelegant to control slow-start by the single dimension of time, as described above:
`using only the time dimension is similar to Envoy‘s slow-start. It may cause the slow-start does not work properly in some scenarios. For example, when the request arrives, the slow start time window has just been done.`

**Comment by alpha-baby** [comment]
完全基于时间的预热可能不太好，那可以再加一个基于请求数的预热机制。具体机制如下：

假设 host 的权重应该是 100，要求 30s 和 100 个请求同时满足这两个条件才保证当前 host 的权重预热到 100。

从 envoy 基于时间的预热机制可以知道，随着时间的流逝，可以计算出当前 host 的当前权重，假设为 timeWarmupWeight, 我们也可以基于现在已经有多少个请求发送给了当前 host 计算出当前 host 的当前权重（这里可以设计一个类似 envoy 这种弯曲的抛物线什么的去计算这个当前权重），假设为 requestsWarmupWeight.  

我们可以在 timeWarmupWeight， requestsWarmupWeight 这两个值中取一个最小值最为最终的结果，我感觉这样是一个可以解决前面所提到的问题。

**Comment by jizhuozhi** [comment]
> 完全基于时间的预热可能不太好，那可以再加一个基于请求数的预热机制。具体机制如下：
> 
> 假设 host 的权重应该是 100，要求 30s 和 100 个请求同时满足这两个条件才保证当前 host 的权重预热到 100。
> 
> 从 envoy 基于时间的预热机制可以知道，随着时间的流逝，可以计算出当前 host 的当前权重，假设为 timeWarmupWeight, 我们也可以基于现在已经有多少个请求发送给了当前 host 计算出当前 host 的当前权重（这里可以设计一个类似 envoy 这种弯曲的抛物线什么的去计算这个当前权重），假设为 requestsWarmupWeight.
> 
> 我们可以在 timeWarmupWeight， requestsWarmupWeight 这两个值中取一个最小值最为最终的结果，我感觉这样是一个可以解决前面所提到的问题。

Hello, @alpha-baby .

The biggest problem at this moment may not what's measurement should we choose, but how could we record the previous states after the load balancer has been rebuilt. 

Until May 4th (my last commit) there is neither delta fetch or timestamp maintained in service instance. So all instances are equal because the information are loosed after rebuilding, Slow-Start doesn't make any sense.

**Comment by alpha-baby** [comment]
> > 完全基于时间的预热可能不太好，那可以再加一个基于请求数的预热机制。具体机制如下：
> > 假设 host 的权重应该是 100，要求 30s 和 100 个请求同时满足这两个条件才保证当前 host 的权重预热到 100。
> > 从 envoy 基于时间的预热机制可以知道，随着时间的流逝，可以计算出当前 host 的当前权重，假设为 timeWarmupWeight, 我们也可以基于现在已经有多少个请求发送给了当前 host 计算出当前 host 的当前权重（这里可以设计一个类似 envoy 这种弯曲的抛物线什么的去计算这个当前权重），假设为 requestsWarmupWeight.
> > 我们可以在 timeWarmupWeight， requestsWarmupWeight 这两个值中取一个最小值最为最终的结果，我感觉这样是一个可以解决前面所提到的问题。
> 
> Hello, @alpha-baby .
> 
> The biggest problem at this moment may not what's measurement should we choose, but how could we record the previous states after the load balancer has been rebuilt.
> 
> Until May 4th (my last commit) there is neither delta fetch or timestamp maintained in service instance. So all instances are equal because the information are loosed after rebuilding, Slow-Start doesn't make any sense.

你这个问题好解决，这里可以拿到 old 的 cluster 和 host, 这样就可以把老的状态迁移到新的对象上面去了
https://github.com/mosn/mosn/blob/master/pkg/upstream/cluster/cluster_manager.go#L197

**Comment by jizhuozhi** [comment]
> 完全基于时间的预热可能不太好，那可以再加一个基于请求数的预热机制。具体机制如下：

Hello, @wangfakang and @alpha-baby 

Maybe we could provide three modes
1. Always bases on the duration elapsed from the host start time.
2. Always bases on the request time and uses the request time as time factor, just like the age of objects in Java's generation garbage collector.
3. Bases on both duration and request time to calculate time factor.

But in my opinion, the third mode is too complex that users cannot predict the traffic. I prefer to just provide first and second modes.

**Comment by jizhuozhi** [comment]
Here is a general formula for slow start using multiple factors

$$
NewWeight = weight * \prod_{i=0}^{n}{f_i(host)}^\frac{1}{\alpha} = weight * (\prod_{i=0}^{n}{f_i(host)})^\frac{1}{\alpha} 
$$

Where $f_i(host)$ is using host to calculate a factor.

**Comment by alpha-baby** [comment]
> > 完全基于时间的预热可能不太好，那可以再加一个基于请求数的预热机制。具体机制如下：
> 
> Hello, @wangfakang and @alpha-baby
> 
> Maybe we could provide three modes
> 
> 1. Always bases on the duration elapsed from the host start time.
> 2. Always bases on the request time and uses the request time as time factor, just like the age of objects in Java's generation garbage collector.
> 3. Bases on both duration and request time to calculate time factor.
> 
> But in my opinion, the third mode is too complex that users cannot predict the traffic. I prefer to just provide first and second modes.

@wangfakang What do you think？

**Comment by wangfakang** [comment]
> > > 完全基于时间的预热可能不太好，那可以再加一个基于请求数的预热机制。具体机制如下：
> > 
> > 
> > Hello, @wangfakang and @alpha-baby
> > Maybe we could provide three modes
> > 
> > 1. Always bases on the duration elapsed from the host start time.
> > 2. Always bases on the request time and uses the request time as time factor, just like the age of objects in Java's generation garbage collector.
> > 3. Bases on both duration and request time to calculate time factor.
> > 
> > But in my opinion, the third mode is too complex that users cannot predict the traffic. I prefer to just provide first and second modes.
> 
> @wangfakang What do you think？

It can continue to iterate in next versions, but the current version needs to be designed to support slow-start extensions of multiple dimensions.

**Comment by jizhuozhi** [comment]
> Here is a general formula for slow start using multiple factors

This formula could be simplify to 

$$
NewWeight = weight * f(host)^\frac{1}{\alpha} 
$$


$f(host)$ is used to calculate the slow start factor, which is equivalent to the following formula but can be replaced when using multi-dimensional slow start

$$
f(host) = \prod_{i=0}^{n}{f_i(host)}
$$

**Comment by spacewander** [comment]
Solved by https://github.com/mosn/mosn/pull/2178?

**Comment by doujiang24** [comment]
yep, closing it, thanks.
