### ISSUE TITLE
如何在acesslog中获取请求path

### ISSUE THREAD

**Issue by MengJiapeng** [mosn/mosn#1947]
### Your question

http1的method、path信息在request line中，并没有在key-value形式的header里，MOSN的accesslog貌似也没有提供获取request line的变量名，请问有什么办法可以在accesslog中打印请求的path和method么？

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
@MengJiapeng https://github.com/mosn/mosn/blob/7ce0de68bcde5c01b44535925162267f6e8208db/pkg/stream/http/var.go#L45
可以配置http相关的变量

**Comment by MengJiapeng** [comment]
> @MengJiapeng
> 
> https://github.com/mosn/mosn/blob/7ce0de68bcde5c01b44535925162267f6e8208db/pkg/stream/http/var.go#L45
> 
> 
> 可以配置http相关的变量

好的，谢谢！
