### ISSUE TITLE
Add weigth != 0 Check for Weighted Round Robin LoadBalancer

### ISSUE THREAD

**Issue by antJack** [mosn/mosn#1969]
When adding item to edfSchduler, we do not check weight != 0, which may causes undefined behavior for MOSN
![image](https://user-images.githubusercontent.com/52443884/156288563-2ced1ff5-dd0b-4d88-823f-17d83f6bbb09.png)

This issue proposes the adding of zero check for MOSN LB, not only for WRR

ref:
![image](https://user-images.githubusercontent.com/52443884/156288688-e666654e-f25e-4f1e-9fd5-2685711ffc12.png)

cc. @alpha-baby @jizhuozhi

**Comment by alpha-baby** [comment]
i have another question:

![image](https://user-images.githubusercontent.com/47237632/156298403-58ea706b-213d-4ad4-9973-f0c5123aea19.png)

When `weightFunc` return 0, do we need to remove the iterm from the edf heap?

**Comment by jizhuozhi** [comment]
Which condition would we get 0 weight, and if there is only one item, what will be happened if we remove it?

**Comment by jizhuozhi** [comment]
I think it's necessary to keep the size of items consistent @alpha-baby @antJack

**Comment by antJack** [comment]
what if rounding any weight<=0 to weight=1?

envoy's load_balancing_weight is uint32 and min value is 1.

ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-lbendpoint

**Comment by jizhuozhi** [comment]
Maybe it's not a bug but a feature~~.
We could make it clear in the documentation that we don't accept negative numbers (or negative numbers have the highest priority), and 0 is a fallback, 0 items will not be used until all non-zero items are invalid

**Comment by antJack** [comment]
1. `weight=0` will yield `1.0/weight = +Inf` which causes undefined behavior for further code execution. And that's what we should prevent.
2. as for the meaning of `weight<=0`, still cannot imagine in which scenario that we should allow `weight<=0`. Currently I suggest keeping it simple, or there's any scenario?

**Comment by antJack** [comment]
MOSN has host weight const： in pkg/configmanager/parser.go
![image](https://user-images.githubusercontent.com/52443884/156302928-66dfcc3e-d38e-4152-b8b6-197b9c5a3542.png)

**Comment by jizhuozhi** [comment]
So there is only one problem: what should we do when weightFunc return 0 or less than 0

I think this value can be fixed using a consistent contract

**Comment by antJack** [comment]
maybe we should keep consistent: if weightFunc return `<MinHostWeight` then set to `MinHostWeight`, if `> MaxHostWeight` then set to `MaxHostWeight`
