### ISSUE TITLE
关于layotto或mosn一些使用问题

### ISSUE THREAD

**Issue by unionhu** [mosn/mosn#1984]
1.如果使用layotto，是不是指定的layotto的一个版本即可，layotto和mosn的版本的升级怎么搞？layotto升级是否有无损的方案？
2.如何通过istio启动layotto？
3.对于iptables的流量劫持和tproxy的流量劫持压测是否有报告？
4.mosn的tproxy流量劫持开启使用文档
5.如果sidecar出现问题了，如何快速的实现不走sidecar，走回原来的调用方式

**Comment by seeflood** [comment]
1.如果使用layotto，是不是指定的layotto的一个版本即可
---
是的。
Layotto和mosn是一个进程，可以理解成 layotto=mosn+一个特殊的grpcfilter 打包到一起, 升级 layotto == 升级mosn
layotto和mosn 的版本是一一对应的关系，之前发布的v0.3.0的layotto对应的mosn版本为 v0.24.1 
所以：如果使用了 layotto，sidecar镜像里指定layotto的一个版本即可，不用另外再指定 mosn 版本

layotto和mosn的版本的升级怎么搞？
---
用k8s部署、升级，升级sidecar镜像里的 layotto版本即可


layotto升级是否有无损的方案？
---
有，升级 layotto == 升级mosn，mosn 支持平滑升级，做长连接迁移，见
https://mosn.io/docs/concept/smooth-upgrade/

不过这种方式需要通过发信号的方式在本机做平滑升级，或者开发定制的 Operator

**Comment by unionhu** [comment]
> ## 1.如果使用layotto，是不是指定的layotto的一个版本即可
> 是的。 Layotto和mosn是一个进程，可以理解成 layotto=mosn+一个特殊的grpcfilter 打包到一起, 升级 layotto == 升级mosn layotto和mosn 的版本是一一对应的关系，之前发布的v0.3.0的layotto对应的mosn版本为 v0.24.1 所以：如果使用了 layotto，sidecar镜像里指定layotto的一个版本即可，不用另外再指定 mosn 版本
> 
> ## layotto和mosn的版本的升级怎么搞？
> 用k8s部署、升级，升级sidecar镜像里的 layotto版本即可
> 
> ## layotto升级是否有无损的方案？
> 有，升级 layotto == 升级mosn，mosn 支持平滑升级，做长连接迁移，见 https://mosn.io/docs/concept/smooth-upgrade/
> 
> 不过这种方式需要通过发信号的方式在本机做平滑升级，或者开发定制的 Operator

具体怎么发送这个信号？

**Comment by unionhu** [comment]
> > ## 1.如果使用layotto，是不是指定的layotto的一个版本即可
> > 是的。 Layotto和mosn是一个进程，可以理解成 layotto=mosn+一个特殊的grpcfilter 打包到一起, 升级 layotto == 升级mosn layotto和mosn 的版本是一一对应的关系，之前发布的v0.3.0的layotto对应的mosn版本为 v0.24.1 所以：如果使用了 layotto，sidecar镜像里指定layotto的一个版本即可，不用另外再指定 mosn 版本
> > ## layotto和mosn的版本的升级怎么搞？
> > 用k8s部署、升级，升级sidecar镜像里的 layotto版本即可
> > ## layotto升级是否有无损的方案？
> > 有，升级 layotto == 升级mosn，mosn 支持平滑升级，做长连接迁移，见 https://mosn.io/docs/concept/smooth-upgrade/
> > 不过这种方式需要通过发信号的方式在本机做平滑升级，或者开发定制的 Operator
> 
> 具体怎么发送这个信号？

**Comment by seeflood** [comment]
@unionhu 可以看下这篇用 OpenKruise 做原地热升级的分享
https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/
