### ISSUE TITLE
mosn 是否支持将请求转发到 自定义 ip 和 自定义路径

### ISSUE THREAD

**Issue by greedying** [mosn/mosn#1986]
### Your question

假设 mosn 收到的请求是 `http://mosn.server.com/a`。
在我私有逻辑里面，把 `a` 映射成了 `http://1.2.3.4:500/b`。
通过 [issue 1548](https://github.com/mosn/mosn/issues/1548)  我找到了 1.2.3.4 这个 ip 的设置方法。
但是没有找到 端口 500 和 路径 `/b` 的设置方法。
请问有办法在转发的时候自定义完整的 `url` 吗?

### Environment

- MOSN Version
v0.26.0

### Logs

- Paste the logs you see.
无

**Comment by taoyuanyuan** [comment]
@greedying  如果你自己的逻辑很复杂，那直接可以写个filter，然后修改变量就行了哈，跟ip类似的处理哈
https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/stream/http/stream.go#L939
这篇文章是讲router的，你也可以看看 https://mosn.io/blog/posts/how-use-dynamic-metadata/
通过变量，可以支持很多复杂的业务。

**Comment by taoyuanyuan** [comment]
@greedying 你这个述求，光用配置就能搞定哈
https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/config/v2/route.go#L64
`prefix_rewrite` 和 `regex_rewrite`

**Comment by greedying** [comment]
> 

配置应该不够。我这里的对应关系很多，而且是可能随时变动的。

**Comment by greedying** [comment]
> @greedying 如果你自己的逻辑很复杂，那直接可以写个filter，然后修改变量就行了哈，跟ip类似的处理哈
> 
> https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/stream/http/stream.go#L939
> 
> 
> 这篇文章是讲router的，你也可以看看 https://mosn.io/blog/posts/how-use-dynamic-metadata/
> 通过变量，可以支持很多复杂的业务。

你好。这篇文章我看过，我理解里面的方法，是动态的确定 `cluster`，也就是说配置里面，需要先有 `cluster`配置才行。

修改变量是怎么修改的？哪儿能看到例子吗？谢谢。

**Comment by taoyuanyuan** [comment]
> > @greedying 如果你自己的逻辑很复杂，那直接可以写个filter，然后修改变量就行了哈，跟ip类似的处理哈
> > https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/stream/http/stream.go#L939
> > 
> > 这篇文章是讲router的，你也可以看看 https://mosn.io/blog/posts/how-use-dynamic-metadata/
> > 通过变量，可以支持很多复杂的业务。
> 
> @taoyuanyuan 你好。这篇文章我看过，我理解里面的方法，是动态的确定 `cluster`，也就是说配置里面，需要先有 `cluster`配置才行。
> 
> 修改变量是怎么修改的？哪儿能看到例子吗？谢谢。

你可以看看这个 https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/router/base_rule.go#L289
方法是类似的，你写一个filter，按照你的要求去设置变量 `variable.SetString(ctx, types.VarPath, rewritedPath)`

**Comment by greedying** [comment]
> > > @greedying 如果你自己的逻辑很复杂，那直接可以写个filter，然后修改变量就行了哈，跟ip类似的处理哈
> > > https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/stream/http/stream.go#L939
> > > 
> > > 这篇文章是讲router的，你也可以看看 https://mosn.io/blog/posts/how-use-dynamic-metadata/
> > > 通过变量，可以支持很多复杂的业务。
> > 
> > 
> > @taoyuanyuan 你好。这篇文章我看过，我理解里面的方法，是动态的确定 `cluster`，也就是说配置里面，需要先有 `cluster`配置才行。
> > 修改变量是怎么修改的？哪儿能看到例子吗？谢谢。
> 
> 你可以看看这个
> 
> https://github.com/mosn/mosn/blob/71803ed3fa533f924ba437a99d37c8f75e4750f0/pkg/router/base_rule.go#L289
> 
> 
> 方法是类似的，你写一个filter，按照你的要求去设置变量 `variable.SetString(ctx, types.VarPath, rewritedPath)`

我直接在官方的 [simple_filter 示例](https://github.com/mosn/mosn/blob/master/examples/codes/mosn-extensions/simple_streamfilter/simple.go) 中加了这么两行代码
```golang
	variable.SetString(ctx, types.VarPath, "/a/b/c")
	variable.SetString(ctx, types.VarHost, "1.2.3.4:5678")
	return api.StreamFilterContinue
```

预期会转发到 `http://1.2.3.4:5678/a/b/c`,  实际上仍然是转发到了 `127.0.0.1:8080`。
我查了下 `api.stream_filter.go` 的代码，接口只定义了 `OnDestroy` 和 `OnReceive` 两个方法，没有我想象中的
`BeforeRoute` 和 `AfterRoute` 方法。
麻烦再帮忙看一下我哪儿理解有误，非常感谢。
有知识星球我也可以加一下

**Comment by taoyuanyuan** [comment]
是这样的哈，`variable.SetString(ctx, types.VarHost`塞的只是host头，真正修改转发的ip还是需要 https://github.com/mosn/mosn/issues/1548 这个方法。
你可以加我微信，我拉你  wx：poooint

**Comment by greedying** [comment]
> 是这样的哈，`variable.SetString(ctx, types.VarHost`塞的只是host头，真正修改转发的ip还是需要 #1548 这个方法。 你可以加我微信，我拉你 wx：poooint

好的，谢谢。已加。
我还有两个问题。
1. #1548 需要插 header 头，这个 头是插入的用户的 header 头吗？有没有例子
 我在 `OnReceive` 中使用 `headers.Set('host', 'xxx')` 好像也没用。
2. 即使 `host` 问题解决了，`path`  好像没有办法使用相同方法修改？
3.

**Comment by taoyuanyuan** [comment]
@greedying 
1. 通过headers.Set就可以了
2. path就用变量就行了， `variable.SetString(ctx, types.VarPath, "/a/b/c")`, 变量修改的是请求的报文， 然后header修改的是真实的转发ip， 其实这个header也应该用变量来做，还没来得及。

**Comment by taoyuanyuan** [comment]
代码
```
	variable.SetString(ctx, types.VarPath, "/abc")
	headers.Add("host", "127.0.0.1:8081")
```

配置
```
{
    "servers":[
        {
            "default_log_path":"stdout",
            "default_log_level": "DEBUG",
            "routers":[
                {
                    "router_config_name":"router1",
                    "virtual_hosts":[
                        {
                            "domains": ["*"],
                            "routers": [
                                {
                                    "match":{
                                        "prefix":"/"
                                    },
                                    "route": {
                                       "cluster_name": "cluster"
                                    }
                                }
                            ]
                        }]
                },
                {
                    "router_config_name":"router2",
                    "virtual_hosts":[
                        {
                            "domains": ["*"],
                            "routers": [
                                {
                                    "match":{
                                        "prefix":"/"
                                    },
                                    "direct_response":{
                                        "status":200,
                                        "body":"Hello MOSN!"
                                    }
                                }
                            ]
                        }]
                }
            ],
            "listeners":[
                {
                    "name":"Listener1",
                    "address": "127.0.0.1:8080",
                    "bind_port": true,
                    "filter_chains": [
                        {
                            "filters": [
                                {
                                    "type": "proxy",
                                    "config": {
                                        "downstream_protocol": "Auto",
                                        "upstream_protocol": "Auto",
                                        "router_config_name":"router1"
                                    }
                                }
                            ]
                        }],
                    "stream_filters": [
                        {
                            "type":"demo"
                        }
                    ]
                },
                {
                    "name":"Listener2",
                    "address": "127.0.0.1:8081",
                    "bind_port": true,
                    "filter_chains": [
                        {
                            "filters": [
                                {
                                    "type": "proxy",
                                    "config": {
                                        "downstream_protocol": "Auto",
                                        "upstream_protocol": "Auto",
                                        "router_config_name":"router2"
                                    }
                                }
                            ]
                        }]
                }
            ]
        }
    ],
    "cluster_manager":{
         "clusters":[
            {
              "Name":"cluster",
              "type": "SIMPLE",
              "lb_type": "LB_ORIGINAL_DST",
              "max_request_per_conn": 1024,
              "conn_buffer_limit_bytes":32768,
              "original_dst_lb_config": {
                 "use_header": true,
                 "header_name": "host"
              }
            }
         ]
     },
    "admin": {
        "address": {
            "socket_address": {
                "address": "0.0.0.0",
                "port_value": 34901
            }
        }
    } ,
    "pprof": {
        "debug": true,
        "port_value": 44902
    }
}

```

**Comment by greedying** [comment]
多谢，这样可以实现了
