### ISSUE TITLE
自定义配置是怎么获取的

### ISSUE THREAD

**Issue by greedying** [mosn/mosn#1995]
### Your question

看到 mosn 有自定义配置，点开文档，发现好像内容是错误的？
看了下代码，自定义配置，是支持传入自定义解析函数的。
但是没找到，怎么取出自定义配置。

```
	"extends": [
		{
			"type": "abc",
			"config": "config string"
		}
	]
```

如上图，我写了一个自定义配置。
后面希望在一个单独的进程里面读取 abc 的 config，做一些操作
请问我需要调用哪个函数来完成这件事？

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
https://github.com/mosn/mosn/blob/8d976811c04076059b0bd5df1124c154832d1144/pkg/upstream/servicediscovery/dubbod/bootstrap.go#L53
可以看这个例子，你可以用 RegisterParseExtendConfig 注册一个key，配置解析的时候就会调用你的handler，去做你想做的事，比如你可以启动一个协程干啥来着

**Comment by greedying** [comment]
谢谢回复。这英嘎就是我说的支持传入自定义函数的方式。

这里是说我只能通过这种方式，自己把配置找个地方存一下对吧。
后续没法使用类似 ` configManager.GetExtend("dubbo_registry")` 的方式获取这个配置

**Comment by taoyuanyuan** [comment]
> 

目前不行，欢迎 PR ~

**Comment by greedying** [comment]
![image](https://user-images.githubusercontent.com/7993339/160992471-0226219e-965a-4f35-8b35-b9ed1dcdc2e2.png)

感觉代码中的例子，和实际结构不太一样

**Comment by greedying** [comment]
> > 
> 
> 目前不行，欢迎 PR ~

我再熟悉一下代码，后续试一下

**Comment by greedying** [comment]
好的，这样也够用。
