### ISSUE TITLE
test: TestDynamicClusterUpdateHosts may failure randomly in CI.

### ISSUE THREAD

**Issue by doujiang24** [mosn/mosn#2012]
maybe we can choose another domain instead of `www.baidu.com`?

error message:
```
=== RUN   TestDynamicClusterUpdateHosts
Error:     strict_dns_cluster_test.go:89: [upstream][static_dns_cluster] Address www.baidu.com:80 not resolved.
--- FAIL: TestDynamicClusterUpdateHosts (7.35s)
```

![image](https://user-images.githubusercontent.com/570391/163535342-1d212e36-c9f0-4e7a-8de5-4403376af376.png)

**Comment by doujiang24** [comment]
maybe it's better to mock it, in this way: https://github.com/mosn/mosn/blob/c9ca4325a175814e5e37e94f05c48b7428caf98c/pkg/upstream/cluster/strict_dns_cluster_test.go#L173

**Comment by songzhibin97** [comment]
assign to me
