### ISSUE TITLE
关于MoE示例文档的一些疑问

### ISSUE THREAD

**Issue by MengJiapeng** [mosn/mosn#2015]
### Your question

[MOE的示例文档](https://github.com/mosn/mosn/blob/master/pkg/networkextention/README-cn.md)

1. 在文档中，通过配置`envoy.filters.http.golang`这个filter实现了envoy对MOSN七层流量治理能力的复用，请问这个filter本身的代码实现在哪里可以看到呢？
2. 除了复用stream filter，是否也支持复用network filter？

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by antJack** [comment]
1. envoy filter 目前还没开源
2. 这个内部已经在用了，我们今年就会开源，连同 envoy 侧的都会一起开的

**Comment by MengJiapeng** [comment]
好的，谢谢
