### ISSUE TITLE
trace 的插件化

### ISSUE THREAD

**Issue by YIDWang** [mosn/mosn#2037]
## 现状介绍
当前 Trace 主要拆分为 Driver ，Tracer，Span 三个对象进行管理。

- Driver 负责从协议为度管理Tracer 对象，当请求被劫持时刻，当前流会根据协议从 Driver 中获取对应 Tracer 对象。其中 Driver 与 Tracer 为解耦合关系，二者通过 协议名字和 TracerBuilder 注册到 Driver 中。
- Tracer 负责管理和创建 span ，Tracer 可以初始化当前依赖的信息，每个协议需要一个Tracer 对象。
- Span 数据记录的最小单位，会为每一个流程创建一个  Span。

![image](https://user-images.githubusercontent.com/20499178/170493791-c79b2b2b-9905-4ca0-8548-e753c879a96c.png)

## 扩展接口
通过上述介绍了解到 Driver 和 TracerBuilder 是结耦合关系 ，mosn trace 的插件话的以 Driver  或者 以 TracerBuilder 两个方面做。
### Driver 插件话
基于 driver 的扩展主要可以用于：

1. 自定义管理 TracerBuilder 的初始化（例如当前实现的 skywaking 方式）
2. Tracer 的维度管理（当前是以协议为维度，用户也可以以全局一个做扩展）
```
type Driver interface {
	Init(config map[string]interface{}) error

	Register(proto ProtocolName, builder TracerBuilder)

	Get(proto ProtocolName) Tracer
}
```
#### 缺陷

- driver 只能给特定的场景使用，例如 skywaking 只能满足 skywaking 的 场景。

### TracerBuilder 插件话
基于 TracerBuilder 的扩展主要用于：

1. Span 的个性化创建，当前 skywaking、sofa、zipkin 都是需要这种能力。
2. Tracer 自身的初始化：其实可以 skywaking 中 driver 定制化能力迁移到 Tracer 去实现。

#### 缺陷

-  builder 需要实现协议无关。

## 实现方案
本次 pr 主要满足多样的 TracerBuilder 创建。例如 skywaking、zipkin、sofa。用户只需要实现 TracerBuilder 插件的扩展即可以完成对应 tracer 系统的接入。 
插件需要实现 TracerBuilder 函数保证服务正确加载。
```
type TracerBuilder func(config map[string]interface{}) (Tracer, error)
```
业务需要根据需求正确的编写 Tracer 和 Span 对象。其中 Tracer 是启动创建 tracer 对象，可以用来初始化全局信息。Span 是根据流创建，一个 stram 搭配一个 span。

### 约束
- builder 需要做协议无关，支持各种协议的解析。
- builder 需要实现收集服务的初始化。

```
type Tracer interface {
	Start(ctx context.Context, request interface{}, startTime time.Time) Span
}
type Span interface {
	TraceId() string

	SpanId() string

	ParentSpanId() string

	SetOperation(operation string)

	SetTag(key uint64, value string)

	SetRequestInfo(requestInfo RequestInfo)

	Tag(key uint64) string

	FinishSpan()

	InjectContext(requestHeaders HeaderMap, requestInfo RequestInfo)

	SpawnChild(operationName string, startTime time.Time) Span
}
```

### 加载流程

![image](https://user-images.githubusercontent.com/20499178/170501233-e282fd4c-9401-4b52-b102-4b803511c4e0.png)

- 当前创建流程为 1-> 2 -> 3-> 4 -> 5
- 插件加载流程为 1->2*->3*->4*->5*

备注：虚线箭头表示当前协议加载 tracer 加载流程，黄色框表示插件加载流程，也是本次加在的流程

### 核心 code 修改
- 实现 PluginDriver 负责管理 so 对象。
- 提供 skywalking 实现demo。

**Comment by doujiang24** [comment]
closing since https://github.com/mosn/mosn/pull/2047 is merged.
