### ISSUE TITLE
Support record state attachments in host

### ISSUE THREAD

**Issue by jizhuozhi** [mosn/mosn#2038]
### The New Feature

Support record state attachments in host

### Your scenes

Host is stateful and now I need to record another state into host, so that I could implement some algorithm which depends on the post responses.

### Your advice

Add `GetState(string) interface{}` and `SetState(string, interface{})` methods to `Host` interface.

### Environment

- MOSN Version

**Comment by jizhuozhi** [comment]
> https://github.com/mosn/mosn/blob/4f3eda59bfb1e44b1fc97c04a1411e703ac71b43/pkg/upstream/cluster/host.go#L71
> 
> 
> Maybe we could add a new func `SetMetadata`， and using metadata to record status.

As I know, `Metadata` is of  type `map[string]string`, but lots of state is of type numeric, this will take more conversion steps

**Comment by nejisama** [comment]
Metadata是host的配置属性，不适合用来做运行时的状态存储。看这个需求更像是需要记录相关的metrics数据

**Comment by nejisama** [comment]
或者更类似Resource数据（目前用于记录熔断数据）

**Comment by nejisama** [comment]
这里主要有一个问题，就是自定义的扩展数据结构，在什么地方记录。
比如metrics/resource 等数据，都是有固定的地方记录的。 扩展一个state，在哪里可以进行记录不确定，应该也是需要额外写filter来做保存的，如果额外做filter保存的话，是不是直接在filter里记录数据就可以了？这里没有想好

**Comment by jizhuozhi** [comment]
> Metadata是host的配置属性，不适合用来做运行时的状态存储。看这个需求更像是需要记录相关的metrics数据

Not only host-related metrics that can be obtained in LoadBalancer, but also some contents other than metrics, such as dynamically updated weight

**Comment by nejisama** [comment]
> > 这里主要有一个问题，就是自定义的扩展数据结构，在什么地方记录。 比如metrics/resource 等数据，都是有固定的地方记录的。 扩展一个state，在哪里可以进行记录不确定，应该也是需要额外写filter来做保存的，如果额外做filter保存的话，是不是直接在filter里记录数据就可以了？这里没有想好
> 
> Use filter to write or update status of host, and read the status in LoadBalancer, then way we can do a heuristic load balancing strategy

Use filter to write or update status of host -> So the status information and host mapping are also recorded directly in the filter ？

**Comment by jizhuozhi** [comment]
> > > 这里主要有一个问题，就是自定义的扩展数据结构，在什么地方记录。 比如metrics/resource 等数据，都是有固定的地方记录的。 扩展一个state，在哪里可以进行记录不确定，应该也是需要额外写filter来做保存的，如果额外做filter保存的话，是不是直接在filter里记录数据就可以了？这里没有想好
> > 
> > 
> > Use filter to write or update status of host, and read the status in LoadBalancer, then way we can do a heuristic load balancing strategy
> 
> Use filter to write or update status of host -> So the status information and host mapping are also recorded directly in the filter ？

I still think the status information should be recorded in the `Host` instance like `Metadata` but a generic type and mutable. It seems an anti-pattern that LoadBalancer depends on filters. If no filter set, LoadBalancer can read from `Host` instance and use default value, but if LoadBalancer depends on filters, how does it know which filter used and holds on the status information?

**Comment by nejisama** [comment]
> > > > 这里主要有一个问题，就是自定义的扩展数据结构，在什么地方记录。 比如metrics/resource 等数据，都是有固定的地方记录的。 扩展一个state，在哪里可以进行记录不确定，应该也是需要额外写filter来做保存的，如果额外做filter保存的话，是不是直接在filter里记录数据就可以了？这里没有想好
> > > 
> > > 
> > > Use filter to write or update status of host, and read the status in LoadBalancer, then way we can do a heuristic load balancing strategy
> > 
> > 
> > Use filter to write or update status of host -> So the status information and host mapping are also recorded directly in the filter ？
> 
> I still think the status information should be recorded in the `Host` instance like `Metadata` but a generic type and mutable. It seems an anti-pattern that LoadBalancer depends on filters. If no filter set, LoadBalancer can read from `Host` instance and use default value, but if LoadBalancer depends on filters, how does it know which filter used and holds on the status information?

Your information relies on the filter to record. Without the filter, there is no data.
 If it is implemented in the host, then there is no good way to record these extended data except for the filter

**Comment by nejisama** [comment]
" If no filter set, LoadBalancer can read from Host instance and use default value" -> no filters, no value(default value).
I think the requirements here should not simply be regarded as a load balancing implementation, but an overall functional module, including filter, lb, etc.

**Comment by nejisama** [comment]
Adding information in the Host should do some general data similar to resource/metrics, so that it can be counted/obtained uniformly.
There is really no way to identify any type of data stored directly in the host. If it is fixed configuration information, metadata can be used instead.

**Comment by jizhuozhi** [comment]
> " If no filter set, LoadBalancer can read from Host instance and use default value" -> no filters, no value(default value). I think the requirements here should not simply be regarded as a load balancing implementation, but an overall functional module, including filter, lb, etc.

Yes, it's impactful, it provides a mechanism for sharing instance side effects across multiple components, like `Context`

**Comment by jizhuozhi** [comment]
> Adding information in the Host should do some general data similar to resource/metrics, so that it can be counted/obtained uniformly. There is really no way to identify any type of data stored directly in the host. If it is fixed configuration information, metadata can be used instead.

I will try other solutions
