### ISSUE TITLE
连接的读超时时间是不是统一一下比较好

### ISSUE THREAD

**Issue by fibbery** [mosn/mosn#2050]
https://github.com/mosn/mosn/blob/448da0ebe3555eec02822f890ca2682ac052d773/pkg/server/handler.go#L654
上面这个buffer.ConnReadTimeout是不是统一用下面的连接读超时时间替换比较好，不然感觉挺割裂的
https://github.com/mosn/mosn/blob/448da0ebe3555eec02822f890ca2682ac052d773/pkg/types/network.go#L192

**Comment by taoyuanyuan** [comment]
PR welcome ~

**Comment by fibbery** [comment]
好，分给我，我处理一下

**Comment by taoyuanyuan** [comment]
thank you ~
