### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by chenzhiguo** [mosn/mosn#2068]
### Describe the bug

Can't build the project.

### Actual behavior
```bash
go: downloading github.com/opentrx/seata-golang/v2 v2.0.4
go: github.com/opentrx/seata-golang/v2@v2.0.4 requires
        github.com/go-xorm/xorm@v0.7.9: reading github.com/go-xorm/xorm/go.mod at revision v0.7.9: git ls-remote -q origin in /Users/chenzhiguo/go/pkg/mod/cache/vcs/516cff95263076be8ff66fbbae295f8235963b00c4f114bcea50f99a51def272: exit status 128:
        remote: Repository `go-xorm/xorm' is disabled.
        remote: Please ask the owner to check their account.
        fatal: unable to access 'https://github.com/go-xorm/xorm/': The requested URL returned error: 403
```
### Steps to reproduce
```bash
go mod tidy
```

### Environment
On macOS M1 Pro

- MOSN Version  master

**Comment by nejisama** [comment]
this tag is exists, see https://github.com/go-xorm/xorm/releases/tag/v0.7.9
it looks like your github configuration have some errors

**Comment by chenzhiguo** [comment]
> this tag is exists, see https://github.com/go-xorm/xorm/releases/tag/v0.7.9 it looks like your github configuration have some errors
https://github.com/go-xorm/xorm/releases/tag/v0.7.9 这个项目被归档了，403访问被拒绝...

**Comment by chenzhiguo** [comment]
原因是我使用的goproxy代理有问题，使用GOPROXY=https://proxy.golang.com.cn,direct会报上面错误。
修改为：GOPROXY=https://goproxy.cn,direct 就可以了。
坑死我了！
