### ISSUE TITLE
Support for istio latest 1.15.x version

### ISSUE THREAD

**Issue by AtticusLv** [mosn/mosn#2126]
### The New Feature

istio does not support 1.10.6 version and CVEs. Seak for support for upgrading to latest istio

### Your scenes

Use MOSN as sidecar injection with istio latest 1.15.x version.

### Your advice

Wish MOSN providing the latest building package with istio 1.15.x

### Environment

- MOSN Version: lastest master branch

**Comment by AtticusLv** [comment]
is this project still maintained?

seem like nobody is maintaining

**Comment by nejisama** [comment]
We currently have no plans to upgrade MOSN to the istio version.  If you are interested in upgrading MOSN to istio 1.15, welcome to contribute code
