### ISSUE TITLE
Is there any demo or implementation that mosn deployed as Per-Node ? 

### ISSUE THREAD

**Issue by welsper-yang** [mosn/mosn#2162]
As title

**Comment by alpha-baby** [comment]
> As title

there is many demo: https://github.com/mosn/mosn/tree/master/examples/codes

**Comment by doujiang24** [comment]
Does `Per-Node` mean no sidecar?

**Comment by welsper-yang** [comment]
> Does `Per-Node` mean no sidecar?

yeah, just like istio ambient or cilium service mesh, there is only a shared enovy for each node. Does mosn support such deployment mode currently?

**Comment by doujiang24** [comment]
No demo yet.

Per-Node thing does not matter to MOSN as a proxy platform. You need to care about the independent configurations in the sidecar, after deploy as Per-Node.
