### ISSUE TITLE
无用的代码

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#2211]
https://github.com/mosn/mosn/blob/431317f0ff511f2ac273ac61d005408c0d9f1137/pkg/upstream/cluster/loadbalancer.go#L448

chosen 变量如果在这里为空了，那么在这里会 panic

https://github.com/mosn/mosn/blob/431317f0ff511f2ac273ac61d005408c0d9f1137/pkg/upstream/cluster/loadbalancer.go#L444

**Comment by nejisama** [comment]
这看上去是两个不同的chosen？

**Comment by alpha-baby** [comment]
> 这看上去是两个不同的chosen？

我又看了下，确实是不一样的，忽略
