### ISSUE TITLE
warnings about proxy_on_delete for proxy_abi_version_0_1_0

### ISSUE THREAD

**Issue by codefromthecrypt** [mosn/mosn#2238]
### Describe the bug

You can see running `TestProxyWasmStreamFilterGo` errors like this.

```
2023-02-21 09:55:09,947 [ERROR] [proxywasm][filter] OnDestroy fail to call ProxyOnDelete, err: [wazero][instance] GetExportsFunc unknown func proxy_on_delete
```

This is due to the wasm not exporting a function `proxy_on_delete`, e.g. ./pkg/filter/stream/proxywasm/data/test-go.wasm

There's no tag around when things were added to the spec, as everything is a single commit: https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#proxy_on_delete

As this is about an old ABI, I think the choice is to ignore the fact that errors are in the log or get rid of them for the proxy_abi_version_0_1_0 spec. It would be nice to have no errors as they confuse when looking to see if any regressions occur on update.

### Expected behavior

Expected no errors in the log.

### Actual behavior

```
2023-02-21 09:55:09,947 [ERROR] [proxywasm][filter] OnDestroy fail to call ProxyOnDelete, err: [wazero][instance] GetExportsFunc unknown func proxy_on_delete
```

### Steps to reproduce

You can see running `TestProxyWasmStreamFilterGo` errors like this.

### Minimal yet complete reproducer code (or GitHub URL to code)

You can see running `TestProxyWasmStreamFilterGo` errors like this.

### Environment

- MOSN Version - master branch

**Comment by doujiang24** [comment]
@antJack Could you take look at this issue? Thanks.

**Comment by antJack** [comment]
just ignore it or lower the log level to warn?

**Comment by codefromthecrypt** [comment]
lower to warn is better than having people ignore error. I'll raise a PR. Thanks!
