### ISSUE TITLE
go import error

### ISSUE THREAD

**Issue by PrinceHatty** [mosn/mosn#2243]
### Describe the bug

go: mosn.io/mosn: unrecognized import path "mosn.io": parse https://mosn.io/?go-get=1: no go-import meta tags ()

### Environment

- MOSN Version

**Comment by doujiang24** [comment]
@PrinceHatty Thanks for your report, could you please paste the command to reproduce this error?

It may be an invalid command or usage.

**Comment by PrinceHatty** [comment]
Just close the issue I fixed it.
