### ISSUE TITLE
 Some linter rules are too strict

### ISSUE THREAD

**Issue by jizhuozhi** [mosn/mosn#2256]
### Your question

In PR https://github.com/mosn/mosn/pull/2253#discussion_r1141576567, there is a rule `ireturn` (accept interfaces, return concrete structs), which requires all constructors of `loadbalancer` to return concrete types instead of interfaces, but because all factory patterns only accept registration methods that return interfaces. 

So this rule cannot be fixed, should we consider letting go of this rule?

**Comment by doujiang24** [comment]
yep, I think we can disable the `ireturn` golint.

**Comment by doujiang24** [comment]
Could you please try to disable it? another PR should be fine.

**Comment by 3062** [comment]
The two functions newRandomLoadBalancer and newReqRoundRobinLoadBalancer don't report an error, just because the return is written differently?

**Comment by jizhuozhi** [comment]
> The two functions newRandomLoadBalancer and newReqRoundRobinLoadBalancer don't report an error, just because the return is written differently?

It's reported, see
https://github.com/mosn/mosn/actions/runs/4446019460/jobs/7805831517?pr=2253#step:3:1841 and https://github.com/mosn/mosn/actions/runs/4446019460/jobs/7805831517?pr=2253#step:3:1847

**Comment by 3062** [comment]
> > The two functions newRandomLoadBalancer and newReqRoundRobinLoadBalancer don't report an error, just because the return is written differently?
> 
> Hello, @3062 . It's reported, see https://github.com/mosn/mosn/actions/runs/4446019460/jobs/7805831517?pr=2253#step:3:1841 and https://github.com/mosn/mosn/actions/runs/4446019460/jobs/7805831517?pr=2253#step:3:1847
OK, maybe I asked a stupid question

**Comment by jizhuozhi** [comment]
> Could you please try to disable it? another PR should be fine.

@doujiang24 Completed, see #2259 :)
