### ISSUE TITLE
健康检查存在goroutine泄漏风险

### ISSUE THREAD

**Issue by yejialiango** [mosn/mosn#2282]
pkg/upstream/healthcheck/session_checker.go:63

session_checker.Start()中，会有两个阻塞的地方，
![image](https://user-images.githubusercontent.com/43239328/229960358-5872e71c-686c-4402-8ed6-4c68f0c2ce69.png)

阻塞中，如果集群更新了Host，比如strict_dns_cluster DNS解析结果有变化，会触发remove old host healthcheck，此时发送 stop，这里的select就会跳出：
![image](https://user-images.githubusercontent.com/43239328/229960603-17be5761-8fe7-43f7-abec-fa07470fa271.png)

也就是说，跳出之后，原来发送 timeout和c.resp channel的 goroutine就一直得不到释放，随着 remove oldHost healthcheck变多，goroutine就会慢慢增多

**Comment by yejialiango** [comment]
https://github.com/yejialiango/mosn/tree/bugfix/sessionchecker_goroutine_leakage
我这种修改方式可以吗？我的想法是把OnCheck改成同步执行，不通过channel传递执行状态

**Comment by doujiang24** [comment]
@yejialiango 多谢反馈，建议搞个 PR，方便 review 讨论

**Comment by yejialiango** [comment]
ok，我提一个

**Comment by jizhuozhi** [comment]
与 #2336 重复了，之后的讨论都移步到 #2336 吧
