### ISSUE TITLE
Why sending xds request periodically in sendRequestLoop?

### ISSUE THREAD

**Issue by 123liuziming** [mosn/mosn#2293]
![image](https://user-images.githubusercontent.com/32130965/232283670-8226ef32-7e0e-431e-8ed1-b6b4cfbe8665.png)
为什么在Mosn中需要定时地去发送xds请求呢？直接在receiveResponseLoop中去等待istio推送配置到Mosn会有什么问题呢？

**Comment by wangfakang** [comment]
是为了在和 pilot 服务端因为某种原因链接断开后，相关 xds 依然可以继续重新更新。比如 pilot 服务端升级或者 idle timeout 等等。

**Comment by 123liuziming** [comment]
貌似envoy不是采用轮询的办法来维护与Pilot的连接的，envoy在pilot服务器因为某种原因断开连接后会出现上述问题吗？

**Comment by wangfakang** [comment]
Envoy 中是采用断连事件的方式来处理的，相关代码如下所示，最终效果和 MOSN 类似。
https://github.com/envoyproxy/envoy/blob/main/source/common/config/grpc_stream.h#L27-L37
https://github.com/envoyproxy/envoy/blob/main/source/common/config/grpc_stream.h#L100-L106

**Comment by 123liuziming** [comment]
明白了，感谢！

**Comment by 123liuziming** [comment]
还有一个问题，Mosn中是严格按照CDS->EDS->LDS->RDS的顺序来更新配置的，但是在Envoy里面貌似CDS和LDS是独立进行更新的，即分为CDS->EDS以及LDS->RDS来更新，在这一块Mosn和Envoy的区别在哪呢

**Comment by wangfakang** [comment]
CDS 肯定是在 LDS 之前更新的，否则 LDS 中指向一个新的 cluster ，而对应的 cluster 都还没加入，那请求必然失败。
https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#eventual-consistency-considerations

**Comment by 123liuziming** [comment]
https://github.com/envoyproxy/envoy/issues/26775 我在envoy的代码里面没找到CDS和LDS的顺序关系，问envoy社区的同学他们说这俩在运行时是独立的

**Comment by wangfakang** [comment]
Envoy 目前只是在启动初始化流程控制了 cluster 和 listener 的顺序，在运行时的 ADS 下的确没有控制。如上面[文档](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#eventual-consistency-considerations)提到到需要用户在更新配置的时候保持 cds 和 lds 顺序，既 virtualservice、destinationrule 等相关 CRD 顺序。

**Comment by 123liuziming** [comment]
还有一个疑问，我看Mosn去轮询的请求时间间隔挺短的，对于网关来说配置的更新可能并不是一个频率这么高的动作，这么频繁地去发送xds并且去解析xds的response会不会对Mosn的性能造成影响？

**Comment by wangfakang** [comment]
> 

这个本意并不是轮训，MOSN 里面也是使用的 grpc 通道，istiod 服务端可以主动 push 的。上面的周期性发送主要是为了解决断连以及均衡性等问题（如上面提到的）。另外这个周期默认是 10s，当然也是可以根据实际场景通过 `RefreshDelay` l来配置。

**Comment by 123liuziming** [comment]
我明白，但是本质上还是一直在发送与处理xds，像envoy的实现方式是只有出现连接断开的时候才会去尝试重连，Mosn貌似是一直去做这个事情

**Comment by wangfakang** [comment]
对，这个理论上也可以增加一个类似 grpc stream 断链的 callback 回调是可以优化的，欢迎贡献 PR哈。

**Comment by 123liuziming** [comment]
> 对，这个理论上也可以增加一个类似 grpc stream 断链的 callback 回调是可以优化的，欢迎贡献 PR哈。

非常感谢！！！
