### ISSUE TITLE
Support recording client errors and server errors on the L7 protocol

### ISSUE THREAD

**Issue by jizhuozhi** [mosn/mosn#2295]
### The New Feature

I want the stats of hosts supprt recording client errors (4xx in HTTP) and server errors (5xx in HTTP) on the L7 protocol.

### Your scenes

Currently the L7 response simply records success and failure, but there are different types of errors in L7 protocol (the HTTP protocol is well defined).
https://github.com/mosn/mosn/blob/92f428f1255a9ae0622beaf4fb11812ad5d93d23/pkg/types/upstream.go#L281-L282

I am currently implementing a latency based load balancing algorithm #2252 , but I'm facing a sticky problem now.

Latency-based load balancing algorithms are all based on the premise that the cost of processing requests is the same. But as we all know, user input is untrustworthy, and all backend services will verify user (or other service) input, and once the verification fails, the request will not be processed and the result will be returned quickly, which will lead to The load balancing algorithm gets a wrong view: this request is processed very quickly.

$$
\begin{align}
Avg &= \sum_{i=1}^{n}Duration_i / TotalCount \\
       &= (\sum_{i=1}^{SuccessCount}SuccessDuration_i + \sum_{i=1}^{FailedCount}FailedDuration_i) / TotalCount \\
        &\approx \sum_{i=1}^{SuccessCount}SuccessDuration_i / TotalCount \\
        &\ll \sum_{i=1}^{SuccessCount}SuccessDuration_i / SuccessCount
\end{align}
$$

We need a mathematical model to fix this wrong view. One of the easiest ways to do this is to fix all response times to the same value as the `SuccessDuration`

$$
\begin{align}
FixedAvg &= Avg / \alpha \\
\sum_{i=1}^{SuccessCount}SuccessDuration_i / SuccessCount &= \sum_{i=1}^{SuccessCount}SuccessDuration_i / TotalCount / \alpha \\
SuccessCount &= \alpha TotalCount \\
\alpha &= SuccessCount / TotalCount \\
\alpha &= SuccessRate
\end{align}
$$

But now client errors are included in $SuccessCount$.

### Your advice

It seems that we only need to record the failed requests count include client errors to solve the problem? 

In fact, different errors have different bias for the final score. The client error is only due to the abnormal behavior of the user. In fact, the host has no performance problems, but the server error is different. It means that there is a real problem with the host. If the request is sent to it again, it will seriously affect the quality of service.

So we'd better be able to split the two metrics, and be able to set different bias when doing circuit breakers and load balancing algorithms in the future

### Environment

- MOSN Version

**Comment by jizhuozhi** [comment]
This problem is also described in *["The Site Reliability Workbook: Practical Ways to Implement SRE"](https://www.amazon.com/Site-Reliability-Workbook-Practical-Implement/dp/1492029505)*. When the resource-based load balancing algorithm encounters fail-fast, severe traffic skew will occur.

**Comment by doujiang24** [comment]
Nice catch, your advice looks good to me, this could be an improvement of https://github.com/mosn/mosn/issues/2252 , not a blocker.

**Comment by doujiang24** [comment]
Nice catch, your advice looks good to me, this could be an improvement of https://github.com/mosn/mosn/issues/2252 , not a blocker.

**Comment by jizhuozhi** [comment]
Because different errors have different reference meanings for load balancing, the revised formula can be changed. 

Since the client error is caused by the wrong behavior of the user, it basically has no impact on the system, so we can simply ignore this part of the request, but the server error is different, because the server really has an error, so the load balancing must avoid giving it sends traffic. 

So the calculation formula has changed a little, where `ClientErrorBias` and `ServerErrorBias` are configurable

$$
\begin{align}
alpha &= SuccessCount / TotalCount \\
          & = 1 - ClientErrorCount / TotalCount - ServerErrorCount / TotalCount \\
=> alpha &= 1 - (ClientErrorCount / TotalCount) ^ {ClientErrorBias} -  (ServerErrorCount / TotalCount) ^ {ServerErrorBias }
\end{align}
$$

cc @rayowang , what do you think of this solution
