### ISSUE TITLE
需要移除proxy默认的route handler name

### ISSUE THREAD

**Issue by fibbery** [mosn/mosn#2307]
目前现状：
https://github.com/mosn/mosn/blob/80f7fa46133ba669137dc0184440463487eb3019/pkg/filter/network/proxy/factory.go#L120-L122
proxy是提供了默认的route handler名字: default
同时，route handler factory 提供了注册默认handler的方法：
https://github.com/mosn/mosn/blob/80f7fa46133ba669137dc0184440463487eb3019/pkg/router/factory.go#L33-L36

场景：
假设我自定义了个route handler, 名字为 test，同时设置为默认的route handler
那么proxy即使不声明route handler name，也会去找名为default的route handler，而不是我自定义的route handler

预期:
我注册了默认的route handler，理论上只要不声明，都应该使用我声明的router handler

**Comment by nejisama** [comment]
“同时设置为默认的route handler” 
似乎没有提供这种接口？

**Comment by nejisama** [comment]
似乎应该是Set Default的时候 把这个name也换掉

**Comment by jizhuozhi** [comment]
> 突然感觉go里面这个const定位，好像不适合后续拓展了，哈哈

我觉得可以把它改为包可见的，然后通过方法进行暴露 `// 但是感觉就像是成了Java一样`

**Comment by nejisama** [comment]
> > 突然感觉go里面这个const定位，好像不适合后续拓展了，哈哈
> 
> 我觉得可以把它改为包可见的，然后通过方法进行暴露 `// 但是感觉就像是成了Java一样`

但是好像比较合理，不像变量一样可以直接改

**Comment by jizhuozhi** [comment]
@doujiang24 提了一个好的建议https://github.com/mosn/mosn/pull/2308#discussion_r1192071683，也许我们可以提供一个优先级更高的变量，如果这个变量设置了，那么我们就使用这个设置了的变量，否则就使用默认值进行处理，这样可以避免我们对外到处的api和变量发生变化
