### ISSUE TITLE
exclusion_labels cause panic

### ISSUE THREAD

**Issue by wenxuwan** [mosn/mosn#2311]
### Describe the bug

The configure like this:
![image](https://github.com/mosn/mosn/assets/11661906/b7de9ea7-1d66-4d0b-82b3-b385dd90b3e7)

stack:

![image](https://github.com/mosn/mosn/assets/11661906/5e23eaf1-1fc3-4539-9b4d-7507a7df279d)

### Expected behavior

start success

### Actual behavior

panic

### Environment

- MOSN Version
	latest

**Comment by antJack** [comment]
https://github.com/mosn/mosn/pull/2310
