### ISSUE TITLE
PeakEWMA supports configuring different bias of client errors and server errors

### ISSUE THREAD

**Issue by jizhuozhi** [mosn/mosn#2324]
### The New Feature

PeakEWMA supports configuring different bias of client errors and server errors

### Your scenes

As #2295 and #2323, we support fixing the EWMA when upstream fail fast. But in actual production environment,  server errors are very unacceptable, so we need a way to configure the bias of server errors to avoid choose hosts with server errors.

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by doujiang24** [comment]
@jizhuozhi better add a simple design, i.e. where to add these configurations, or, a similar example somewhere.
make it easier to start as a good first issue, thanks!

**Comment by jizhuozhi** [comment]
#2301 displays how to add bias for `activeRequest`. What we need to do for this issue, is in the same way to add `clientErrorBias` and `serverErrorBias` and then calculate the `biasedClientErrorRate` and `biasedServerErrorRate`.

**Comment by jizhuozhi** [comment]
Closed via #2337
