### ISSUE TITLE
协程泄露

### ISSUE THREAD

**Issue by alpha-baby** [mosn/mosn#2336]
https://github.com/mosn/mosn/blob/07be2d0d6b9cee511262f85132277fcf937be23b/pkg/upstream/healthcheck/session_checker.go#L160

这个地方当 stop chan 被关闭了，start 方法的那个协程就立马退出了，然后正在执行具体检查逻辑的那个协程就一直被卡到这个位置，然后就泄露

OnTimeout 方法没有对具体是哪个 checkID 做校验，并发情况下会导致把一个正常的给搞成超时

目前的这个健康检查机制还有个问题是，在 Host 比较多的时候，比如：我们公司有个场景有 2.3 W 个 Host ，那么就有 2.3 W 个协程做健康检查，协程太多就会导致调度变慢进而影响性能，协程多了还占用内存，
@doujiang24

**Comment by doujiang24** [comment]
貌似真的有 bug，有兴趣来个补丁不？

**Comment by alpha-baby** [comment]
> 貌似真的有 bug，有兴趣来个补丁不？

可以

**Comment by nejisama** [comment]
是可以优化一下，不用那么多goroutine

**Comment by alpha-baby** [comment]
> 是可以优化一下，不用那么多goroutine

我想了两个方案：

1. 每个 cluster 启动一个协程，这个协程就循环去检查每个 host 的健康状态，有人可能会有疑问，这样的话检查的及时性是不是就不好了
    1.  如果依赖主动健康检查去非常快的摘除不健康的节点，这种做法是不太对的，应该使用熔断工具去做这种非常快速的摘除有问题的 Host。
    2. 在大规模的微服务场景下，一个服务可能有几百个或者上千个 Host，一个应用可能调用几十上百个服务，一个 sidecar 可能就需要连接上万个 Host，如果你健康检查间隔配置的很小会导致你服务一直被检查，建议至少配置 30 秒以上，当然这是得服务规模很大的场景下才会遇到。
    3.  如果某个 Host 检查花费了很长时间，是不是就阻塞了检查其他的 Host, 这个确实有这个问题，这个问题的话需要自己合理评估健康检查的超时时间设置是否合理。
2. 全局启动一个协程池，启动一个延迟队列，延迟时间就是健康检查的间隔时间.
    1. 相比方案一可以增加并行检查的及时性，但是更为复杂，如果协程池用完还是需要等待空闲的协程
    2. 相比 mosn 中原始的方式和方案 1， 方案 2 是介于两者之间。如果协程池配置的比较少就类似方案 1，如果协程池配置的多那么就类似方案 3

你们怎么看？

**Comment by jizhuozhi** [comment]
> 每个 cluster 启动一个协程，这个协程就循环去检查每个 host 的健康状态，有人可能会有疑问，这样的话检查的及时性是不是就不好了

我理解这个协程只是负责轮询hosts去触发健康检查任务吧，实际去执行健康检查的时候还是需要开一个协程的，不然只要有一个host因为不健康达到了最大超时时间，健康检查的吞吐就会急速下降。我们的期望其实就是在host被移除后绑定的协程不要泄漏即可，而不要带来额外的副作用。

**Comment by alpha-baby** [comment]
> > 每个 cluster 启动一个协程，这个协程就循环去检查每个 host 的健康状态，有人可能会有疑问，这样的话检查的及时性是不是就不好了
> 
> 我理解这个协程只是负责轮询hosts去触发健康检查任务吧，实际去执行健康检查的时候还是需要开一个协程的，不然只要有一个host因为不健康达到了最大超时时间，健康检查的吞吐就会急速下降。我们的期望其实就是在host被移除后绑定的协程不要泄漏即可，而不要带来额外的副作用。

肯定是不能泄漏，健康检查要那么高的吞吐干嘛，反而把业务请求的性能给占用了，我说的场景是在大规模情况下，比如要给sidecar 有 2W Host

**Comment by doujiang24** [comment]
我更倾向于方案 2，并且，默认情况下，协程池的数量不受限制（这样可以向后兼容）；或者是一个很大的值，保证多数情况下不受影响

我的逻辑是，既然是提供给了用户这个能力，还是要尽量做到，先完成功能，再提升性能
2 里的协程池，我觉得是一个合理的折中

**Comment by alpha-baby** [comment]
那我有空了先搞一下协程池的版本
