### ISSUE TITLE
请问mosn的MOE架构什么时候能支持在envoy的L4扩展能力呢

### ISSUE THREAD

**Issue by duxin40** [mosn/mosn#2347]
请问mosn的MOE架构什么时候能支持在envoy的L4扩展能力呢

**Comment by taoyuanyuan** [comment]
> 请问mosn的MOE架构什么时候能支持在envoy的L4扩展能力呢

已经支持，核心能力已经贡献给envoy官方，欢迎试用提意见~
https://www.envoyproxy.io/docs/envoy/v1.27.0/configuration/listeners/network_filters/golang_filter.html

**Comment by duxin40** [comment]
@taoyuanyuan 赞～还想问下目前开源mosn内的接入envoy的l4插件的代码有实现么，目前看只有l7的实现～
![Uploading image.png…]()

**Comment by taoyuanyuan** [comment]
> @taoyuanyuan 赞～还想问下目前开源mosn内的接入envoy的l4插件的代码有实现么，目前看只有l7的实现～ ![image](https://user-images.githubusercontent.com/33946910/270880752-00101c0f-b2dd-4183-900e-d1dfcc719877.png)

这个后续看加上，目前推荐直接用envoy就能玩起来哈
随便问下，你们是什么场景需要用到，是业务需要，还是自己玩~

**Comment by duxin40** [comment]
> 随便问下，你们是什么场景需要用到，是业务需要，还是自己玩~

我们目前在调研阶段，想用envoy做来做流量代理，但是考虑到研发效能，所以想用MOE的方案看看～
因为涉及到L4的流量处理，顺便再确认下～ 那对于企业内部自定义的RPC协议，涉及到四层的流量filter操作，基于目前开源版mosn是做不到哈？只能基于原生envoy的l4 extension来做了哈？

**Comment by taoyuanyuan** [comment]
> > 随便问下，你们是什么场景需要用到，是业务需要，还是自己玩~
> 
> 我们目前在调研阶段，想用envoy做来做流量代理，但是考虑到研发效能，所以想用MOE的方案看看～ 因为涉及到L4的流量处理，顺便再确认下～ 那对于企业内部自定义的RPC协议，涉及到四层的流量filter操作，基于目前开源版mosn是做不到哈？只能基于原生envoy的l4 extension来做了哈？

这个我们内部的做法就是mosn的xprotocol框架支持多协议，然后在用L4 moe嫁接到envoy上。收益还是很可观，没有链接的常驻协程。
如果直接用envoy的L4的话，你其实还是需要用go搞一套proxy框架出来的。
你可以先用纯mosn支持你们的rpc协议，然后在用moe移植到envoy上。

**Comment by taoyuanyuan** [comment]
> > 随便问下，你们是什么场景需要用到，是业务需要，还是自己玩~
> 
> 我们目前在调研阶段，想用envoy做来做流量代理，但是考虑到研发效能，所以想用MOE的方案看看～ 因为涉及到L4的流量处理，顺便再确认下～ 那对于企业内部自定义的RPC协议，涉及到四层的流量filter操作，基于目前开源版mosn是做不到哈？只能基于原生envoy的l4 extension来做了哈？

这个我们内部的做法就是mosn的xprotocol框架支持多协议，然后在用L4 moe嫁接到envoy上。收益还是很可观，没有链接的常驻协程。
如果直接用envoy的L4的话，你其实还是需要用go搞一套proxy框架出来的。

**Comment by duxin40** [comment]
> 你可以先用纯mosn支持你们的rpc协议，然后在用moe移植到envoy上。

嗯嗯，我们也想这样搞，但是目前moe的L4 extension没有开源呀，求大佬推进开源L4 extension，这块开源roadmap有嘛，我们之后可以共建～

**Comment by duxin40** [comment]
> 然后在用L4 moe嫁接到envoy上

如果短期内没有开源计划的话，moe的L4 extension这块逻辑，有一些指导文档和建议么，我们尝试看能不能自己搞～

**Comment by taoyuanyuan** [comment]
> > 然后在用L4 moe嫁接到envoy上
> 
> 如果短期内没有开源计划的话，moe的L4 extension这块逻辑，有一些指导文档和建议么，我们尝试看能不能自己搞～

你可以钉钉联系我，烈元
