### ISSUE TITLE
您好，请问多路复用的映射关系在哪里记录的呢？

### ISSUE THREAD

**Issue by zzqCh** [mosn/mosn#2354]
### Your question

您好，请问多路复用的映射关系在哪里记录的呢？

### Environment

- MOSN Version

### Logs

- Paste the logs you see.

**Comment by taoyuanyuan** [comment]
没有啥多路复用的映射关系表哟
可以看下整个id的修改，替换过程，差不多就是支持多路复用的关键点。

1. 这个保存了原始的id
https://github.com/mosn/mosn/blob/9409ffa46969e2389f0debb9b442feb865c8ec08/pkg/stream/xprotocol/conn.go#L370

2. 转发给upstream的时候分配了一个新id
https://github.com/mosn/mosn/blob/9409ffa46969e2389f0debb9b442feb865c8ec08/pkg/stream/xprotocol/conn.go#L386

3. 返回请求的时候，把id还原为原始的id
https://github.com/mosn/mosn/blob/9409ffa46969e2389f0debb9b442feb865c8ec08/pkg/stream/xprotocol/stream.go#L137

**Comment by zzqCh** [comment]
> 没有啥多路复用的映射关系表哟
> 可以看下整个id的修改，替换过程，差不多就是支持多路复用的关键点。
> 
> 1. 这个保存了原始的id
> https://github.com/mosn/mosn/blob/9409ffa46969e2389f0debb9b442feb865c8ec08/pkg/stream/xprotocol/conn.go#L370
> 
> 2. 转发给upstream的时候分配了一个新id
> https://github.com/mosn/mosn/blob/9409ffa46969e2389f0debb9b442feb865c8ec08/pkg/stream/xprotocol/conn.go#L386
> 
> 3. 返回请求的时候，把id还原为原始的id
> https://github.com/mosn/mosn/blob/9409ffa46969e2389f0debb9b442feb865c8ec08/pkg/stream/xprotocol/stream.go#L137

好的我学习学习，谢谢您
