### ISSUE TITLE
BOLT 协议的心跳检测耗时较长

### ISSUE THREAD

**Issue by hui-cha** [mosn/mosn#2364]
### The New Feature
目前 BOLT 协议的心跳检测机制默认是一次 Read Timeout 会触发一次心跳检测，6 次检测超时之后断开链接。一次 Read Timeout 为 15s，所以默认断开连接需要 15 * 6 = 90s。这个时间在我们的业务场景下有些长，业务上希望可以把断开时间降低到 30s 内，在目前的实现下就只能把心跳检测次数改成 1 了，但是这样可能会导致连接不稳定更容易断开。所以希望有个机制可以缩短心跳检测的间隔。

### Your scenes
业务场景主要是服务提供方异常宕机无响应，希望通过心跳较快速的剔除掉这个异常连接

### Your advice
目前 Mosn 上 BOLT 协议的心跳检测机制更倾向于降低检测频率，减少 CPU 占用。所以可能这样的方式更合适：在心跳检测失败的时候触发快速检测，检测不再以 Read Timeout 事件触发，而是另起协程以短间隔快速检测几次，如果这几次检测都失败了就断开链接。

这样在正常的场景下，心跳频率仍然是一次 Read Timeout 也就是 15s 一次。在异常情况下才会减少心跳检测间隔。

### Environment

- MOSN Version: mosn.io/mosn v1.5.1-0.20230614031520-2aa33a14939b

**Comment by alpha-baby** [comment]
你所说的是空闲超时，如果你想要空闲超时更快，你可以自己配置更小时间，
你 pr 改动的地方是用来连接保活的，并不是用来做链接的健康检查的，如果你想要自己做健康健康可以推荐这里：
1. 主动健康检查：https://github.com/mosn/mosn/blob/master/pkg/upstream/healthcheck/healthchecker.go

**Comment by hui-cha** [comment]
> 你所说的是空闲超时，如果你想要空闲超时更快，你可以自己配置更小时间， 你 pr 改动的地方是用来连接保活的，并不是用来做链接的健康检查的，如果你想要自己做健康健康可以推荐这里：
> 
> 1. 主动健康检查：https://github.com/mosn/mosn/blob/master/pkg/upstream/healthcheck/healthchecker.go
> 2. 如果你想做被动健康检查，你可以用 sentinel-go 熔断，https://github.com/mosn/mosn/blob/master/pkg/filter/stream/flowcontrol/stream_filter_factory.go

我们这里想要的不是空闲超时，主要是想要剔除同一个 IP 上的无响应连接。

我们的业务场景是这样的

Client -> Mosn -> LVS -> Mosn -> Server

我们使用 Mosn 做了一个网络代理，将 Client 的请求转发给 Server。Client Mosn 通过 LVS 和 Server Mosn 通信，中间的 LVS 只有一个，后面的 Server Mosn 可能有多个。当 LVS 后面的某一个 Server Mosn 所在的宿主机宕机无响应的时候，希望 Client Mosn 可以快速断开这个长链接。

在异常发生的时间内，由于 Client 还会持续发送请求，因此 Client Mosn 也会持续向长链接发送请求，所以如果不能感知连接的状态，那么连接上会持续有请求，这样就不会触发空闲超时。

做主动健康检查剔除异常 IP 这个并不满足这个场景的需求，因为 Client Mosn 看到的 Upstream 地址是 LVS，只有一个地址。

Sentinel 如果可以做到连接级别的熔断的话，应该是满足业务需求的，我去看看这块的实现，感谢大佬、

**Comment by hui-cha** [comment]
查看了下熔断的实现，现在这里做的应该还是 Host 级别的熔断，在 LVS 的场景下不太适用

https://github.com/mosn/mosn/blob/b16511a42a12d4466d262f741dc8388351941ed7/pkg/filter/stream/faulttolerance/send_filter.go#L58

**Comment by alpha-baby** [comment]
首先明确，你这个宕机，对于 client mosn 是否可以感知到 tcp reset 包，如果可以感知到，那你可以设置，连接事件的回调函数，你可以添加自己的回调函数，https://github.com/mosn/mosn/blob/b16511a42a12d4466d262f741dc8388351941ed7/pkg/network/connection.go#L262

回调函数里面你就可以实现自己想要的逻辑。

如果你那个宕机是不能感知 tcp 连接断开的，这个看起来没太好的做法，那可能就只能从业务层上面去做一些重试什么的

**Comment by hui-cha** [comment]
这个场景主要指物理机宕机，可能确实是没有 reset 包的。如果 tcp 层面断开链接了，那么 mosn 也不会继续往这个链接转发请求了，这样就只是宕机的那个瞬间会有一部分还没处理完的请求失败。但是现在业务上观察到的现象就是失败会持续大概 90s 所以 tcp 链接应该是没断开的，还是靠的心跳检测主动断开的链接。

现在就是这个心跳检测断开的时长太长了，我们想缩短这个时间。PR 里那样的解决方案并不好，请问下这个心跳检测的间隔可以支持配置，或者 keepalive 的实现可以支持业务扩展吗？

**Comment by alpha-baby** [comment]
主动健康检查：https://github.com/mosn/mosn/blob/master/pkg/upstream/healthcheck/healthchecker.go

**Comment by hui-cha** [comment]
Host 级别的主动健康检查对我来说用不了，因为 Host 是 LVS，只有一个地址。

keepalive 这个现在健康检查的间隔是固定的 15s，不可以调整的，其实我就是想缩短这个间隔

**Comment by alpha-baby** [comment]
> Host 级别的主动健康检查对我来说用不了，因为 Host 是 LVS，只有一个地址。
> 
> Keepalive 这个现在触发一次心跳就是写死的一次 Read timeout 是 15s，我们觉得这个时间太长了，想改短一些。
> 
> 这个可以支持配置吗？

看了你提交的 PR , 看起来是一个目前来说相对比较好的解决方案了，

**Comment by hui-cha** [comment]
好的，谢谢大佬，那我再看下 CR 里的 Comment 重新修改下
