### ISSUE TITLE
社区钉钉二维码过期

### ISSUE THREAD

**Issue by WeixinX** [mosn/mosn#2390]
Github README 及其官方网站中的社区钉钉二维码过期：

<img width="982" alt="image" src="https://github.com/mosn/mosn/assets/49450531/94c9ad3e-1811-479a-b655-f9ff38c09255">

<img width="766" alt="image" src="https://github.com/mosn/mosn/assets/49450531/9b0620c1-cb07-4963-99a5-a1a8ed5331c2">

扫描效果如下：

![IMG_8566](https://github.com/mosn/mosn/assets/49450531/4c8ae446-1d90-4a1a-90ef-b904fb2f4f1f)

**Comment by alpha-baby** [comment]
@WeixinX 
![image](https://github.com/mosn/mosn/assets/47237632/a8ae7849-6c7e-4321-a588-dd73dde4e30c)
