### ISSUE TITLE
是否可以自定义loadbalance？

### ISSUE THREAD

**Issue by abbracadabra** [mosn/mosn#2394]
### 是否可以支持自定义的loadbalance   
原始需求是想在mesh中实现这两个负载均衡策略：   
1、服务在测试环境部署了多个泳道，想根据泳道header值选择相应的泳道上的服务调用，如果指定泳道上无服务实例则调用主干泳道     
2、同一个泳道的实例，希望优先调用同可用区的服务    
所以不知道能不能支持下自定义负载均衡，或者有啥其他方法可以实现吗？

**Comment by taoyuanyuan** [comment]
https://mosn.io/blog/posts/how-use-dynamic-metadata/
可以看看， 方法很多
