### ISSUE TITLE
mosn 1.6.1 compile  error

### ISSUE THREAD

**Issue by paulzhu8597** [mosn/mosn#2414]
### Your question
use  go  mod tidy 
error info
verifying mosn.io/pkg@v1.6.0: checksum mismatch
        downloaded: h1:mkxH/rP51LGa38guF3pjbz8nPKlnMR/9eY98FlqbTNo=
        go.sum:     h1:R+T344PEp7CauQvXEitDJTXQ0bIeOhLwnaey9qwN4Fs=

Describe your question clearly.

### Environment   
win 11   
go  version  1.20.12

- MOSN Version   1.6.1

### Logs
go: downloading github.com/c2h5oh/datasize v0.0.0-20171227191756-4eba002a5eae
go: downloading github.com/golang/protobuf v1.5.2
verifying mosn.io/pkg@v1.6.0: checksum mismatch
        downloaded: h1:mkxH/rP51LGa38guF3pjbz8nPKlnMR/9eY98FlqbTNo=
        go.sum:     h1:R+T344PEp7CauQvXEitDJTXQ0bIeOhLwnaey9qwN4Fs=
- Paste the logs you see.

**Comment by alpha-baby** [comment]
切换其他的 goproxy 代理，或者不要使用 goproxy

**Comment by alpha-baby** [comment]
请使用linux 或者 macos 或者 wsl2不支持 windows

**Comment by paulzhu8597** [comment]
ok  我试试

**Comment by paulzhu8597** [comment]
"mosn.io/pkg/buffer"
	"mosn.io/pkg/utils"
	"mosn.io/pkg/variable"   这些包还是加载不到
原来低版本的都没这个问题

**Comment by paulzhu8597** [comment]
已解决
