### ISSUE TITLE
Component lifecycle management support

### ISSUE THREAD

**Issue by JervyShi** [mosn/mosn#618]
### The New Feature

When mosn starts, it can be divided into several stages. When we do component extensions, we need to do different initialization actions at different stages, and the startup of different components is often dependent on the order.

### Your scenes

So I hope that Mosn can support component lifecycle management, define different startup phases, and call the periodic initialization methods of the registered components in sequence.

### Your advice

Maybe we can define `Lifecycle` interface, and with some stage method `init`、`onStart`、`onStop` etc.

Register factory support order for `Lifecycle`. 

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
MOSN implement `featuregates` for it
