### ISSUE TITLE
Does mosn support authorization?

### ISSUE THREAD

**Issue by WywTed** [mosn/mosn#673]
### Your question
Support HTTP1/HTTP2 protocol automatic identification 
what does that mean in change log? and does sofa-mosn support authorization such as jwt and oauth2 ?
### Environment
+ SOFAMosn latest

**Comment by nejisama** [comment]
if protocol:auto is configured in proxy,  mosn can proxy both http1/http2 request.
see: https://github.com/alipay/sofa-mosn/blob/master/configs/mosn_autoprotocol.json
no jwt and oauth2 supported yet.
