### ISSUE TITLE
Goroutine model optimization

### ISSUE THREAD

**Issue by taoyuanyuan** [mosn/mosn#696]
### The New Feature
之前对workerpool模型做了一期的改造，https://github.com/alipay/sofa-mosn/pull/589
计划对 模型做进一步的优化：
* stream的事件全部收敛到proxy的worker pool，然后简化proxy层stream状态判断逻辑并且去掉并发保护
* stream层抽象connpool
* stream引入worker pool顺序化stream事件
* 函数调用同步化.
* workerpool底层实现优化,  支持过期
* 收敛跨层的数据和事件传递

![image](https://user-images.githubusercontent.com/2707372/58314912-14e56f80-7e43-11e9-8b2b-20c9d7beb97c.png)

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution of this new feature

### Environment
+ SOFAMosn Version

**Comment by peacocktrain** [comment]
scenes  TCP 场景
advice
链路层与逻辑层解耦，方便链路层后续优化
采用类似netty设计，每个poller代表一个携程。将conn绑定到poller上，这里poller数量为可用线程数，在普通sidecar中为1，ingress中可扩展
![image](https://user-images.githubusercontent.com/15363932/58319064-b40e6500-7e4b-11e9-8372-7d415cdb75e6.png)

**Comment by peacocktrain** [comment]
因为每层切换线程每个消息所需要切换线程过多，这里读写建议不切换线程，根据不同的消息类型和处理机制可以用不同的poxyer处理
![image](https://user-images.githubusercontent.com/15363932/58320427-3009ac80-7e4e-11e9-9cef-02654e3b7356.png)

**Comment by peacocktrain** [comment]
最后，每层所响应的事件处理机制可以收集到一起统一处理，每层维护一个集合并启动一个携程监听事件。
![image](https://user-images.githubusercontent.com/15363932/58320888-47956500-7e4f-11e9-9c09-133368c51b2f.png)

**Comment by taoyuanyuan** [comment]
> 这里对于业务消息要保证吞吐量，io-stream 期间不切线程，并且减少goroutine数量
> ![image](https://user-images.githubusercontent.com/15363932/58320427-3009ac80-7e4e-11e9-9cef-02654e3b7356.png)

目前MOSN就是图上的架构， 这样吞吐量确实更高， 减少协程的唤醒切换。 
![image](https://user-images.githubusercontent.com/2707372/58394456-e69ba600-8075-11e9-969b-a0e4de6fb7dd.png)

我们会在性能和可读可维护上做一些权衡，目前只是一个初步方案，后续也会写demo代码验证每个点。
谢谢你的建议。

**Comment by peacocktrain** [comment]
如果是可读性，我认为要应用go的优势将mosn的模块化，将层级进行解耦，其实和携程关系不大1。（go开发者看到复杂的对象关系都会很头疼，并且mosn文档都是模块化思想）。

线程模型的话这样应该算是成熟方案微调吧，应该和mosn现有的还是有点区别。比如upstream和downstream分别独立携程，代理驱动携程池，另外确实要比envoy适当增加携程，比如我认为吧事件用单独的一个gorouting处理减少回调

携程切换是一个设计中要注意的点，另一个 go语言对比C++性能劣势主要还是垃圾回收。这里需要在复用和减少资源使用上努力（mosn在复用上做了很多），我的想法每个链接额外生成一个虚拟链接对象，一个gorouting做发送监听。


1:推荐我认为服务化比较好的写法https://github.com/peacocktrain/fission/blob/master/executor/poolmgr/gpm.go

**Comment by taoyuanyuan** [comment]
---- 我的想法每个链接额外生成一个虚拟链接对象，一个gorouting做发送监听。
这个跟我们的目前的`UseNetpollMode`模式类似， 但是我们在真正write的时候还是会启用一个协程池。
