### ISSUE TITLE
Goland debug question

### ISSUE THREAD

**Issue by BruceWangNo1** [mosn/mosn#834]
### Your question

Hello to the sofa-mosn developers. I start to look into sofa-mosn last night and I have been stuck with this debugging issue on Goland this whole morning.
I am trying to run [http-sample](https://github.com/sofastack/sofa-mosn/blob/master/examples/cn_readme/http-sample/README.md) in debug mode in Goland.

This is how I configured Debug in Goland.
![image](https://user-images.githubusercontent.com/8055536/65810863-dbeb4c00-e1e2-11e9-99f4-6fa5760ece0b.png)

I have "go run server.go" running in a terminal.

Somehow the debug program stopped half way.
![image](https://user-images.githubusercontent.com/8055536/65810892-47351e00-e1e3-11e9-90ca-1c960e082228.png)

![image](https://user-images.githubusercontent.com/8055536/65810898-51efb300-e1e3-11e9-8036-9e8d22965d39.png)

Does anyone have any idea? I figure that this is a purely Goland configuration problem. What am I doing wrong?

**Comment by nejisama** [comment]
this is a golang debug mode's bug. 
the implementation of `golang printf("%v", nil)  ` is nil pointer panic and recover to print <nil>
but in the debug(dlv) cannot handle this.

**Comment by nejisama** [comment]
we will try to fix the nil pointer for output.

**Comment by BruceWangNo1** [comment]
Finally, someone replied. Thank you @nejisama

**Comment by nejisama** [comment]
fixed
