### ISSUE TITLE
mosn smooth upgrade problem

### ISSUE THREAD

**Issue by kaka19ace** [mosn/mosn#866]
### 为什么热重启机制需要新老进程 两个 unix domain socket server 通信交互?
 目前分为 旧进程 reconfigerServer  新进程 transferServer,
1. reconfigerServer 只是新进程主动判断 isReconfigure() 就结束了连接  
2. 迁移 listener fd 以及 connection fd 让旧进程作为 client 角色  

如果仅使用 reconfigerServer 作为交互通信会存在哪些问题.

### Environment
+ SOFAMosn 0.7.0

**Comment by taoyuanyuan** [comment]
你的意思就是旧进程 reconfigerServer在收到isReconfigure() 后，直接传输旧进程的fd给新进程。
原理上也是可以的。
这儿其实有个历史原因，最开始支持信号fork子进程的方式，是不需要isReconfigure() 来判断是否存在旧进程的，通过环境变量就可以了，后来为了支持容器升级的方式，单独启一个新的进程，才需要一个机制来判断是否存在旧进程，为了改动更小，之前的逻辑不受影响，才加了这个新的us来通讯。
@kaka19ace

**Comment by kaka19ace** [comment]
> 你的意思就是旧进程 reconfigerServer在收到isReconfigure() 后，直接传输旧进程的fd给新进程。
> 原理上也是可以的。
> 这儿其实有个历史原因，最开始支持信号fork子进程的方式，是不需要isReconfigure() 来判断是否存在旧进程的，通过环境变量就可以了，后来为了支持容器升级的方式，单独启一个新的进程，才需要一个机制来判断是否存在旧进程，为了改动更小，之前的逻辑不受影响，才加了这个新的us来通讯。
> @kaka19ace

原来如此，对比envoy 机制，当时没太理解.  多谢指导 :)

**Comment by kaka19ace** [comment]
Hi, 再次请教:

翻了老版本代码阅读: 
reconfigure 这块是基于 环境变量设置 fd. fork exec 参数使用 sys.ProcAttr  继承 fd 信息.

这块有一个问题确认: 
老版本场景里: 如果升级新版的二进制文件, 也是基于同目录下替换了相同的 bin文件,
然后再给老进程 hup 信号触发重启吧? 

老版本代码:
```golang
execSpec := &syscall.ProcAttr{
		Env:   os.Environ(),
		Files: append([]uintptr{os.Stdin.Fd(), os.Stdout.Fd(), os.Stderr.Fd()}, listenerFD...),
	}

	// Fork exec the new version of your server
	fork, err := syscall.ForkExec(os.Args[0], os.Args, execSpec)
	if err != nil {
		log.DefaultLogger.Errorf("Fail to fork %v", err)
		return
	}
```

**Comment by kaka19ace** [comment]
1. 早期版本和envoy uds 迁移方式不同，当时设计是有什么考虑吗?
2. 后续基于 SCM_RIGHTS 传输 fd 方式 与 envoy 类似, 这块重构原因有哪些? 
想了解代码演进的过程 :)

**Comment by taoyuanyuan** [comment]
是的，老版本是发送hup信号，然后fork一个子进程来做二进制升级，这个适用于虚拟机升级。
而基于容器的话，是重新拉起一个容器，一个新的进程，就需要跟老的进程来交互。
你看到代码是listen fd的迁移，和envoy最大的不同是我们会把存量的长链接也做迁移。
代码演进是：
第一阶段， 只支持 listen fd的迁移。
第二阶段， 支持存量长链接的迁移，hup信号，然后fork的方式。
第三阶段， 支持容器间存量长链接的迁移，通过uds通信子进程。
@kaka19ace

**Comment by kaka19ace** [comment]
> 是的，老版本是发送hup信号，然后fork一个子进程来做二进制升级，这个适用于虚拟机升级。
> 而基于容器的话，是重新拉起一个容器，一个新的进程，就需要跟老的进程来交互。
> 你看到代码是listen fd的迁移，和envoy最大的不同是我们会把存量的长链接也做迁移。
> 代码演进是：
> 第一阶段， 只支持 listen fd的迁移。
> 第二阶段， 支持存量长链接的迁移，hup信号，然后fork的方式。
> 第三阶段， 支持容器间存量长链接的迁移，通过uds查找子进程。
> @kaka19ace

非常感谢丰富的演进说明.

重新拉起容器这块不太明白:
对 envoy 的场景理解:
* 热重启是同一个容器内,  sidecar 新老进程的交接, 业务进程继续运行
* sidecar 进程管理是由 pilot-agent 进行管理,  当前容器内 agent 发送热重启信号, 非重新拉起容器

1) mosn 这里指的是拉起新容器, 容器间迁移数据?  
2) 如果是 1),  uds 的路径是挂载盘?

**Comment by taoyuanyuan** [comment]
envoy的方式的话不能用镜像来管理二进制了。
mosn除了支持envoy这种容器内热升级，也支持容器间，mosn会拉起新容器，然后做容器间的连接迁移，uds的路径是共享卷，2个container共享。

**Comment by kaka19ace** [comment]
> envoy的方式的话不能用镜像来管理二进制了。
> mosn除了支持envoy这种容器内热升级，也支持容器间，mosn会拉起新容器，然后做容器间的连接迁移，uds的路径是共享卷，2个container共享。

1. 容器间迁移是否和业务场景有关,  为何不是让旧容器自己销毁(摘掉服务发现, 并延迟一段时间自己销毁)?

**Comment by taoyuanyuan** [comment]
是的，就是为了sidecar的发布对用户无感知，连接不断，升级sidecar的时候服务也一直在运行。

**Comment by kaka19ace** [comment]
> 是的，就是为了sidecar的发布对用户无感知，连接不断，升级sidecar的时候服务也一直在运行。

1.  管理sidecar 升级的 agent 是在容器外部(宿主机单agent)?
2. 容器内只有业务进程和 mosn 进程? 
3. 如果容器内 mosn 突然被kill, 但业务进程仍运行中. 这块 蚂蚁ops 实践中， 检测降级或者恢复机制是什么样的?

**Comment by taoyuanyuan** [comment]
![image](https://user-images.githubusercontent.com/2707372/69613682-f029b900-106c-11ea-8480-e971539620cc.png)
mosn和app是不同的容器，同一个pod。

**Comment by chainhelen** [comment]
@taoyuanyuan 您好，我也有一点困惑，希望能得到解答。
同一个pod已经拥有两个容器（app/mosn）了，说明在deployment已经指定了两个容器（app/mosn），是如何能在不删除pod的情况下加入了新的容器（New Mosn/app/mosn三个的）的？

**Comment by gaogaoSpark** [comment]
@chainhelen webhook + patch

**Comment by taoyuanyuan** [comment]
我们有operator来专门处理mosn平滑升级的能力，会做生命周期的管理。
mosn也支持使用发信号的方式平滑升级，这个可以在虚拟机或者容器内升级。

**Comment by chainhelen** [comment]
@gaogaoSpark 感谢，明白了，patch确实有命令可以完成. 
@taoyuanyuan 万分感谢.

**Comment by NameHaibinZhang** [comment]
> 我们有operator来专门处理mosn平滑升级的能力，会做生命周期的管理。
> mosn也支持使用发信号的方式平滑升级，这个可以在虚拟机或者容器内升级。

operator 目前有开源的计划么

**Comment by taoyuanyuan** [comment]
operator目前还没有计划计划。这个跟特定环境还是有关系，不太通用。
我们也支持发信号的方式在本机做平滑升级，这个外部使用的话更方便。

**Comment by ms2008** [comment]
关于连接迁移，我也有一些疑问：

1. New Mosn 和 Old Mosn 监听的端口一致？迁移前后 TCP 四元组信息是否改变？
2. 如果端口一致，New Mosn 和 Old Mosn 属于不同的容器，但是共享一个 POD，其实现机制是 `fork` 还是 `SO_REUSEPORT`？

**Comment by taoyuanyuan** [comment]
@ms2008 
listen fd 迁移， new mosn和old mosn监听一样的端口，也不是fork也不是SO_REUSEPORT。

**Comment by ms2008** [comment]
不好意思，还有个问题，我对 `sendmsg/recvmsg` 机制并不是很了解。listener fd 正在迁移的过程中，能否接受新来的连接？

**Comment by taoyuanyuan** [comment]
可以，old mosn的fd可以accept新连接。
如果你熟悉nginx，可以想象成2个worker都可以accept连接。

**Comment by ms2008** [comment]
@taoyuanyuan 谢谢，大概明白了
据我所知 nginx 热升级的时候是通过 `execve` 调用生成新的 master，本身就已经继承了老 master 的 listener fd，直接 listen 就好，不会 `bind`。而 mosn 这块属于分离进程传递，通过 domain socket 传递 `cmsg` 消息，都是传递 listener fd，只是方式不同而已

**Comment by taoyuanyuan** [comment]
@ms2008  是的，因为在容器间升级的场景，new mosn是一个独立启动的新进程，不是old mosn的子进程，所以只能通过domain socket来传递fd。

**Comment by JasonRD** [comment]
> @chainhelen webhook + patch

求教 webhook + patch 如何实现平滑升级的呢？k8s 在 pod runtime 过程中好像不可以 patch 新增 container。

**Comment by dunjut** [comment]
@JasonRD 我们对 k8s apiserver, kubelet 做了一些增强，其中就包括 pod 原地进行容器增删启停操作，社区版本确实不支持

**Comment by zhenjunMa** [comment]
看了最新的master分支的代码，关于平滑升级这一块总共有四部：
```
ReconfigureDomainSocket    = MosnConfigPath + string(os.PathSeparator) + "reconfig.sock"
TransferConnDomainSocket   = MosnConfigPath + string(os.PathSeparator) + "conn.sock"
TransferStatsDomainSocket  = MosnConfigPath + string(os.PathSeparator) + "stats.sock"
TransferListenDomainSocket = MosnConfigPath + string(os.PathSeparator) + "listen.sock"
```

平滑升级的过程大体分为四个阶段：
1. 升级事件的触发，使用ReconfigureDomainSocket
2. Listener的迁移，使用TransferListenDomainSocket
3. 存量连接的迁移，使用TransferListenDomainSocket

中间夹杂了一个Config的迁移，是基于dump文件的方式做的，而不是传统的UDS。

但是关于内存状态的迁移TransferStatsDomainSocket在master分支上没有找到使用的地方。

我理解比如像请求量这种数据，监控系统1min打一个点，假如前30s的请求量在旧mosn，后30s的请求量在新mosn，理论上应该由新mosn汇总这1min的总请求量然后上报。

我个人认为这些数据刚好使用TransferStatsDomainSocket来迁移，但最新的分支master上面却没找到相应的逻辑，想请教下这部分逻辑有没有开源出来，或者是不是我没找对地方？


**Environment**
master分支

**Comment by taoyuanyuan** [comment]
最开始stat的迁移是使用的TransferStatsDomainSocket，但是这个有个问题，就跟你说的一样，需要新进程去汇总，这个是不及时的，比如1分钟汇总，但我统计是5s一次，就会有问题的。
新的做法是使用共享内存，新老mosn都访问同一块内存在做stat的计数。
https://github.com/mosn/mosn/tree/master/pkg/metrics/shm

**Comment by zhenjunMa** [comment]
了解了，我研究一下

**Comment by rootsongjc** [comment]
该问题已由 @taoyuanyuan 整理成 [MOSN 平滑升级解析](https://www.sofastack.tech/projects/sofa-mosn/concept/smooth-upgrade/) 一文。关闭此 issue，如有问题请在下面评论。

**Comment by hitzhangjie** [comment]
朋友推荐，来学习下存量连接迁移，如果是长连接的话，server端读取完一个完整请求后，直接shutdown read，client连接复用写的时候会感知到对端read关闭，client重新选择一个连接就可以了。连接上已经读取的请求处理完后，正常回包，过段时间close掉。

**Comment by taoyuanyuan** [comment]
> 朋友推荐，来学习下存量连接迁移。
> 
> 
> 
> ---------------------------------
> 
> 
> 
> 如果是长连接的话，server端读取完一个完整请求后，直接shutdown read，client连接复用写的时候会感知到对端read关闭，client重新选择一个连接就可以了。连接上已经读取的请求处理完后，正常回包，过段时间close掉。
> 
> 
> 
> 没完全理解mosn这里为什么要花大代价迁移buffer呢？

这儿就是为了让client无感知，不需要重新建链接。
你说的方案就类似http2 的goaway，需要client支持，也会断链接，这个也是可以为满足无损。但是很多协议，比如dubbo，sofa并没有类似能力。你说的方案也需要client改造。

**Comment by liyork** [comment]
咨询下，是不是说，对于server主动发送响应或者超过2*TransferTimeout + 2*buffer.ConnReadTimeout + 10*time.Second，这种情况就不能进行正常主动回报？我看app->oldmosn是有stopchan的，为什么oldserver->oldmosn并没有传入?
谢谢

**Comment by taoyuanyuan** [comment]
@liyork  对于old mosn的server，是不会有新请求了，新的请求都去new mosn了，但是old server会等待之前请求的响应。也就是你列的那个时间内

**Comment by firefeifei** [comment]
我想了解下SSL这部分的链接迁移是什么实现呢？
还有HAproxy 是不是也不支持这种长连接迁移的？仅是新连接请求不会中断

**Comment by taoyuanyuan** [comment]
https://github.com/mosn/mosn/blob/b1eb47897aec067a23e0a8e5c6ee3cc9dc884945/pkg/mtls/crypto/tls/tls_custom.go#L42
@firefeifei 
可以看这块代码，把对称秘钥也迁移到了新的连接里
据我所知，nginx，envoy，haproxy等都不支持存量连接的迁移，只是迁移了listen fd，保证新连接不出问题。

**Comment by firefeifei** [comment]
> https://github.com/mosn/mosn/blob/b1eb47897aec067a23e0a8e5c6ee3cc9dc884945/pkg/mtls/crypto/tls/tls_custom.go#L42
> 
> 
> @firefeifei
> 可以看这块代码，把对称秘钥也迁移到了新的连接里
> 据我所知，nginx，envoy，haproxy等都不支持存量连接的迁移，只是迁移了listen fd，保证新连接不出问题。

感谢解答

**Comment by Huixxi** [comment]
您好，在长连接的迁移过程中有个问题想请教一下，就是在New Mosn收到connfd和相关数据并把数据发送至client之后，直到Old Mosn停止读取数据这段时间，这时client再次向这个connfd发送数据的时候，新老Mosn进程之间对于该数据的读取是竞争关系么？

**Comment by taoyuanyuan** [comment]
不是竞争的，迁移流程保证了同时只能有一个mosn去read数据。

**Comment by cwdsuzhou** [comment]
mosn 对于 http2  和  grpc是怎么处理的，客户端是否需要断开连接

**Comment by taoyuanyuan** [comment]
> mosn 对于 http2 和 grpc是怎么处理的，客户端是否需要断开连接

需要断开，但是这个断开是可以无损的，可以发送goaway帧。

**Comment by cwdsuzhou** [comment]
> > mosn 对于 http2 和 grpc是怎么处理的，客户端是否需要断开连接
> 
> 需要断开，但是这个断开是可以无损的，可以发送goaway帧。

所以这里平滑主要是为了处理一些基于tcp封装的无状态协议？

**Comment by taoyuanyuan** [comment]
> > > mosn 对于 http2 和 grpc是怎么处理的，客户端是否需要断开连接
> > 
> > 
> > 需要断开，但是这个断开是可以无损的，可以发送goaway帧。
> 
> 所以这里平滑主要是为了处理一些基于tcp封装的无状态协议？

是的， 比如dubbo和sofarpc这些，就可以直接不断链升级

**Comment by LiujunjieALiling** [comment]
> @ms2008 listen fd 迁移， new mosn和old mosn监听一样的端口。

我这边也有一个疑问，麻烦帮忙解答一下。 new mosn  跟old mosn 监听相同的端口的话 不会出现 already  in used 么？

**Comment by taoyuanyuan** [comment]
> > @ms2008 listen fd 迁移， new mosn和old mosn监听一样的端口。
> 
> 我这边也有一个疑问，麻烦帮忙解答一下。 new mosn 跟old mosn 监听相同的端口的话 不会出现 already in used 么？

@LiujunjieALiling  不会的，他们用的是同一个listen fd，可以看这篇文章 https://mosn.io/blog/code/mosn-reconfig-mechanism/

**Comment by LiujunjieALiling** [comment]
> > > @ms2008 listen fd 迁移， new mosn和old mosn监听一样的端口。
> > 
> > 
> > 我这边也有一个疑问，麻烦帮忙解答一下。 new mosn 跟old mosn 监听相同的端口的话 不会出现 already in used 么？
> 
> @LiujunjieALiling 不会的，他们用的是同一个listen fd，可以看这篇文章 https://mosn.io/blog/code/mosn-reconfig-mechanism/

感谢，我去看一下

**Comment by LiujunjieALiling** [comment]
@taoyuanyuan   求教  （1）如果要是容器进程间热更新mosn的话，有指导手册么？ （2） fork的方式更新，哪个版本开始i支持的呢？ 相应的热更新手册有么？

**Comment by taoyuanyuan** [comment]
@LiujunjieALiling  （1） 可以看看这个文档，通过 sidecarset， https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/ ； （2） 如果是fork的方式，一般就是虚拟机场景了，也是mosn最早就支持的模式，直接给mosn进程 kill -1  发送 hup 信号就行了

**Comment by LiujunjieALiling** [comment]
> @LiujunjieALiling （1） 可以看看这个文档，通过 sidecarset， https://mosn.io/blog/posts/mosn-sidecarset-hotupgrade/ ； （2） 如果是fork的方式，一般就是虚拟机场景了，也是mosn最早就支持的模式，直接给mosn进程 kill -1 发送 hup 信号就行了

thx

**Comment by xueqiwang0v0** [comment]
请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？

**Comment by taoyuanyuan** [comment]
> 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？

就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。

**Comment by xueqiwang0v0** [comment]
是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？
从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？

**Comment by xueqiwang0v0** [comment]
> > 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？
> 
> 就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。

是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？
从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？

**Comment by taoyuanyuan** [comment]
> > > 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？
> > 
> > 
> > 就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。
> 
> 是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？ 从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？

https://github.com/mosn/mosn/blob/3f01437302aeb61a2e9dd0958aa4ebc70a89942f/pkg/network/connection.go#L459
可以看这个代码，进入迁移流程之后，所有upstream read io的包，都会走transferWrite流程，不是只处理一次。

**Comment by xueqiwang0v0** [comment]
> > > > 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？
> > > 
> > > 
> > > 就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。
> > 
> > 
> > 是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？ 从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？
> 
> https://github.com/mosn/mosn/blob/3f01437302aeb61a2e9dd0958aa4ebc70a89942f/pkg/network/connection.go#L459
> 
> 
> 可以看这个代码，进入迁移流程之后，所有upstream read io的包，都会走transferWrite流程，不是只处理一次。

感谢，这个地方之前看到过，但还是有些不明白。

1. c.transfer中会依次进行transferRead和transferWrite，对于这特定某一个connection c1的迁移是否只会接收到一个c1.stopChan信号？也就是c1.transfer()只会执行一次？（因为我看到每次transferRead过程中都会对该tcp连接进行tcp fd的迁移，所以推测只会有一次读迁移）

2. 处理完transferRead后，transferWrite会持续监听writeBufferChan，在超时时间内收到的writeBuffer数据都会迁移，如果残留响应已经迁移完成，transferWrite仍会持续阻塞到超时时间结束，而不会通过某种机制判断响应完成而提前结束。可以这么理解吗？

**Comment by taoyuanyuan** [comment]
> > > > > 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？
> > > > 
> > > > 
> > > > 就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。
> > > 
> > > 
> > > 是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？ 从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？
> > 
> > 
> > https://github.com/mosn/mosn/blob/3f01437302aeb61a2e9dd0958aa4ebc70a89942f/pkg/network/connection.go#L459
> > 
> > 可以看这个代码，进入迁移流程之后，所有upstream read io的包，都会走transferWrite流程，不是只处理一次。
> 
> 感谢，这个地方之前看到过，但还是有些不明白。
> 
> 1. c.transfer中会依次进行transferRead和transferWrite，对于这特定某一个connection c1的迁移是否只会接收到一个c1.stopChan信号？也就是c1.transfer()只会执行一次？（因为我看到每次transferRead过程中都会对该tcp连接进行tcp fd的迁移，所以推测只会有一次读迁移）
> 2. 处理完transferRead后，transferWrite会持续监听writeBufferChan，在超时时间内收到的writeBuffer数据都会迁移，如果残留响应已经迁移完成，transferWrite仍会持续阻塞到超时时间结束，而不会通过某种机制判断响应完成而提前结束。可以这么理解吗？

是这个意思，这个迁移是做在tcp层，如果要感知协议，做七层协议数据的迁移，就相当复杂了。
提前结束的收益也就是提前释放一个tcp链接，提前关闭。但付出的代价就是要感知协议了，成本就很高了。

**Comment by taoyuanyuan** [comment]
> > > > > 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？
> > > > 
> > > > 
> > > > 就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。
> > > 
> > > 
> > > 是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？ 从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？
> > 
> > 
> > https://github.com/mosn/mosn/blob/3f01437302aeb61a2e9dd0958aa4ebc70a89942f/pkg/network/connection.go#L459
> > 
> > 可以看这个代码，进入迁移流程之后，所有upstream read io的包，都会走transferWrite流程，不是只处理一次。
> 
> 感谢，这个地方之前看到过，但还是有些不明白。
> 
> 1. c.transfer中会依次进行transferRead和transferWrite，对于这特定某一个connection c1的迁移是否只会接收到一个c1.stopChan信号？也就是c1.transfer()只会执行一次？（因为我看到每次transferRead过程中都会对该tcp连接进行tcp fd的迁移，所以推测只会有一次读迁移）
> 2. 处理完transferRead后，transferWrite会持续监听writeBufferChan，在超时时间内收到的writeBuffer数据都会迁移，如果残留响应已经迁移完成，transferWrite仍会持续阻塞到超时时间结束，而不会通过某种机制判断响应完成而提前结束。可以这么理解吗？

transferRead 是迁移新的请求就走new mosn了，一次就行了，后面的read都在new mosn。transferWrite需要多次，会一直把response写给new mosn返回给client。

**Comment by xueqiwang0v0** [comment]
> > > > > > 请教一下，写迁移阶段Old Mosn向New Mosn传递残留响应，是如何判定残留响应已经结束了的？还是说在整个迁移期间（2 * TransferTimeout）回复给Old Mosn的响应都会通过写迁移传递给New Mosn？
> > > > > 
> > > > > 
> > > > > 就是你说的哈，如果一个response在这段时间都没返回（已经发送request了），那就认为失败了。一般请求超时也不会这么长，当然也有极低得几率有问题，就当是超时失败了。
> > > > 
> > > > 
> > > > 是指在超时时间内收到的响应片段都会直接传递给New Mosn吗？假设一个响应很大，是会触发多次transferWrite还是一次transferRead呢？ 从代码中看起来是一个连接会处理一次transferRead和transferWrite，如何保证在transferWrite中得到的响应是完整的？
> > > 
> > > 
> > > https://github.com/mosn/mosn/blob/3f01437302aeb61a2e9dd0958aa4ebc70a89942f/pkg/network/connection.go#L459
> > > 
> > > 可以看这个代码，进入迁移流程之后，所有upstream read io的包，都会走transferWrite流程，不是只处理一次。
> > 
> > 
> > 感谢，这个地方之前看到过，但还是有些不明白。
> > 
> > 1. c.transfer中会依次进行transferRead和transferWrite，对于这特定某一个connection c1的迁移是否只会接收到一个c1.stopChan信号？也就是c1.transfer()只会执行一次？（因为我看到每次transferRead过程中都会对该tcp连接进行tcp fd的迁移，所以推测只会有一次读迁移）
> > 2. 处理完transferRead后，transferWrite会持续监听writeBufferChan，在超时时间内收到的writeBuffer数据都会迁移，如果残留响应已经迁移完成，transferWrite仍会持续阻塞到超时时间结束，而不会通过某种机制判断响应完成而提前结束。可以这么理解吗？
> 
> transferRead 是迁移新的请求就走new mosn了，一次就行了，后面的read都在new mosn。transferWrite需要多次，会一直把response写给new mosn返回给client。

明白了，非常感谢
