### ISSUE TITLE
Support variable usage like nginx.

### ISSUE THREAD

**Issue by neverhook** [mosn/mosn#880]
### The New Feature

Provide a **Flexible** and  **Efficient** way to pass information across layers, like protocol/stream/proxy.

### Your scenes

1. More flexible way to pass information. For example, get the length of a particular request in **proxy** layer.  Currently we can only handle headers/body/trailers, which may not have the exact info about the request length.

2. Efficient way to get some data, like remote address. The current implementation needs to call `net.Addr->String()` every time, which means more cpu cost. It seems better if we can use "$remote_addr".

### Your advice

Support  variable usage like nginx.

### Environment
+ SOFAMosn Version

**Comment by rootsongjc** [comment]
Test DingTalk Github robot.

**Comment by nejisama** [comment]
fixed in 0.9.0
