### ISSUE TITLE
Run Mosn's images error

### ISSUE THREAD

**Issue by peacocktrain** [mosn/mosn#889]
### Describe the bug
```bash
make build
make build-linux64
make rpm
make image
```
and  docker run mosn's image

### Actual behavior
Error: Invalid user name admin in section 'program:mosn' (file: '/etc/supervisord/conf.d/mosn.conf')
For help, use /usr/bin/supervisord -h

### Environment
+ SOFAMosn master

**Comment by nejisama** [comment]
make build && make image is ok
