### ISSUE TITLE
Can mosn open port 15001 and handle requests from different protocols at the same time?

### ISSUE THREAD

**Issue by NameHaibinZhang** [mosn/mosn#897]
### The New Feature

将mosn 按照容器化的方式部署，通过读取默认配置，暴露15001端口，mosn能够同时在一个端口接收不同协议的请求么，如http、sofarpc请求

describe the new feature you want to support clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution of this new feature

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
1. mosn的默认配置都是一些example，没有15001端口，你需要按照你的需求写你的配置。
2. 一个listener目前不能同时处理两种协议，listener中proxy的配置指定了可以处理的协议

**Comment by NameHaibinZhang** [comment]
> 1. mosn的默认配置都是一些example，没有15001端口，你需要按照你的需求写你的配置。
> 2. 一个listener目前不能同时处理两种协议，listener中proxy的配置指定了可以处理的协议

15001端口是按sidecar方式部署的时候开启的端口，比如通过istio来部署，iptables 中envoy开启15001端口

**Comment by taoyuanyuan** [comment]
目前同一个端口支持 tls/明文自定识别， http1/http2的自动识别，协议哪儿配置 Auto
http和sofa的识别目前不支持，有需求的话支持也很方便。

**Comment by NameHaibinZhang** [comment]
> 目前同一个端口支持 tls/明文自定识别， http1/http2的自动识别，协议哪儿配置 Auto
> http和sofa的识别目前不支持，有需求的话支持也很方便。

嗯，因为作为sidecar部署的时候，http的接口和sofa接口都希望能通过sidecar来做流量劫持，Auto可以做rpc协议的支持和识别不？

**Comment by taoyuanyuan** [comment]
如果是做流量劫持的话，其实是不需要支持识别的，这个15001不会实际处理请求，会转发给正确的端口来处理。

**Comment by NameHaibinZhang** [comment]
> 如果是做流量劫持的话，其实是不需要支持识别的，这个15001不会实际处理请求，会转发给正确的端口来处理。

sidecar 内部做一个转发是吧，开另外2个端口，那15001这个端口配置tcp 协议了，然后接收到之前做判断是什么协议。转给对应的接口

**Comment by taoyuanyuan** [comment]
https://www.servicemesher.com/blog/x-protocol-common-address-solution/
可以看看这篇文章 《DNS通用寻址方案》
