### ISSUE TITLE
load balancing extension

### ISSUE THREAD

**Issue by Alanyx** [mosn/mosn#931]
We hope mson can provide  extension function in load balancing.

For example, before load balancing, query target servers(for example we have 5 same server instance) api service interface to check that target servers is busy. After query and check, then decide which target server to dipose this request.

Now,the normal load balancing strategy like random, polling can not meet our requirements.

This scene is very common in our business.We want to use mson as our sidecar. Thank you!

**Comment by nejisama** [comment]
mosn  support lb extension. we will add a document for it.
now you can see the unit test in load blance, there is an example.
https://github.com/mosn/mosn/blob/master/pkg/upstream/cluster/lb_register_test.go
