### ISSUE TITLE
metrics collected error

### ISSUE THREAD

**Issue by peacocktrain** [mosn/mosn#934]
### Describe the bug

For metrics collected by mosn using prometheus, prometheus-server will report an error。
Is the prometheus‘s version of mosn too low？
### prometheus log ：
level=warn ts=2020-01-11T03:49:14.392Z caller=scrape.go:930 component="scrape manager" scrape_pool=kubernetes-pods target=http://172.22.111.250:34903/metrics msg="append failed" err="invalid metric type \"a4cea8b8) gauge\""
level=warn ts=2020-01-11T03:49:24.392Z caller=scrape.go:930 component="scrape manager" scrape_pool=kubernetes-pods target=http://172.22.111.250:34903/metrics msg="append failed" err="invalid metric type \"a4cea8b8) gauge\""
level=warn ts=2020-01-11T03:49:34.393Z caller=scrape.go:930 component="scrape manager" scrape_pool=kubernetes-pods target=http://172.22.111.250:34903/metrics msg="append failed" err="invalid metric type \"a4cea8b8) gauge\""
level=warn ts=2020-01-11T03:49:44.390Z caller=scrape.go:930 component="scrape manager" scrape_pool=kubernetes-pods target=http://172.22.111.250:34903/metrics msg="append failed" err="invalid metric type \"a4cea8b8) gauge\""

### Environment
prometheus 2.12

- MOSN Version master newest

**Comment by peacocktrain** [comment]
我修复了它，bug在于有个gauge将版本号作为name，这个版本号有特殊字符

**Comment by nejisama** [comment]
we will fix it

**Comment by nejisama** [comment]
@peacocktrain can you tell me what special characters you set in your metrics?

**Comment by peacocktrain** [comment]
> @peacocktrain can you tell me what special characters you set in your metrics?
()

**Comment by nejisama** [comment]
#1164
