### ISSUE TITLE
Has mosn achieved the feature micro service pub/sub according to it?

### ISSUE THREAD

**Issue by SongYintao** [mosn/mosn#936]
hi，请教一个问题。在SofaStack的博客「[Service Mesh 在『路口』的产品思考与实践：务实是根本](https://www.sofastack.tech/blog/service-mesh-practice-in-production-at-ant-financial-wushi/)」 提到，蚂蚁在具体落地的时候，微服务的服务注册、发现都是通过SideCar来进行的。

![Uploading image.png…](https://cdn.nlark.com/yuque/0/2019/png/226702/1575015733311-75e91db8-5fa5-4c51-8666-0b02c9c45a2f.png)

在另一篇「[蚂蚁金服 Service Mesh 大规模落地系列 - RPC 篇](https://www.sofastack.tech/blog/service-mesh-practice-in-production-at-ant-financial-part4-rpc/)」中提到，RPC在落地篇里面sofaboot/sofarpc框架也是根据POD里面注入的环境变量来判断是否开启Mesh功能，来决定是否通过sidecar来进行服务的注册发现。

![Uploading image.png…](https://cdn.nlark.com/yuque/0/2019/png/226702/1574914852253-38155353-99a3-45e9-8281-3a08967a7b0c.png)

通过阅读sofa-rpc的代码，确实有一段Mesh Registry相关代码，来访问SideCar的接口进行服务的发现和订阅。但是，在Mosn里面并没有看到这些接口的实现。是不是Mosn关于这部分的代码并没有实现或者放出来哈[微笑]

总结：是不是github上发布的代码，和实际落地的存在着一些差距。这些距离之后是有什么打算吗？
@khotyn @taoyuanyuan

**Comment by taoyuanyuan** [comment]
针对这一块内部做了一些扩展，有着我们自身场景的考虑，并不一定对外都是适用的，代码就没有放出来。MOSN开源的目的是向着云原生Service Mesh标准走，这部分代码这也不太符合我们的初衷。
MOSN目前正在全面兼容istio的功能特性，也正在推动Istio来支持多协议场景。 
https://github.com/mosn/mosn/issues/891

**Comment by SongYintao** [comment]
> 针对这一块内部做了一些扩展，有着我们自身场景的考虑，并不一定对外都是适用的，代码就没有放出来。MOSN开源的目的是向着云原生Service Mesh标准走，这部分代码这也不太符合我们的初衷。
> MOSN目前正在全面兼容istio的功能特性，也正在推动Istio来支持多协议场景。
> #891

感谢
