### ISSUE TITLE
docker build失败

### ISSUE THREAD

**Issue by yiyanghua** [mosn/mosn#946]
### docker build失败

执行docker build 报错
docker build -f build/contrib/builder/image/Dockerfile .

### Environment

- MOSN master

### Logs

COPY failed: stat /var/lib/docker/tmp/docker-builder108074357/mosnd: no such file or directory

**Comment by rootsongjc** [comment]
@nejisama can you take a look?

**Comment by yiyanghua** [comment]
make build && make image  可以
