### ISSUE TITLE
./server.go:35:11: undefined: "mosn.io/mosn/pkg/buffer".NewIoBuffer

### ISSUE THREAD

**Issue by leongle** [mosn/mosn#981]
### Your question

mosn/ examples / codes / sofarpc-sample / server.go

35	iobuf := buffer.NewIoBuffer(102400)

go run server.go 失败

是不是pkg/buffer代码更新了，有什么替代方式吗？

### Environment

- MOSN Version
var Version = "0.4.0"

  型号名称：	MacBook Air
  型号标识符：	MacBookAir4,2
  处理器名称：	Intel Core i5
  处理器速度：	1.7 GHz
  处理器数目：	1
  核总数：	2
  L2 缓存（每个核）：	256 KB
  L3 缓存：	3 MB
  内存：	4 GB

### Logs

[mac@192 ~/go/src/mosn.io/mosn]$ cd examples/codes/sofarpc-sample/
[mac@192 ~/go/src/mosn.io/mosn/examples/codes/sofarpc-sample]$ go run server.go 
./server.go:35:11: undefined: "mosn.io/mosn/pkg/buffer".NewIoBuffer
[mac@192 ~/go/src/mosn.io/mosn/examples/codes/sofarpc-sample]$

**Comment by taoyuanyuan** [comment]
@leongle 上周做了代码迁移，把buffer迁移到单独的仓库了，mosn.io/pkg/buffer
这个example的示例还没有修改，  @nejisama 
你可以暂时改下import路径试试

**Comment by nejisama** [comment]
下次PR 一起修复

**Comment by nejisama** [comment]
fixed
