### ISSUE TITLE
virtual listener about cluster PassthroughCluster is not support?

### ISSUE THREAD

**Issue by NameHaibinZhang** [mosn/mosn#982]
### The New Feature

convertxds.go

if listenerConfig.Name == "virtual" {
		return listenerConfig
	}

PassthroughCluster can not find in mosn

Describe the new feature you want to support clearly.

### Your scenes

Describe your use scenes (why need this feature).

### Your advice

Describe the advice or solution of this new feature.

### Environment

- MOSN Version

**Comment by NameHaibinZhang** [comment]
if service is not in the same k8s cluster, for example，RDS in ali cloud，if all outbound request hijack to mosn 15001 port， and this request will can not request rds

**Comment by wangfakang** [comment]
You can do this using the `useOriginalDst` and `tcp_proxy`. In this way, the matched listener can be found based on the DST connection information, and `PassthroughCluster` cluster can be used if it cannot be found. BTW the type 'ORIGINAL_DST' is not currently supported by the cluster attribute in MOSN. 
```
[
    {
        "name": "virtual",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15001
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "tcp_proxy",
                        "config": {
                            "cluster": "PassthroughCluster"
                        }
                    }
                ]
            }
        ],
        "useOriginalDst": true
    }
]

  "cluster_manager":{     
     "clusters":[
        {
	  "Name":"PassthroughCluster",
	  "type": "SIMPLE",
	  "lb_type": "LB_RANDOM",
	  "max_request_per_conn": 1024,
	  "conn_buffer_limit_bytes":32768,
	  "hosts":[
	     {"address":"x.x.x.x:x"}
	  ]
	}
     ]
  }

```

**Comment by NameHaibinZhang** [comment]
> You can do this using the `useOriginalDst` and `tcp_proxy`. In this way, the matched listener can be found based on the DST connection information, and `PassthroughCluster` cluster can be used if it cannot be found. BTW the type 'ORIGINAL_DST' is not currently supported by the cluster attribute in MOSN.
> 
> ```
> [
>     {
>         "name": "virtual",
>         "address": {
>             "socketAddress": {
>                 "address": "0.0.0.0",
>                 "portValue": 15001
>             }
>         },
>         "filterChains": [
>             {
>                 "filters": [
>                     {
>                         "name": "tcp_proxy",
>                         "config": {
>                             "cluster": "PassthroughCluster"
>                         }
>                     }
>                 ]
>             }
>         ],
>         "useOriginalDst": true
>     }
> ]
> 
>   "cluster_manager":{     
>      "clusters":[
>         {
> 	  "Name":"PassthroughCluster",
> 	  "type": "SIMPLE",
> 	  "lb_type": "LB_RANDOM",
> 	  "max_request_per_conn": 1024,
> 	  "conn_buffer_limit_bytes":32768,
> 	  "hosts":[
> 	     {"address":"x.x.x.x:x"}
> 	  ]
> 	}
>      ]
>   }
> ```

this is the default config
but xds api get the PassthroughCluster config from pilot, then the hosts is nil

**Comment by wangfakang** [comment]
@NameHaibinZhang The standard Istio approach is that the cluster of the PassthroughCluster needs to support `ORIGINAL_DST` type, which can be forwarded directly based on the DST connection information, And don't need to get hosts from pilot.

**Comment by fyery-chen** [comment]
How does it work in istio? Can not visit any other addresses in the pod with sidecar mosn.

**Comment by fyery-chen** [comment]
https://github.com/mosn/mosn/blob/1609ae144136039508dda6d0c5d03c1f732cb107/pkg/server/handler.go#L598
If `use_original_dest` is set to true, then how to address the situation that there isn't  a listener that listening `originalDstIP:originalDstPort`. For example, how to access mosn.io(e.g 192.168.11.10:80) because there isn't a listener which is listening `192.168.11.10:80`. I can't find any logic in the function `UseOriginalDst`.

**Comment by wangfakang** [comment]
This scenario requires both filters `orignal_dst` and `tcp_prxoy` to be configured together. However, since the MOSN's cluster does not support the `original_dst` type. As mentioned above, so the current situation can only be forwarded to a simple cluster.

**Comment by fyery-chen** [comment]
Do you have roadmap to support `ORIGINAL_DST` type?

**Comment by fyery-chen** [comment]
Maybe I see, we can use the crd `envoyfilters.networking.istio.io` in istio to achieve what we want.
So in this scenario, mosn doesn't need to support `ORIGINAL_DST` type. Right?

**Comment by wangfakang** [comment]
> Do you have roadmap to support `ORIGINAL_DST` type?

We implemented this feature in this pr https://github.com/mosn/mosn/pull/1005, you can try it.

**Comment by wangfakang** [comment]
It has been supported by https://github.com/mosn/mosn/pull/1005 .
