### ISSUE TITLE
No tcp_proxy filter named PassthroughCluster 

### ISSUE THREAD

**Issue by fyery-chen** [mosn/mosn#984]
### Describe the bug
There is no tcp_proxy filter named `PassthroughCluster `, so all the traffic which to the port XX is routed to the filter named `BlackHoleCluster` if there is no listener listening XX in it.

### Expected behavior
There should be a filter named `PassthroughCluster` in outbound listers' filter policy,  so we can access some public address.

### Actual behavior
No tcp_proxy filter named `PassthroughCluster`.
### Steps to reproduce
Using `mosn` instead of envoy in istio-1.1.4.
Deploy a service named A in the namespace `default`.
Access `baidu.com` in one instance of service A.
Can't access it.
### Minimal yet complete reproducer code (or GitHub URL to code)

- MOSN Version 0.8.1

**Comment by wangfakang** [comment]
https://github.com/mosn/mosn/issues/982 Here is a discussion of a similar problem, you can refer to it.

**Comment by fyery-chen** [comment]
How does it work in istio? Can not visit any other addresses in the pod with sidecar mosn.

**Comment by wangfakang** [comment]
It has been supported by https://github.com/mosn/mosn/pull/1005.
